@startuml
!include savingsStyle.puml

skinparam arrowThickness 1.1
skinparam arrowColor #000000

class Savings as "__s7:Savings__" \
SAVINGS_COLOUR
class PercentageAmount as \
"__percentage:PercentageAmount__" \
PERCENT_COLOUR {
    percentage: 20
}
class MonetaryAmount as \
"__monetaryAmount:MonetaryAmount__" \
MONEY_COLOUR {
    monetaryAmount: 1.5
}

Savings --> PercentageAmount
Savings --> MonetaryAmount

@enduml
