@startuml
start
:AddGroupCommand object is
created with the fields group
            and module;

:The execute method of AddGroupCommand
                           is called;

:Get the module from TA-Tracker's
                    model;

:Add group to the module;


:return command result;

stop
@enduml
