@startuml
!include ../style.puml
package Model {

skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

class TaTracker

package Module {
class Module
class UniqueModuleList
}
package Group {
class Group
class UniqueGroupList
}

package Student {
class Student
class UniqueStudentList
}
}

TaTracker --> "1 " UniqueModuleList

UniqueModuleList -right-> "*" Module

Module -right-> "1" UniqueGroupList

UniqueGroupList -right-> "*" Group

Group --> "1 " UniqueStudentList
UniqueStudentList -left-> "*" Student

@enduml

