@startuml
!include ../style.puml
skinparam arrowThickness 1.1
skinparam arrowColor UI_COLOR_T4
skinparam classBackgroundColor UI_COLOR

package UI <<Rectangle>>{
    Interface Ui <<Interface>>
    Class UiManager
    Class MainWindow

    Class "{abstract}\nUiPart" as UiPart
    Class CommandBox
    Class ResultDisplay

    Class HomePanel
    Class ExerciseListPanel
    Class WorkoutListPanel
    Class ScheduledWorkoutListPanel
    Class LogListPanel
    Class AboutDisplay
    Class StatisticsWindow
}

package Logic <<Rectangle>> {
    Class HiddenLogic #FFFFFF
}

Class HiddenOutside #FFFFFF
HiddenOutside ..> Ui

UiManager .left.|> Ui
UiManager -down-> MainWindow
UiManager -up-> Logic
MainWindow -up-> Logic

MainWindow *-down-> CommandBox
MainWindow *-down-> ResultDisplay
MainWindow *-down-> HomePanel
MainWindow *-down-> ExerciseListPanel
MainWindow *-down-> WorkoutListPanel
MainWindow *-down-> ScheduledWorkoutListPanel
MainWindow *-down-> LogListPanel
MainWindow *-down-> AboutDisplay
MainWindow *-down-> StatisticsWindow

MainWindow --|> UiPart
CommandBox --|> UiPart
ResultDisplay --|> UiPart
HomePanel --|> UiPart
ExerciseListPanel --|> UiPart
WorkoutListPanel --|> UiPart
ScheduledWorkoutListPanel --|> UiPart
LogListPanel --|> UiPart
AboutDisplay --|> UiPart
StatisticsWindow --|> UiPart

CommandBox -right[hidden]- ResultDisplay
ResultDisplay -right[hidden]- HomePanel
HomePanel -right[hidden]- ExerciseListPanel
ExerciseListPanel -right[hidden]- WorkoutListPanel
WorkoutListPanel -right[hidden]- ScheduledWorkoutListPanel
ScheduledWorkoutListPanel -right[hidden]- LogListPanel
LogListPanel -right[hidden]- AboutDisplay
AboutDisplay -right[hidden]- StatisticsWindow
@enduml
