@startuml
start
:User executes find command;

if () then ([command is valid])
    :Instantiate a Find Command with the corresponding keywords;
    :Executes Find Command;
    :Update UI with filtered list;
else ([else])
    :Throw an Exception;
    :Update UI to notify the users;
endif
stop
@enduml

