@startuml

!include ../style.puml
show interface members
skinparam arrowThickness 1.1
skinparam classBackgroundColor MODEL_COLOR

abstract class Command

interface Parser {
	T parse(String userInput)
}

class FindCommand

class DoneSessionPredicate

class FindCommandParser

Command <|.. FindCommand

Parser <|-- FindCommandParser

DoneSessionPredicate <.. FindCommand
DoneSessionPredicate <.. FindCommandParser


@enduml

