@startuml
!include ../style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

GlobalData *--> Budget
GlobalData *--> TransactionList
GlobalData *--> Balance
GlobalData *--> LocalDate
@enduml
