@startuml
start
:A DoneSessionCommand is called;

  :The duration of the session is added to TotalHours in TaTracker;
  :TotalEarnings in the UI is increased;
  :Session is added to UniqueDoneSessionList;

  if () then (session is recurring)
    :A new session is created with startTime
    and endTime are incremented accordingly;
    :New session is added to UniqueSessionList;

    else (session is not recurring)
endif
    :Old session is deleted from UniqueSessionList;

    stop
@enduml
