@startuml
start
:User enters the add reminder command;

if () then ([invalid format])
    :Shows invalid format;
else ([valid format])
    if () then ([module does not exist])
        :Shows "Module does not exist error" message;
    else ([else])
        if () then ([index out of bounds])
            :Shows activity does not exist error;
        else ([else])
            if () then ([activity's date already past])
                :Shows activity has already passed;
            else ([else])
                if () then ([reminder date passed])
                    :Shows reminder date has already passed;
                else ([else])
                    :Create Reminder class;
                    :Add to ActiveReminderList;
                    :Shows reminder has been successfully added;
endif
endif
endif
endif
endif
:Return command result based on the message shown to UI;
stop
@enduml
