@startuml
!include style.puml

Actor User as user USER_COLOR
Participant ":UI" as ui UI_COLOR
Participant ":Logic" as logic LOGIC_COLOR
Participant ":Model" as splitterModel MODEL_COLOR
Participant ":Storage" as splitterStorage STORAGE_COLOR

user -[USER_COLOR]> ui : "deleteitem 1"
activate ui UI_COLOR

ui -[UI_COLOR]> logic : "deleteitem 1"
activate logic LOGIC_COLOR

logic -[LOGIC_COLOR]> splitterModel : isReceiptDone()
activate splitterModel MODEL_COLOR

splitterModel -[MODEL_COLOR]-> logic
logic -[LOGIC_COLOR]> splitterModel : getEntry(1)
splitterModel -[MODEL_COLOR]-> logic
logic -[LOGIC_COLOR]> splitterModel : removeAmount(person, amount)
splitterModel -[MODEL_COLOR]-> logic
logic -[LOGIC_COLOR]> splitterModel : deleteEntry(1)
splitterModel -[MODEL_COLOR]-> logic
deactivate splitterModel

logic -[LOGIC_COLOR]> splitterStorage : savePersonAmountBook(personAmountBook)
activate splitterStorage STORAGE_COLOR

splitterStorage -[STORAGE_COLOR]> splitterStorage : Save to file
activate splitterStorage STORAGE_COLOR_T1
deactivate splitterStorage

splitterStorage --[STORAGE_COLOR]> logic
deactivate splitterStorage

logic -[LOGIC_COLOR]> splitterStorage : saveReceiptBook(receiptBook)
activate splitterStorage STORAGE_COLOR

splitterStorage -[STORAGE_COLOR]> splitterStorage : Save to file
activate splitterStorage STORAGE_COLOR_T1
deactivate splitterStorage

splitterStorage --[STORAGE_COLOR]> logic
deactivate splitterStorage

logic --[LOGIC_COLOR]> ui : commandResult
deactivate logic

ui--[UI_COLOR]> user : result
deactivate ui
@enduml
