@startuml
!include style.puml

Actor User as user USER_COLOR
Participant ":UI" as ui UI_COLOR
Participant ":Logic" as logic LOGIC_COLOR
Participant ":Model" as splitterModel MODEL_COLOR
Participant ":Storage" as splitterStorage STORAGE_COLOR

user -[USER_COLOR]> ui : "delete 1"
activate ui UI_COLOR

ui -[UI_COLOR]> logic : execute("delete 1")
activate logic LOGIC_COLOR

logic -[LOGIC_COLOR]> splitterModel : deletePerson(p)
activate splitterModel MODEL_COLOR

splitterModel -[MODEL_COLOR]-> logic
deactivate splitterModel

logic -[LOGIC_COLOR]> splitterStorage : saveAddressBook(addressBook)
activate splitterStorage STORAGE_COLOR

splitterStorage -[STORAGE_COLOR]> splitterStorage : Save to file
activate splitterStorage STORAGE_COLOR_T1
deactivate splitterStorage

splitterStorage --[STORAGE_COLOR]> logic
deactivate splitterStorage

logic --[LOGIC_COLOR]> ui
deactivate logic

ui--[UI_COLOR]> user
deactivate ui
@enduml
