@startuml
!include style.puml

skinparam ParticipantPadding 0

actor User

box <color:white>Application</color> #999999
participant ":MainApp" as MainApp #333333
end box

box "<color:white>Model</color>" MODEL_COLOR_T1
participant ":ModelManager" as ModelManager MODEL_COLOR
participant ":CouponStash" as CouponStash MODEL_COLOR
participant ":FilteredList" as FilteredList MODEL_COLOR
participant ":Coupon" as Coupon MODEL_COLOR
end box

User -> MainApp: Opens Coupon Stash
activate MainApp
create ModelManager

MainApp -> ModelManager: ModelManager()
activate ModelManager

create CouponStash
ModelManager -> CouponStash: CouponStash(couponStash)
activate CouponStash
CouponStash --> ModelManager: couponStash
deactivate CouponStash

ModelManager -> CouponStash: archiveExpiredCoupons()
activate CouponStash

loop for each coupon
    CouponStash -> Coupon: getExpiryDate()
    activate Coupon
    Coupon --> CouponStash : expiryDate
    deactivate Coupon

    opt has expired
        CouponStash -> Coupon: archive()
        activate Coupon
        Coupon --> CouponStash: archivedCoupon
        deactivate Coupon
    end
end

CouponStash --> ModelManager: updatedCouponStash
deactivate CouponStash

create FilteredList
ModelManager -> FilteredList: FilteredList<>(sortedCoupons, PREDICATE_SHOW_ALL_ACTIVE_COUPONS)
activate FilteredList
FilteredList --> ModelManager: filteredCoupons
deactivate FilteredList

MainApp <-- ModelManager: modelManager
deactivate ModelManager

User <-- MainApp: Display active coupons

@enduml
