@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

CouponStash *-right-> "1" UniqueCouponList
CouponStash *-right-> "1" UniqueTagList
UniqueTagList -[hidden]down- UniqueCouponList
UniqueTagList -[hidden]down- UniqueCouponList

UniqueTagList *-right-> "*" Tag
UniqueCouponList o-right-> Coupon

Coupon o-up-> "*" Tag

Coupon *--> Name
Coupon *--> PromoCode
Coupon *--> Savings
Coupon *--> ExpiryDate

note "Not all Coupon fields\nshown for simplicity" as N1
N1 .left. Coupon
@enduml
