@startuml
!include style.puml

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":FoodBookParser" as FoodBookParser LOGIC_COLOR
participant ":BmiCommandParser" as BmiCommandParser LOGIC_COLOR
participant "b:BmiCommand" as BmiCommand LOGIC_COLOR
participant ":CommandResult" as CommandResult LOGIC_COLOR
end box

[-> LogicManager : execute("bmi")
activate LogicManager

LogicManager -> FoodBookParser : parseCommand("bmi")
activate FoodBookParser

create BmiCommandParser
FoodBookParser -> BmiCommandParser
activate BmiCommandParser

BmiCommandParser --> FoodBookParser
deactivate BmiCommandParser

FoodBookParser -> BmiCommandParser : parse("")
activate BmiCommandParser

create BmiCommand
BmiCommandParser -> BmiCommand
activate BmiCommand

BmiCommand --> BmiCommandParser : b
deactivate BmiCommand

BmiCommandParser --> FoodBookParser : b
deactivate BmiCommandParser
'Hidden arrow to position the destroy marker below the end of the activation bar.
BmiCommandParser -[hidden]-> FoodBookParser
destroy BmiCommandParser

FoodBookParser --> LogicManager : b
deactivate FoodBookParser

LogicManager -> BmiCommand : execute()
activate BmiCommand

create CommandResult
BmiCommand -> CommandResult
activate CommandResult

CommandResult --> BmiCommand
deactivate CommandResult

BmiCommand --> LogicManager : result
deactivate BmiCommand

[<--LogicManager
deactivate LogicManager
@enduml
