@startuml
!include style.puml

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":InventoryManagerParser" as InventoryManagerParser LOGIC_COLOR
participant ":BuyCommandParser" as BuyCommandParser LOGIC_COLOR
participant "b:BuyCommand" as BuyCommand LOGIC_COLOR
participant ":CommandResult" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
end box

[-> LogicManager : execute("buy 1 g/Apple q/50")
activate LogicManager

LogicManager -> InventoryManagerParser : parseCommand("buy 1 g/Apple q/50")
activate InventoryManagerParser

create BuyCommandParser
InventoryManagerParser -> BuyCommandParser
activate BuyCommandParser

BuyCommandParser --> InventoryManagerParser
deactivate BuyCommandParser

InventoryManagerParser -> BuyCommandParser : parse("1 g/Apple q/50")
activate BuyCommandParser

create BuyCommand
BuyCommandParser -> BuyCommand
activate BuyCommand

BuyCommand --> BuyCommandParser : b
deactivate BuyCommand

BuyCommandParser --> InventoryManagerParser : b
deactivate BuyCommandParser
'Hidden arrow to position the destroy marker below the end of the activation bar.
BuyCommandParser -[hidden]-> InventoryManagerParser
destroy BuyCommandParser

InventoryManagerParser --> LogicManager : b
deactivate InventoryManagerParser

LogicManager -> BuyCommand : execute()
activate BuyCommand

BuyCommand -> Model : getFilteredSupplierList()
activate Model
Model --> BuyCommand

BuyCommand -> Model : addGood(boughtGood)
Model --> BuyCommand

BuyCommand -> Model : addTransaction(buyTransaction)
Model --> BuyCommand

BuyCommand -> Model : commit()
Model --> BuyCommand

deactivate Model

create CommandResult
BuyCommand -> CommandResult
activate CommandResult

CommandResult --> BuyCommand
deactivate CommandResult

BuyCommand --> LogicManager : result
deactivate BuyCommand

[<--LogicManager
deactivate LogicManager
@enduml
