@startuml
!include style.puml

'actor User

box "<color:black>Logic</color>" LOGIC_COLOR_T1
participant ":ExpiringCommand" as ExpiringCommand LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":ModelManager" as ModelManager MODEL_COLOR
participant ":ObservableMonthView" as ObservableMonthView MODEL_COLOR
end box

box "<color:black>UI</color>" UI_COLOR_T1
participant ":CalendarPane" as CalendarPane UI_COLOR
participant "d:DateCell" as DateCell UI_COLOR
end box

[-> ExpiringCommand: execute(model, "expiring my/9-2020")
activate ExpiringCommand
ExpiringCommand -> ModelManager :updateMonthView()
deactivate ExpiringCommand

activate ModelManager
ModelManager -> ObservableMonthView : setValue()
deactivate ModelManager

activate ObservableMonthView
ObservableMonthView -> CalendarPane: notify()
deactivate ObservableMonthView

activate CalendarPane
CalendarPane -> CalendarPane: fillUpCalendar()
activate CalendarPane

ref over CalendarPane, DateCell : Set details of DateCell
CalendarPane --> CalendarPane

deactivate CalendarPane


@enduml
