@startuml

start
:User enter clear command;
if () then ([Arguments are empty])
    :Create a new Clear Command with no flags;
else ([else])
    :Create a new Clear Command with flags;
endif
:Executes the command;

if () then (([flags contains '-f' flag])
    if () then ([flags also contains '-o' flag])
    :Clear the order book list;
    else ([else])
        if() then ([flags also contain '-r' flag])
        :Clear the return order book list;
        else ([flags only contains 'f' flag])
        :Clear both order book list and
         return order book list;
        endif
    endif
    :Display success message to the User;

else ([else])
    if() then([flags do not contains 'f' flag])
        if () then ([flags contains '-o' flag])
            :Display the confirmation message
             to clear order book list to user;
        else ([flags contains 'r' flag])
            :Display the confirmation message
             to clear return order book list to user;
        endif
    else ([flags equal to null])
    :Display the confirmation message
     to clear both order book list
     and return order book list to user;
    endif
    if () then ([User press yes button])
        :Clear the respective order book list based on the command;
        :Display clear success message to user;
    else ([User press no button])
    endif
endif
stop
@enduml
