@startuml
skinparam backgroundColor #ffffff
skinparam classAttributeIconSize 0
hide circle

abstract class "{abstract}\nCommand" {
    + {abstract} execute(model : Model) : CommandResult
}

class Model <<Interface>> {
    + setOrderBook(orderBook : ReadOnlyOrderBook) : void
    + setReturnOrderBook(returnOrderBook : ReadOnlyReturnOrderBook) : void
}

Model ..> ReadOnlyOrderBook
Model ..> ReadOnlyReturnOrderBook

class ReadOnlyOrderBook {
    + getOrderList() : ObservableList<Order>
}

class ReadOnlyReturnOrderBook {
    + getReturnOrderList() : ObservableList<ReturnOrder>
}

class ClearCommand {
    /' Fields '/
    - flags : HashSet<String>

    /' Methods '/
    + execute(model : Model) : CommandResult
    - updateModel(model : Model) : CommandResult
}

ClearCommand ..> Model
ClearCommand --up|> "{abstract}\nCommand"
@enduml
