@startuml
!include style.puml

Participant ":CommandBox" as commandBox UI_COLOR
Participant ":TextField" as textField UI_COLOR
Participant ":ResultDisplay" as resultDisplay UI_COLOR
Participant ":Autocomplete" as autoComplete LOGIC_COLOR
' Participant ":Trie" as trie LOGIC_COLOR
' Participant "node:Node" as node LOGIC_COLOR
' Participant "similarWordsResult:SimilarWordsResult" as similarWordsResult LOGIC_COLOR
Participant "acResult:AutocompleteResult" as autoCompleteResult LOGIC_COLOR

-[UI_COLOR]> commandBox : handleTabKey()
activate commandBox UI_COLOR

commandBox -[UI_COLOR]> textField : getText()
activate textField UI_COLOR

textField -[UI_COLOR]-> commandBox : "gra"
deactivate textField

commandBox -[UI_COLOR]> textField : getCaretPosition()
activate textField UI_COLOR

textField -[UI_COLOR]-> commandBox : 3
deactivate textField

commandBox -[UI_COLOR]> autoComplete : execute("gra", 3)
activate autoComplete LOGIC_COLOR

ref over autoComplete, autoCompleteResult : get autocomplete result
note right
note that the acResult object is
actually created within this ref
end note

' autoComplete -[LOGIC_COLOR]> trie : listAllSimilarWords("gra")
' activate trie LOGIC_COLOR

' trie -[LOGIC_COLOR]> trie : getLongestPrefixNode("gra")
' activate trie LOGIC_COLOR_T1
' trie -[LOGIC_COLOR]-> trie : node
' deactivate trie

' trie -[LOGIC_COLOR]> node : constructWord()
' activate node LOGIC_COLOR

' node -[LOGIC_COLOR]-> trie : "graph"
' deactivate node

' trie -[LOGIC_COLOR]> node : isWordEnd()
' activate node LOGIC_COLOR

' node -[LOGIC_COLOR]-> trie : true
' deactivate node

' create similarWordsResult
' trie -[LOGIC_COLOR]> similarWordsResult : SimilarWordsResult("graph", ["graph"])
' activate similarWordsResult LOGIC_COLOR

' similarWordsResult -[LOGIC_COLOR]-> trie : similarWordsResult
' deactivate similarWordsResult

' trie -[LOGIC_COLOR]-> autoComplete : similarWordsResult
' deactivate trie LOGIC_COLOR

' autoComplete -[LOGIC_COLOR]> similarWordsResult : hasOnlyOneWord()
' activate similarWordsResult LOGIC_COLOR

' similarWordsResult -[LOGIC_COLOR]-> autoComplete : true
' deactivate similarWordsResult

' autoComplete -[LOGIC_COLOR]> similarWordsResult : getSingleWord()
' activate similarWordsResult LOGIC_COLOR

' similarWordsResult -[LOGIC_COLOR]-> autoComplete : "graph"
' deactivate similarWordsResult

' autoComplete -[LOGIC_COLOR]> autoComplete : singleCommandHandler("graph")
' activate autoComplete LOGIC_COLOR_T1

' autoComplete -[LOGIC_COLOR]> autoComplete : generatePrefixesString(GraphCommand.PREFIXES)
' activate autoComplete LOGIC_COLOR_T1
' autoComplete -[LOGIC_COLOR]-> autoComplete : "graph n/ a/ sd/ ed/"
' deactivate autoComplete

' create autoCompleteResult
' autoComplete -[LOGIC_COLOR]> autoCompleteResult : AutocompleteResult("graph n/ a/ sd/ ed/", GraphCommand.MESSAGE_USAGE, 8)
' activate autoCompleteResult LOGIC_COLOR

' autoCompleteResult -[LOGIC_COLOR]-> autoComplete : autoCompleteResult
' deactivate autoCompleteResult
' autoComplete -[LOGIC_COLOR]-> autoComplete : autoCompleteResult
' deactivate autoComplete

autoComplete -[LOGIC_COLOR]-> commandBox : acResult
deactivate autoComplete

commandBox -[UI_COLOR]> autoCompleteResult : getTextToSet()
activate autoCompleteResult LOGIC_COLOR

autoCompleteResult -[LOGIC_COLOR]-> commandBox : "graph n/ a/ sd/ ed/"
deactivate autoCompleteResult

commandBox -[UI_COLOR]> autoCompleteResult : getTextToFeedback()
activate autoCompleteResult LOGIC_COLOR

autoCompleteResult -[LOGIC_COLOR]-> commandBox : GraphCommand.MESSAGE_USAGE
deactivate autoCompleteResult

commandBox -[UI_COLOR]> autoCompleteResult : getCaretPositionToSet
activate autoCompleteResult LOGIC_COLOR

autoCompleteResult -[LOGIC_COLOR]-> commandBox : 8
deactivate autoCompleteResult

commandBox -[UI_COLOR]> textField : setText("graph n/ a/ sd/ ed/")
activate textField UI_COLOR

textField -[UI_COLOR]-> commandBox
deactivate textField

commandBox -[UI_COLOR]> textField : positionCaret(8)
activate textField UI_COLOR

textField -[UI_COLOR]-> commandBox
deactivate textField

commandBox -[UI_COLOR]> resultDisplay : setFeedbackToUser(GraphCommand.MESSAGE_USAGE)
activate resultDisplay UI_COLOR

resultDisplay -[UI_COLOR]-> commandBox
deactivate resultDisplay

[<[UI_COLOR]-- commandBox

@enduml
