@startuml
!include style.puml

Class CommandBox UI_COLOR
Class TextField UI_COLOR
Class ResultDisplay UI_COLOR
Class AutoComplete LOGIC_COLOR
Class Trie LOGIC_COLOR
Class Node LOGIC_COLOR
Class SimilarWordsResult LOGIC_COLOR
Class AutoCompleteResult LOGIC_COLOR

CommandBox "1" *-down-> "1" TextField
CommandBox "1" *-up-> "1" ResultDisplay
CommandBox "1" *-left-> "1" AutoComplete
(CommandBox, AutoComplete) .. AutoCompleteResult
AutoComplete "1" *-right-> "1" Trie
(AutoComplete, Trie) .. SimilarWordsResult
Trie "1" *-up-> "1" Node
Node "0..1" *-- "*" Node

@enduml
