@startuml
!include style.puml

Participant ":CommandBox" as commandBox UI_COLOR
Participant ":TextField" as textField UI_COLOR
Participant ":CommandHistory" as commandHistory LOGIC_COLOR
Participant ":CommandHistoryState" as commandHistoryState MODEL_COLOR
Participant ":StorageReaderWriter" as storageReaderWriter STORAGE_COLOR

-[UI_COLOR]> commandBox : handleCommandEntered()
activate commandBox UI_COLOR

commandBox -[UI_COLOR]> textField : getText()
activate textField UI_COLOR 

textField -[UI_COLOR]> commandBox : "list-c"
deactivate textField

commandBox -[UI_COLOR]> commandHistory : addToHistory("list-c")
activate commandHistory LOGIC_COLOR

commandHistory -[LOGIC_COLOR]> commandHistoryState : add("list-c")
activate commandHistoryState MODEL_COLOR

commandHistoryState -[MODEL_COLOR]-> commandHistory
deactivate commandHistoryState

commandHistory -[LOGIC_COLOR]> commandHistoryState : getCurrentState()
activate commandHistoryState MODEL_COLOR

commandHistoryState -[MODEL_COLOR]-> commandHistory : ArrayList<String> history
deactivate commandHistoryState

commandHistory -[LOGIC_COLOR]> storageReaderWriter : writeToStorage(history)
activate storageReaderWriter STORAGE_COLOR

storageReaderWriter -[STORAGE_COLOR]> storageReaderWriter : Save to file
activate storageReaderWriter STORAGE_COLOR_T1
deactivate storageReaderWriter

storageReaderWriter -[STORAGE_COLOR]> commandHistory
deactivate storageReaderWriter

commandHistory -[LOGIC_COLOR]> commandBox
deactivate commandHistory

[<[UI_COLOR]-- commandBox

@enduml
