@startuml
!include style.puml

start
:User inputs Count command;

If () then ([Correct command format])
    :Count all the recipes;
    :Returns success message;
else ([Syntax error])
    :Returns failure message
    (Invalid Command);
endif
:LogicManager prints message to user;

stop
@enduml
