@startuml
!include style.puml

skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

Class Coupon

Package Savings {
Class DateSavingsSumMap
Class PureMonetarySavings
}

Class java.time.LocalDate #000000

Coupon *--> DateSavingsSumMap : total savings
DateSavingsSumMap ..> java.time.LocalDate : keys
DateSavingsSumMap ..> PureMonetarySavings : values

@enduml
