@startuml
!include style.puml

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":FoodBookParser" as FoodBookParser LOGIC_COLOR
participant ":DeleteCommandParser" as DeleteCommandParser LOGIC_COLOR
participant "d:DeleteCommand" as DeleteCommand LOGIC_COLOR
participant ":CommandResult" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
end box

box Storage STORAGE_COLOR_T1
participant ":FoodBookStorage" as FoodBookStorage STORAGE_COLOR
end box

[-> LogicManager : execute("delete 3")
activate LogicManager

LogicManager -> FoodBookParser : parseCommand("delete 3")
activate FoodBookParser

create DeleteCommandParser
FoodBookParser -> DeleteCommandParser
activate DeleteCommandParser

DeleteCommandParser --> FoodBookParser
deactivate DeleteCommandParser

FoodBookParser -> DeleteCommandParser : parse("3")
activate DeleteCommandParser

create DeleteCommand
DeleteCommandParser -> DeleteCommand
activate DeleteCommand

DeleteCommand --> DeleteCommandParser : d
deactivate DeleteCommand

DeleteCommandParser --> FoodBookParser : d
deactivate DeleteCommandParser
'Hidden arrow to position the destroy marker below the end of the activation bar.
DeleteCommandParser -[hidden]-> FoodBookParser
destroy DeleteCommandParser

FoodBookParser --> LogicManager : d
deactivate FoodBookParser

LogicManager -> DeleteCommand : execute()
activate DeleteCommand

DeleteCommand -> Model : deleteFood(3)
activate Model

Model --> DeleteCommand
deactivate Model

create CommandResult
DeleteCommand -> CommandResult
activate CommandResult

CommandResult --> DeleteCommand
deactivate CommandResult

DeleteCommand --> LogicManager : result
deactivate DeleteCommand

LogicManager -> FoodBookStorage : saveFoodBook(foodBook)
activate FoodBookStorage

FoodBookStorage --> LogicManager
deactivate FoodBookStorage

[<--LogicManager
deactivate LogicManager
@enduml
