@startuml
!include style.puml

box Ui UI_COLOR_T1
participant ":CommandBox" as CommandBox UI_COLOR
participant ":MainWindow" as MainWindow UI_COLOR
end box

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":ModdyParser" as ModdyParser LOGIC_COLOR
participant ":DeleteCommandParser" as DeleteCommandParser LOGIC_COLOR
participant "d:DeleteCommand" as DeleteCommand LOGIC_COLOR
participant ":CommandResult" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
participant ":Profile" as Profile MODEL_COLOR
participant ":Module" as Module MODEL_COLOR
participant ":Deadline" as Deadline MODEL_COLOR
end box

[-> CommandBox : "delete\n m/CS2101 t/work"
activate CommandBox

CommandBox -> MainWindow : executeCommand("delete\n m/CS2101 t/work")
activate MainWindow

MainWindow -> LogicManager : execute("delete\n m/CS2101 t/work")
activate LogicManager

LogicManager -> ModdyParser : parseCommand("delete\n m/CS2101 t/work")
activate ModdyParser

create DeleteCommandParser
ModdyParser -> DeleteCommandParser
activate DeleteCommandParser

DeleteCommandParser --> ModdyParser
deactivate DeleteCommandParser

ModdyParser -> DeleteCommandParser : parse("m/CS2101 t/work")
activate DeleteCommandParser

create DeleteCommand
DeleteCommandParser -> DeleteCommand
activate DeleteCommand

DeleteCommand --> DeleteCommandParser : d
deactivate DeleteCommand

DeleteCommandParser --> ModdyParser : d
deactivate DeleteCommandParser
'Hidden arrow to position the destroy marker below the end of the activation bar.
DeleteCommandParser -[hidden]-> ModdyParser
destroy DeleteCommandParser

ModdyParser --> LogicManager : d
deactivate ModdyParser

LogicManager -> DeleteCommand : execute()
activate DeleteCommand

DeleteCommand -> Model : getFirstProfile()
activate Model

Model --> DeleteCommand
deactivate Model

DeleteCommand -> Profile
activate Profile

Profile -> Module : getModule()
activate Module

Module --> Profile
deactivate Module

Profile --> DeleteCommand
deactivate Profile

DeleteCommand -> Module
activate Module

Module -> Deadline : deleteDeadline()
activate Deadline

Deadline -> Module
deactivate Deadline
Deadline -[hidden]-> Module
destroy Deadline

Module -> DeleteCommand
deactivate Module

create CommandResult
DeleteCommand -> CommandResult
activate CommandResult

CommandResult --> DeleteCommand
deactivate CommandResult

DeleteCommand --> LogicManager : result
deactivate DeleteCommand

LogicManager --> MainWindow
deactivate LogicManager

MainWindow --> CommandBox

[<-- CommandBox
@enduml
