@startuml
!include style.puml

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":FitBizParser" as FitBizParser LOGIC_COLOR
participant ":DeleteCommandParser" as DeleteCommandParser LOGIC_COLOR
participant "d:DeleteCommand" as DeleteCommand LOGIC_COLOR
participant ":CommandResult" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
end box

[-[LOGIC_COLOR]> LogicManager : execute("delete-c 1")
activate LogicManager LOGIC_COLOR

LogicManager -[LOGIC_COLOR]> FitBizParser : parseCommand("delete-c 1")
activate FitBizParser LOGIC_COLOR

create DeleteCommandParser
FitBizParser -[LOGIC_COLOR]> DeleteCommandParser : DeleteCommandParser()
activate DeleteCommandParser LOGIC_COLOR

DeleteCommandParser --[LOGIC_COLOR]> FitBizParser
deactivate DeleteCommandParser

FitBizParser -[LOGIC_COLOR]> DeleteCommandParser : parse("1")
activate DeleteCommandParser LOGIC_COLOR

create DeleteCommand
DeleteCommandParser -[LOGIC_COLOR]> DeleteCommand : DeleteCommand()
activate DeleteCommand LOGIC_COLOR

DeleteCommand --[LOGIC_COLOR]> DeleteCommandParser : d
deactivate DeleteCommand

DeleteCommandParser --[LOGIC_COLOR]> FitBizParser : d
deactivate DeleteCommandParser

FitBizParser --[LOGIC_COLOR]> LogicManager : d
deactivate FitBizParser

LogicManager -[LOGIC_COLOR]> DeleteCommand : execute()
activate DeleteCommand LOGIC_COLOR

DeleteCommand -[LOGIC_COLOR]> Model : deleteClient(1)
activate Model MODEL_COLOR

Model --[MODEL_COLOR]> DeleteCommand
deactivate Model

create CommandResult
DeleteCommand -[LOGIC_COLOR]> CommandResult : CommandResult()
activate CommandResult LOGIC_COLOR

CommandResult --[LOGIC_COLOR]> DeleteCommand
deactivate CommandResult

DeleteCommand --[LOGIC_COLOR]> LogicManager : result
deactivate DeleteCommand

[<[LOGIC_COLOR]--LogicManager : result
deactivate LogicManager
@enduml
