@startuml
/' @author @cherweijie'/

!include style.puml

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":DelinoParser" as DelinoParser LOGIC_COLOR
participant ":DeliveredCommandParser" as DeliveredCommandParser LOGIC_COLOR
participant "d:DeliveredCommand" as DeliveredCommand LOGIC_COLOR
participant ":CommandResult" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
participant ":Order" as Order LOGIC_COLOR
end box

[-> LogicManager : execute("delivered -o 1")
activate LogicManager

LogicManager -> DelinoParser : parseCommand("delivered -o 1")
activate DelinoParser

create DeliveredCommandParser
DelinoParser -> DeliveredCommandParser
activate DeliveredCommandParser
DeliveredCommandParser --> DelinoParser
deactivate DeliveredCommandParser

DelinoParser -> DeliveredCommandParser : parse("-o 1")
activate DeliveredCommandParser

create DeliveredCommand
DeliveredCommandParser -> DeliveredCommand
activate DeliveredCommand

DeliveredCommand --> DeliveredCommandParser : d
deactivate DeliveredCommand

DeliveredCommandParser --> DelinoParser : d
deactivate DeliveredCommandParser
'Hidden arrow to position the destroy marker below the end of the activation bar.
DeliveredCommandParser -[hidden]-> DelinoParser
destroy DeliveredCommandParser

DelinoParser --> LogicManager : d
deactivate DelinoParser

ref over LogicManager, Model, Order : Execution of DeliveredCommand

[<--LogicManager : result
deactivate LogicManager
@enduml
