@startuml
/' @author @jarrod-bob'/

!include style.puml

box Logic LOGIC_COLOR_T1
participant ":DietLogicManager" as LogicManager LOGIC_COLOR
participant ":FoodBookParser" as FoodBookParser LOGIC_COLOR
participant ":ListCommandParser" as ListCommandParser LOGIC_COLOR
participant "l:ListCommand" as ListCommand LOGIC_COLOR
participant ":CommandResult" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
end box

box Storage STORAGE_COLOR_T1
participant ":FoodBookStorage" as FoodBookStorage STORAGE_COLOR
end box

[-> LogicManager : execute("list -a")
activate LogicManager

LogicManager -> FoodBookParser : parseCommand("list -a")
activate FoodBookParser

create ListCommandParser
FoodBookParser -> ListCommandParser
activate ListCommandParser

ListCommandParser --> FoodBookParser
deactivate ListCommandParser

FoodBookParser -> ListCommandParser : parse("-a")
activate ListCommandParser


create ListCommand
ListCommandParser -> ListCommand
activate ListCommand

ListCommand --> ListCommandParser : l
deactivate ListCommand

ListCommandParser --> FoodBookParser : l
deactivate ListCommandParser
'Hidden arrow to position the destroy marker below the end of the activation bar.
ListCommandParser -[hidden]-> FoodBookParser
destroy ListCommandParser

FoodBookParser --> LogicManager : l
deactivate FoodBookParser

LogicManager -> ListCommand : execute()
activate ListCommand

ListCommand -> Model : updateFilteredFoodList(todayPredicate)
activate Model

Model --> ListCommand
deactivate Model

ListCommand -> Model : listFoods(mode)
activate Model

Model --> ListCommand
deactivate Model

create CommandResult
ListCommand -> CommandResult
activate CommandResult

CommandResult --> ListCommand
deactivate CommandResult

ListCommand --> LogicManager : commandResult
deactivate ListCommand

ListCommand -[hidden]-> LogicManager
destroy ListCommand

LogicManager -> FoodBookStorage : saveFoodBook(foodBook)
activate FoodBookStorage

FoodBookStorage --> LogicManager
deactivate FoodBookStorage

[<--LogicManager
deactivate LogicManager
@enduml
