@startuml
/' @author @jarrod-bob'/

!include style.puml

box Logic LOGIC_COLOR_T1
participant ":DietLogicManager" as LogicManager LOGIC_COLOR
participant ":FoodBookParser" as FoodBookParser LOGIC_COLOR
participant ":BmiCommandParser" as BmiCommandParser LOGIC_COLOR
participant "b:BmiCommand" as BmiCommand LOGIC_COLOR
participant "result:CommandResult" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
end box

[-> LogicManager : execute("bmi -h 172 -w 73")
activate LogicManager

LogicManager -> FoodBookParser : parseCommand("bmi -h 172 -w 73")
activate FoodBookParser

create BmiCommandParser
FoodBookParser -> BmiCommandParser
activate BmiCommandParser

BmiCommandParser --> FoodBookParser
deactivate BmiCommandParser

FoodBookParser -> BmiCommandParser : parse("-h 172 -w 73")
activate BmiCommandParser

ref over FoodBookParser, Model : Create Height and Weight Objects for usage in BmiCommand.

create BmiCommand
BmiCommandParser -> BmiCommand
activate BmiCommand

BmiCommand --> BmiCommandParser : b
deactivate BmiCommand

BmiCommandParser --> FoodBookParser : b
deactivate BmiCommandParser
'Hidden arrow to position the destroy marker below the end of the activation bar.
BmiCommandParser -[hidden]-> FoodBookParser
destroy BmiCommandParser

FoodBookParser --> LogicManager : b
deactivate FoodBookParser

LogicManager -> BmiCommand : execute()
activate BmiCommand

create CommandResult
BmiCommand -> CommandResult
activate CommandResult

CommandResult --> BmiCommand : result
deactivate CommandResult

BmiCommand --> LogicManager : result
deactivate BmiCommand

[<--LogicManager : result
deactivate LogicManager
@enduml
