@startuml
!include style.puml

Actor User as user USER_COLOR
Participant ":EYLAH" as ui UI_COLOR
Participant ":LogicManager" as logic LOGIC_COLOR
Participant ":ModelManager" as splitterModel MODEL_COLOR

user -[USER_COLOR]> ui : "mode -m"
activate ui UI_COLOR

ui -[UI_COLOR]> logic : execute("mode -m")
activate logic LOGIC_COLOR

create "m:Mode" as mode STORAGE_COLOR
logic -[LOGIC_COLOR]> mode : new MODE.Maintain
activate mode STORAGE_COLOR

mode -[STORAGE_COLOR]-> logic
deactivate mode

logic -[LOGIC_COLOR]> splitterModel : setMode(m)
activate splitterModel MODEL_COLOR

splitterModel -[MODEL_COLOR]-> logic
deactivate splitterModel

logic --[LOGIC_COLOR]> ui : CommandResult
deactivate logic

ui--[UI_COLOR]> user : CommandResult
deactivate ui
@enduml
