@startuml
/' @author @akhilvuputuri'/
/' Got inspiration and adapted
from https://github.com/AY1920S2-CS2103T-W12-1/main/blob/master/docs/images/DeliveredClassDiagram.png '/

skinparam backgroundColor #ffffff
skinparam classAttributeIconSize 0
hide circle


class AddCommandParser implements Parser {
    /' Methods '/
    + parse(args : String) : AddCommand
}

interface Parser<T extends Command> {
    parse(userInput : String) : AddCommand
}

abstract class Command<E> {
    {abstract} execute(model : E) : CommandResult
}

class AddCommand extends Command {
    /' Fields '/
    - COMMAND_WORD : String = "add"
    - MESSAGE_USAGE : String
    - MESSAGE_SUCCESS : String
    - MESSAGE_DUPLICATE_FOOD : String
    - toAdd : Food

    /' Methods '/
    + execute(dietModel : DietModel) : CommandResult

}

interface DietModel <<Interface>> {
    - PREDICATE_SHOW_ALL_FOODS : Predicate<Food>

    + hasFood(food : Food) : boolean
    + addFood(food : Food) : void
}

class ParserUtil {
    <u> + parseCalories(calories : String) : Calories
    <u> + parseName(name : String) : Name
    <u> + parseTag(tag : String) : Tag
    <u> + parseTags(tags : Collection<Tag>) : Set<Tag>
}

class DietModelManager implements DietModel {
    /' Fields '/
    - FoodBook : foodBook

    /' Methods '/
    + addFood(food : Food) : void
    + isReceiptDone() : boolean
}

class Food {
    - name : Name
}

class FoodBook {
    /' Fields '/
    - UniqueFoodList : foods

    /' Methods '/
    + addFood(food : Food) : void
}

class Name {
    - name : String
}


AddCommandParser ..> AddCommand
AddCommandParser ..> ParserUtil
AddCommand ..> DietModel
AddCommand --> Food
Food --> Name
DietModelManager *-right->"1" FoodBook

@enduml
