@startuml
!include style.puml

box Model MODEL_COLOR_T1
participant ":ModelManager" as ModelManager MODEL_COLOR
participant ":RecipeBook" as RecipeBook MODEL_COLOR
participant ":UniqueRecipeList" as UniqueRecipeList MODEL_COLOR
participant ":PlannedBook" as PlannedBook MODEL_COLOR
participant ":PlannedRecipeMap" as PlannedRecipeMap MODEL_COLOR
participant ":UniquePlannedList" as UniquePlannedList MODEL_COLOR
participant "newPlan:Plan" as Plan MODEL_COLOR
end box

[-> ModelManager : setRecipe(target, edited)
activate ModelManager

ModelManager -> RecipeBook : setRecipe(target, edited)
activate RecipeBook

RecipeBook -> UniqueRecipeList : setRecipe(target, edited)
activate UniqueRecipeList

UniqueRecipeList --> RecipeBook
deactivate UniqueRecipeList

RecipeBook --> ModelManager
deactivate RecipeBook

ModelManager -> PlannedBook : setRecipe(target, edited)
activate PlannedBook

PlannedBook -> PlannedRecipeMap : getPlans(target)
activate PlannedRecipeMap

PlannedRecipeMap --> PlannedBook
deactivate PlannedRecipeMap

alt oldPlans exist
    loop for all oldPlan that uses target recipe

        PlannedBook -> Plan : setRecipe(edited)
        activate Plan

        Plan --> PlannedBook : newPlan
        deactivate Plan

        PlannedBook -> UniquePlannedList : setPlan(oldPlan, newPlan)
        activate UniquePlannedList

        UniquePlannedList --> PlannedBook
        deactivate UniquePlannedList
    end

    PlannedBook -> PlannedRecipeMap : setRecipe(target, edited, newPlans)
    activate PlannedRecipeMap

    PlannedRecipeMap --> PlannedBook
    deactivate PlannedRecipeMap

end

PlannedBook --> ModelManager
deactivate PlannedBook


[<-- ModelManager
deactivate ModelManager

@enduml
