@startuml
start
:User inputs command;
:Parse command;

if () then ([command arguments is valid])
    :Parse input;
    if () then ([valid user input])
        :Generate new Edit command;
        :Execute Edit command;
        if () then ([Flag is order list])
        :Obtain order to edit;
        :Edit the order of given index;
        else ([Flag is return order list])
        :Obtain return order to edit;
        :Edit the return order of given index;
        endif
    else ([else])
        :Display wrong
        format warning message;
    endif
else ([else])
    : Display unknown
    command message;
endif

stop
@enduml
