@startuml
/' @author @WillySeahh'/
title Activity: List Receipt Command

start
:User enters the list receipt command;

if () then ([no entries in receipt])
    :Inform user that receipt is empty;
else ([else])
    :Displays to user all the entries which
    includes item name, item price and
    persons involved in splitting that item;

endif
stop
@enduml
