@startuml
!include style.puml

Actor User as user USER_COLOR
Participant ":EYLAH" as ui UI_COLOR
Participant ":LogicManager" as logic LOGIC_COLOR
Participant ":ModelManager" as splitterModel MODEL_COLOR
Participant ":Receipt" as receipt MODEL_COLOR
Participant ":Entry" as entry MODEL_COLOR

user -[USER_COLOR]> ui : "listreceipt"
activate ui UI_COLOR

ui -[UI_COLOR]> logic : execute("listreceipt")
activate logic LOGIC_COLOR

logic -[LOGIC_COLOR]> splitterModel : listReceipt()
activate splitterModel MODEL_COLOR

splitterModel -[MODEL_COLOR]> receipt : toString()
activate receipt MODEL_COLOR

receipt -[MODEL_COLOR]> entry : toString()
activate entry MODEL_COLOR

entry --[MODEL_COLOR]> receipt : String
deactivate entry


receipt --[MODEL_COLOR]-> splitterModel : String
deactivate receipt

splitterModel --[LOGIC_COLOR]> logic : CommandResult
deactivate splitterModel

logic --[UI_COLOR]> ui : CommandResult
deactivate logic

ui --[UI_COLOR]> user : CommandResult
deactivate ui

@enduml
