@startuml
/' @author @ailanthustng'/

skinparam backgroundColor #ffffff
skinparam classAttributeIconSize 0
hide circle


abstract class Command<E> {
    {abstract} execute(model : E) : CommandResult
}

class DeleteItemCommandParser implements Parser {
    /' Methods '/
    + parse(args : String) : DeleteItemCommand
}

interface Parser<T extends Command> <<Interface>> {
    parse(userInput : String) : DeleteItemCommand
}

class DeleteItemCommand extends Command {
    /' Fields '/
    - targetIndex : Index

    /' Methods '/
    + execute(splitterModel : SplitterModel) : CommandResult
}

interface SplitterModel <<Interface>> {
    + addEntry(entry : Entry) : void
    + deleteEntry(index : int) : void
    + getEntry(entry : Entry) : Entry
    + paidPerson(person : Person, amountPaid : String) : void
    + listAmount() : String
    + listReceipt() : String
    + getReceipt() : Receipt
    + clearReceipt() : void
    + isReceiptDone() : boolean
    + deleteAllEntries() : void
    + hasPerson(person : Person) : boolean
    + addPerson(person : Person) : void
    + getPerson(person : Person) : Person
    + addAmount(person : Person, amount : Amount) : void
    + removeAmount(person : Person, amount : Amount) : void
    + getReceiptBook() : ReadOnlyReceiptBook
    + updateFilteredPersonList(predicate : Predicate<Person>) : void
    + getFilteredPersonList() : ObservableList<Person>
}

class ParserUtil {
    <u> + parseIndex(oneBasedIndex : String) : Index
    <u> + parseItemName(itemName : String) throws : ItemName
    <u> + parseItemPrice(priceInString : String) : ItemPrice
    <u> + parseAmount(price : ItemPrice , numPersons : int) : Amount
    <u> + parseName(name : String) : Name
    <u> + parseNames(names : Collection<String>) : ArrayList<Name>
    <u> + parsePersons(names : ArrayList<Name>, amount : Amount) : ArrayList<Person>
}

class Index {
    + getZeroBased() : int
    + getOneBased() : int
}

class SplitterModelManager implements SplitterModel {
    /' Fields '/
    - receipt : Receipt

    /' Methods '/
    + deleteEntry(index : int) : void
    + isReceiptDone() : boolean
}

class Receipt {
    /' Fields '/
    - receipt : - ArrayList<Entry>
    - isDone : boolean

    /' Methods '/
    + deleteEntry(entry : Entry) : void
    + isDone() : boolean
}

class Entry {
    /' Fields '/
    - item : Item
    - persons : ArrayList<Person>
}

DeleteItemCommand ..> SplitterModel
DeleteItemCommand *--> Index
DeleteItemCommandParser .left.> Index
DeleteItemCommandParser ..> DeleteItemCommand
DeleteItemCommandParser ..> ParserUtil
SplitterModelManager *-right->"1" Receipt
Receipt .right.> Entry


@enduml
