@startuml
!include style.puml

Actor User as user USER_COLOR
Participant ":EYLAH" as ui UI_COLOR
Participant ":LogicManager" as logic LOGIC_COLOR
Participant ":ModelManager" as splitterModel MODEL_COLOR
Participant ":StorageManager" as splitterStorage STORAGE_COLOR

user -[USER_COLOR]> ui : "additem -i pasta -p 5 -n bob"
activate ui UI_COLOR

ui -[UI_COLOR]> logic : execute("additem -i pasta -p 5 -n bob")
activate logic LOGIC_COLOR

logic -[LOGIC_COLOR]> splitterModel : addEntry(entry)
activate splitterModel MODEL_COLOR

splitterModel -[MODEL_COLOR]-> logic
deactivate splitterModel

alt person does not exist in splitterModel

    logic -[LOGIC_COLOR]> splitterModel : addPerson(person)
    activate splitterModel MODEL_COLOR

    splitterModel -[MODEL_COLOR]-> logic
    deactivate splitterModel

else person already exist in splitterModel

        logic -[LOGIC_COLOR]> splitterModel : addAmount(person, amount)
        activate splitterModel MODEL_COLOR

        splitterModel -[MODEL_COLOR]-> logic
        deactivate splitterModel

end

logic -[LOGIC_COLOR]> splitterStorage : savePersonAmountBook(personAmount)
activate splitterStorage STORAGE_COLOR

splitterStorage -[STORAGE_COLOR]> splitterStorage : Save to file
activate splitterStorage STORAGE_COLOR_T1
deactivate splitterStorage

splitterStorage --[STORAGE_COLOR]> logic
deactivate splitterStorage

logic --[LOGIC_COLOR]> ui : CommandResult
deactivate logic

ui--[UI_COLOR]> user : CommandResult
deactivate ui
@enduml
