@startuml
!include style.puml

Actor User as user USER_COLOR
Participant ":EYLAH" as ui UI_COLOR
Participant ":LogicManager" as logic LOGIC_COLOR
Participant ":ModelManager" as model MODEL_COLOR
Participant ":StorageManager" as storage STORAGE_COLOR

user -[USER_COLOR]> ui : "deleteitem 1"
activate ui UI_COLOR

ui -[UI_COLOR]> logic : execute("deleteitem 1")
activate logic LOGIC_COLOR

logic -[LOGIC_COLOR]> model : deleteEntry(i)
activate model MODEL_COLOR

model -[MODEL_COLOR]-> logic
deactivate model

logic -[LOGIC_COLOR]> storage : savePersonAmountBook(personAmount)
activate storage STORAGE_COLOR

storage -[STORAGE_COLOR]> storage : Save to file
activate storage STORAGE_COLOR_T1
deactivate storage

storage --[STORAGE_COLOR]> logic
deactivate storage

logic --[LOGIC_COLOR]> ui : CommandResult
deactivate logic

ui--[UI_COLOR]> user : CommandResult
deactivate ui
@enduml
