@startuml

title Activity Diagram: Simplified AddItem

start
:AddItem;
note right: This process repeats until the User has finished entering all Items

if () then ([itemAddedCorrectly])

  if () then ([seeReceipt])
    :List Receipt;
  else ([seeAmount])
    :List Amount;
  endif
else ([else])
  :DeleteItem;
endif
stop


@enduml
