@startuml
!include style.puml

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":NormalParser" as NormalParser LOGIC_COLOR
participant ":AddCommandParser" as AddCommandParser LOGIC_COLOR
participant "d:AddAttributeCommand" as AddAttributeCommand LOGIC_COLOR
end box


box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
participant "<<class>>\n:ModelUtil" as ModelUtil UI_COLOR
end box

[-> LogicManager : execute("add attribute leadership")
activate LogicManager

LogicManager -> Model : getAppPhase()
activate Model

Model -> LogicManager : appPhase
deactivate Model

LogicManager -> NormalParser : parseCommand("add attribute leadership")
activate NormalParser

create AddCommandParser
NormalParser -> AddCommandParser
activate AddCommandParser

AddCommandParser --> NormalParser
deactivate AddCommandParser

NormalParser -> AddCommandParser : parse("attribute leadership")
activate AddCommandParser

create AddAttributeCommand
AddCommandParser -> AddAttributeCommand
activate AddAttributeCommand

AddAttributeCommand --> AddCommandParser : d
deactivate AddAttributeCommand

AddCommandParser --> NormalParser : d
deactivate AddCommandParser
'Hidden arrow to position the destroy marker below the end of the activation bar.
AddCommandParser -[hidden]-> NormalParser
destroy AddCommandParser

NormalParser --> LogicManager : d
deactivate NormalParser

LogicManager -> AddAttributeCommand : execute()
activate AddAttributeCommand

AddAttributeCommand -> ModelUtil : validateFinalisation()
activate ModelUtil

ModelUtil --> AddAttributeCommand : throw CommandException("This interview session has been finalized.\nYou can no longer make changes to attributes and questions.")
deactivate ModelUtil
'Hidden arrow to position the destroy marker below the end of the activation bar.
ModelUtil -[hidden]-> AddAttributeCommand
destroy ModelUtil

AddAttributeCommand --> LogicManager : throw CommandException("This interview session has been finalized.\nYou can no longer make changes to attributes and questions.")
deactivate AddAttributeCommand

[<--LogicManager
deactivate LogicManager
@enduml
