@startuml
!include style.puml

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":NormalParser" as NormalParser LOGIC_COLOR
participant ":IntervieweeParser" as IntervieweeParser LOGIC_COLOR
participant ":BestCommandParser" as BestCommandParser LOGIC_COLOR
participant "d:BestCommand" as BestCommand LOGIC_COLOR
participant ":ToggleCommandResult" as ToggleCommandResult LOGIC_COLOR
end box

[-> LogicManager : execute("interviewee -best 5 -a leadership")
activate LogicManager

LogicManager -> NormalParser : parseCommand("interviewee -best 5 -a leadership")
activate NormalParser

create IntervieweeParser
NormalParser -> IntervieweeParser : parse("-best 5 -a leadership")
activate IntervieweeParser

create BestCommandParser
IntervieweeParser -> BestCommandParser : parse("5 -a leadership")
activate BestCommandParser

create BestCommand
BestCommandParser -> BestCommand
activate BestCommand

BestCommand --> BestCommandParser : d
deactivate BestCommand

BestCommandParser --> IntervieweeParser : d
deactivate BestCommandParser
'Hidden arrow to position the destroy marker below the end of the activation bar.
BestCommandParser -[hidden]-> IntervieweeParser
destroy BestCommandParser

IntervieweeParser --> NormalParser : d
deactivate IntervieweeParser
'Hidden arrow to position the destroy marker below the end of the activation bar.
IntervieweeParser -[hidden]-> NormalParser
destroy IntervieweeParser

NormalParser --> LogicManager : d
deactivate NormalParser

LogicManager -> BestCommand : execute()
activate BestCommand

BestCommand -> BestCommand : getBest()
activate BestCommand

BestCommand --> LogicManager : throw CommandException("There is no interviewee that has been interviewed")

deactivate BestCommand

deactivate BestCommand

[<--LogicManager
deactivate LogicManager

@enduml
