@startuml
!include style.puml

box Logic LOGIC_COLOR_T1
    Participant ":GraphCommand" as GraphCommand LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
    Participant ":Model" as Model MODEL_COLOR
    Participant ":Client" as Client MODEL_COLOR
    Participant ":UniqueExerciseList" as UniqueExerciseList MODEL_COLOR
    Participant ":Graph" as Graph MODEL_COLOR
endbox

[-[LOGIC_COLOR]> GraphCommand : execute(model)

activate GraphCommand LOGIC_COLOR

GraphCommand -[LOGIC_COLOR]> Model : hasClientInView()
activate Model MODEL_COLOR
Model --[MODEL_COLOR]> GraphCommand : true
deactivate Model

GraphCommand -[LOGIC_COLOR]> Model : getClientInView()
activate Model MODEL_COLOR
Model --[MODEL_COLOR]> GraphCommand : clientInView
deactivate Model

GraphCommand -[LOGIC_COLOR]> Client : getExerciseList()

activate Client MODEL_COLOR
GraphCommand <[MODEL_COLOR]-- Client : exerciseList
deactivate Client

GraphCommand -[LOGIC_COLOR]> UniqueExerciseList : containsNameWithinDate()
activate UniqueExerciseList MODEL_COLOR
GraphCommand <[MODEL_COLOR]-- UniqueExerciseList : true
deactivate UniqueExerciseList

GraphCommand -[LOGIC_COLOR]> Graph : generateGraphList(clientInView)
activate Graph MODEL_COLOR
GraphCommand <[MODEL_COLOR]-- Graph : graphList
deactivate Graph

deactivate Model

<[LOGIC_COLOR]-- GraphCommand : CommandResult

deactivate GraphCommand

@enduml
