@startuml
/' Sequence Diagram for import feature'/
!include style.puml
box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":DelinoParser" as DelinoParser LOGIC_COLOR
participant ":ImportCommandParser" as ImportCommandParser LOGIC_COLOR
participant ":ParseUtil" as ParseUtil LOGIC_COLOR
participant ":Paths" as Paths LOGIC_COLOR
participant ":CsvProcessor" as CsvProcessor LOGIC_COLOR
participant ":FileUtil" as FileUtil LOGIC_COLOR
participant "importCommand:ImportCommand" as ImportCommand LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
end box

[-> LogicManager : execute("import orders.csv")
activate LogicManager

LogicManager -> DelinoParser ++ : parseCommand("import orders.csv")

create ImportCommandParser
DelinoParser -> ImportCommandParser ++

ImportCommandParser --> DelinoParser --

DelinoParser -> ImportCommandParser ++ : parse("orders.csv")

ImportCommandParser -> ParseUtil ++ : parseCsvFile("orders.csv")

ParseUtil -> Paths ++ : get("data", "orders.csv")

Paths --> ParseUtil -- : csvFilePath

ParseUtil -> CsvProcessor ++ : retrieveData(csvFilePath)

CsvProcessor -> FileUtil ++ : readFromFile(filePath)

FileUtil --> CsvProcessor -- : fileData

CsvProcessor --> ParseUtil -- : fileData

ParseUtil --> ImportCommandParser -- : fileData

create ImportCommand
ImportCommandParser -> ImportCommand ++ : fileData

ImportCommand --> ImportCommandParser -- : importCommand

ImportCommandParser --> DelinoParser -- : importCommand

ImportCommandParser -[hidden]-> DelinoParser
destroy ImportCommandParser

DelinoParser --> LogicManager -- : importCommand

ref over LogicManager,  Model : execute import command

[<--LogicManager : result
deactivate LogicManager
@enduml
