@startuml
!include style.puml

title Sequence Diagram of CalorieTables Initialization

participant ":MainApp" as Main #black
participant ":ModelManager" as Model MODEL_COLOR
participant ":FitHelper" as Fh #red
participant ":CalorieTable" as Table #green
participant ":CalorieEntryUtil" as Data #blue

 -> Main : initModelManager()
activate Main
create Model
Main -> Model
activate Model
create Fh
Model -> Fh
activate Fh
create Table
Fh -> Table
activate Table
Table -> Data : getData()
activate Data
Table <-- Data : data
deactivate
Table -> Table : convertDataToSet()
activate Table
Table --> Table :
deactivate
Fh <-- Table
deactivate
Model <-- Fh
deactivate
Main <-- Model :
deactivate
 <-- Main : model
deactivate Main

@enduml
