@startuml
start
:User enters Insert Command;


If () then ([Command has missing compulsory prefixes])
    :Throws ParseException;

    else ([Command is valid])


    If () then ([Order is duplicate])
    :Throws CommandException;

    else ([Order is unique])
        :Adds Order to OrderBook;
        :Returns Message to user indicating Success;
        :LogicManager prints result to user;
        endif
        endif
stop
@enduml
