@startuml
start
:User inputs List Command;

If () then ([Command is 'list done'])
    :List all completed orders;
    :Returns success message;
else ([Command is not 'list done'])
    If () then ([Command is 'list undone])
        :List all orders that are not completed;
        :Returns success message;
        else ([Command is not 'list undone'])
            If () then ([Command is 'list'])
                :List all orders
                (completed and not completed);
                :Returns success message;
            else ([Command is neither of the three commands])
                :Returns failure message
                (Invalid Command);

        endif
endif
endif
:LogicManager prints message to user;

stop
@enduml
