@startuml

skinparam backgroundColor #ffffff
skinparam classAttributeIconSize 0
hide circle

abstract class "{abstract}\nCommand" {
    + {abstract} execute(model : Model) : CommandResult
}

interface Model <<interface>> {
    + updateFilteredOrderList(Predicate<Order> predicate) : void
    + updateFilteredReturnOrderList(Predicate<ReturnOrder> predicate) : void
}
interface Predicate <<interface>> {
}

class ListCommand implements Model{
    /' Fields '/
    - listArg : String

    /' Methods '/
    + execute(model : Model) : CommandResult
}
ListCommand --up|> "{abstract}\nCommand"
Model ..> Predicate
@enduml
