@startuml
start
:User inputs List Command;

If () then ([Command is 'list done'])
    :UpdateFilteredList with predicate to list all
    delivered orders;
    :Returns Message that indicates successful
     command to list all delivered orders;
else ([Command is not 'list done'])
    If () then ([Command is 'list undone])
        :UpdateFilteredList with predicate to list all
        orders not delivered;
        :Returns Message that indicates successful
        command to list all orders not delivered;
        else ([Command is not 'list undone'])
            If () then ([Command is 'list'])
                :UpdateFilteredList with predicate
                that always result to true (List all orders);
                :Returns Message that indicates successful
                command to list all orders
                (Both delivered and undelivered);
            else ([Command is neither of the three commands])
                :Returns Message that indicates
                 an invalid command;

        endif
endif
endif
:LogicManager prints message to user;

stop
@enduml
