@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor LOGIC_COLOR_T4
skinparam classBackgroundColor LOGIC_COLOR

package Model {}

package Logic as LogicPkg {

    Interface Logic <<Interface>>
    Class LogicManager

'    package Parser as ParserPkg {
'        Class TaTrackerParser
'    }

    package Command as CommandPkg {
        Class CommandResult
        Class "{abstract}\nCommand" as Command

        CommandResult <.left. Command
    }

    Logic .down.> CommandResult

    Logic <|.left. LogicManager

'    LogicManager -up-> "1" TaTrackerParser
    LogicManager .down.> CommandResult
    LogicManager .down.> Command
}

Class HiddenOutside #FFFFFF
'HiddenOutside .[hidden]down.> LogicPkg
HiddenOutside .down.> Logic

LogicManager -right-> Model
Command .right.> Model
@enduml

@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor LOGIC_COLOR_T4
skinparam classBackgroundColor LOGIC_COLOR

package Logic {
    package Parser as ParserPkg {

        Class TaTrackerParser
        Interface Parser <<Interface>>


        package X as ModelParser {
            Class XCommandParser
            Class XYCommandParser

            TaTrackerParser .down.> XCommandParser
            XCommandParser .down.> XYCommandParser
        }

        XYCommandParser .right.|> Parser

        Class Prefix

        Class Prefixes

        Class ArgumentTokenizer
        Class ArgumentMultimap

        Class ParserUtil


        Prefixes -right[hidden]- ParserUtil

        XYCommandParser .down.> ArgumentMultimap
        XYCommandParser .down.> ArgumentTokenizer
        XYCommandParser .down[#Green].> Prefixes
        XYCommandParser .down.> ParserUtil

        ArgumentTokenizer .right.> ArgumentMultimap

        ArgumentTokenizer .down.> Prefix
        ParserUtil .down.> Prefix
        Prefixes .down.> Prefix
    }

    package Command as ModelCommand {
        package X {
            Class XYCommand
        }

        Class CommandResult
        Class "{abstract}\nCommand" as Command

        Command .up.> CommandResult
        XYCommand -up-|> Command

        XYCommand .down[#Red].> Prefixes
    }

    XYCommandParser .right.> XYCommand
}
@enduml

@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor LOGIC_COLOR_T4
skinparam classBackgroundColor LOGIC_COLOR

package Logic {
    package Parser as ParserPkg {

        Class TaTrackerParser
        Interface Parser <<Interface>>


        package X as ModelParser {
            Class XCommandParser

            TaTrackerParser ..down[#Red].> XCommandParser
        }

        XCommandParser .right.|> Parser
    }

    package Command as ModelCommand {
        package X {
            Class XCommand
        }

        Class CommandResult
        Class "{abstract}\nCommand" as Command

        Command .up.> CommandResult
        XCommand -up-|> Command
    }

    XCommandParser .right.> XCommand
}
@enduml