@startuml
!include style.puml

skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

class QuoteBook

Package Quote {
    class UniqueQuoteList
    class Quote
    class Content
}


QuoteBook *-down->"1" UniqueQuoteList
UniqueQuoteList o--> "*" Quote
Quote o--> "1" Content

@enduml