@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

Package Model <<Rectangle>>{
Interface ReadOnlyTaskList <<Interface>>
Interface Model <<Interface>>
Interface ObservableList <<Interface>>
Class TaskList
Class ReadOnlyTaskList
Class ReadOnlyPet
Class ReadOnlyStatistics
Class ReadOnlyPomodoro
Class Model
Class ModelManager
Class UserPrefs
Class ReadOnlyUserPrefs
Class Pet
Class Pomodoro
Class Statistics
Class CustomQueue
Class DayData
Class Date
Class PomDurationData
Class TasksDoneData

Package Task {
Class Task
Class Description
Class Reminder
Class Name
Class Priority
Class UniqueTaskList
}

Package Tag {
Class Tag
}
}

Class HiddenOutside #FFFFFF
HiddenOutside ..> Model

TaskList .up.|> ReadOnlyTaskList

ModelManager .up.|> Model
Model .right.> ObservableList
ModelManager o--> "1" TaskList
ModelManager o-right-> "1" Pet
ModelManager o--> "1" Pomodoro
ModelManager o--> "1" Statistics
ModelManager o-left-> "1" UserPrefs
UserPrefs .up.|> ReadOnlyUserPrefs

Pet ..|> ReadOnlyPet
Pomodoro ..|> ReadOnlyPomodoro
Statistics ..|> ReadOnlyStatistics

Statistics o--> "1" CustomQueue
CustomQueue o--> "7" DayData
DayData *--> Date
DayData *--> PomDurationData
DayData *--> TasksDoneData


TaskList *--> "1" UniqueTaskList
UniqueTaskList o--> "*" Task
Task *--> Name
Task *--> Priority
Task *--> Reminder
Task *--> Description
Task *--> "*" Tag

Name -[hidden]right-> Priority
Priority -[hidden]right-> Description
Description -[hidden]right-> Reminder

ModelManager -->"1" Task : filtered list
@enduml
