@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

Package Model <<Rectangle>> {
    Interface Model <<Interface>>

    Class FitHelper
    Class FitHelperCommit
    Class UserPrefs
    Class UserProfile
    Class VersionedFitHelper
    Class WeightRecords
    Class ModelManager
}

ModelManager .up.|> Model

ModelManager o-left-> "1" UserPrefs
ModelManager o-right-> "1" UserProfile
ModelManager o-down-> "1" WeightRecords
ModelManager o-down-> "1" FitHelper
ModelManager o-down-> "1" VersionedFitHelper
ModelManager o-down-> "1" FitHelperCommit

@enduml
