@startuml
!include style.puml

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":AddressBookParser" as AddressBookParser LOGIC_COLOR
participant "a:AddModuleCommand" as AddModuleCommand LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
participant ":ModuleBook" as ModelBook MODEL_COLOR
end box
[-> LogicManager : execute(moduleAdd)
activate LogicManager

LogicManager -> AddressBookParser : parseCommand(moduleAdd)
activate AddressBookParser

create AddModuleCommand
AddressBookParser -> AddModuleCommand
activate AddModuleCommand

AddModuleCommand --> AddressBookParser
deactivate AddModuleCommand

AddressBookParser --> LogicManager : a
deactivate AddressBookParser

LogicManager -> AddModuleCommand : execute()
activate AddModuleCommand

AddModuleCommand -> Model : hasModule()
activate Model

Model -> ModelBook : hasModule()
activate ModelBook

ModelBook -> Model
deactivate ModelBook

Model --> AddModuleCommand
deactivate Model

AddModuleCommand -> Model : addModule()
activate Model

Model -> ModelBook : addModule()
activate ModelBook

ModelBook -> Model
deactivate ModelBook

Model --> AddModuleCommand
deactivate Model

AddModuleCommand --> LogicManager : result
deactivate AddModuleCommand
AddModuleCommand -[hidden]-> LogicManager : result
destroy AddModuleCommand

[<--LogicManager
deactivate LogicManager
@enduml
