@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor STORAGE_COLOR
skinparam classBackgroundColor STORAGE_COLOR

Class ModuleList

ModuleList .d.> Module
package Module {
Class Module
Class SemesterData
Class AcadYear
Class Preclusion
Class Description
Class Title
Class PreRequisite
Class ModuleCredit
Class ModuleCode

Module *-l> SemesterData
Module *-> AcadYear
Module *--> Preclusion
Module *-d--> Description
Module *-d--> Title
Module *-d--> PreRequisite
Module *-> Personal
Module *--> ModuleCredit
Module *--> ModuleCode

SemesterData -d[hidden]-> AcadYear
AcadYear -d[hidden]-> Preclusion
Preclusion -r[hidden]-> Description
Description -r[hidden]-> Title
Title -r[hidden]-> PreRequisite
PreRequisite -u[hidden]-> ModuleCredit
ModuleCode -d[hidden]-> Personal

package Personal {
class Personal
class Grade
class Status
class TaskList

Personal *-d-> Grade
Personal *-d-> Status
Personal *-d- TaskList
}

}

@enduml