@startuml
start
:User inputs command;
:Parse command;

if () then ([command arguments is valid])
    :Generate new nearby command;
    :Execute nearby command;
    if () then ([Flag given])
        :Obtain all matching nearby orders for specified list;
        :Show all nearby orders for specified list;
    else ([No flags given])
        :Obtain all matching nearby orders for all lists;
        :Show all nearby orders for all lists;
    endif
else ([else])
    :Parse exception generated;
endif

stop
@enduml