@startuml
/' Sequence Diagram for postal sector search '/
!include style.puml
box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":OrderBookParser" as OrderBookParser LOGIC_COLOR
participant ":NearbyCommandParser" as NearbyCommandParser LOGIC_COLOR
participant "n:NearbyCommand" as NearbyCommand LOGIC_COLOR
participant ":NearbyCommandUtil" as NearbyCommandUtil LOGIC_COLOR
participant "result:CommandResult" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
end box

[-> LogicManager : execute("nearby -o 14")
activate LogicManager

LogicManager -> OrderBookParser : parseCommand("nearby -o 14")
activate OrderBookParser

create NearbyCommandParser
OrderBookParser -> NearbyCommandParser
activate NearbyCommandParser

NearbyCommandParser --> OrderBookParser
deactivate NearbyCommandParser

OrderBookParser -> NearbyCommandParser : parse(" -o 14")
activate NearbyCommandParser

create NearbyCommand
NearbyCommandParser -> NearbyCommand
activate NearbyCommand

NearbyCommand --> NearbyCommandParser : n
deactivate NearbyCommand

NearbyCommandParser --> OrderBookParser : n
deactivate NearbyCommandParser
'Hidden arrow to position the destroy marker below the end of the activation bar.
NearbyCommandParser -[hidden]-> OrderBookParser
destroy NearbyCommandParser

OrderBookParser --> LogicManager : n
deactivate OrderBookParser

LogicManager -> NearbyCommand : execute(model)
activate NearbyCommand

NearbyCommand -> NearbyCommand: isPostalSectorSearch()
activate NearbyCommand
NearbyCommand --> NearbyCommand: true
deactivate NearbyCommand

NearbyCommand -> NearbyCommand: getPostalSectorCommandResult(model)
activate NearbyCommand

NearbyCommand -> NearbyCommandUtil: isValidPostalSector(14)
activate NearbyCommandUtil
NearbyCommandUtil --> NearbyCommand: true
deactivate NearbyCommandUtil

NearbyCommand -> NearbyCommand: showPostalSectors(model)
activate NearbyCommand
NearbyCommand -> Model : updateFilteredOrderList(orderPredicate)
activate Model
Model --> NearbyCommand
deactivate Model
NearbyCommand --> NearbyCommand:
deactivate NearbyCommand

create CommandResult
NearbyCommand -> CommandResult
activate CommandResult

CommandResult --> NearbyCommand: result
deactivate CommandResult
NearbyCommand --> NearbyCommand: result
deactivate NearbyCommand
NearbyCommand --> LogicManager : result
deactivate NearbyCommand

[<--LogicManager : result
deactivate LogicManager
@enduml
