@startuml
/' Sequence Diagram for parse exception in Nearby Command '/
!include style.puml
box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":DelinoParser" as DelinoParser LOGIC_COLOR
participant ":NearbyCommandParser" as NearbyCommandParser LOGIC_COLOR
end box


[-> LogicManager : execute("nearby")
activate LogicManager

LogicManager -> DelinoParser : parseCommand("nearby")
activate DelinoParser

create NearbyCommandParser
DelinoParser -> NearbyCommandParser
activate NearbyCommandParser

NearbyCommandParser --> DelinoParser
deactivate NearbyCommandParser

DelinoParser -> NearbyCommandParser : parse("")
activate NearbyCommandParser
return ParseException(MESSAGE_INVALID_COMMAND_FORMAT)

return ParseException(MESSAGE_INVALID_COMMAND_FORMAT)
return ParseException(MESSAGE_INVALID_COMMAND_FORMAT)
@enduml
