@startuml
/' Sequence Diagram for area search '/
!include style.puml
box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":OrderBookParser" as OrderBookParser LOGIC_COLOR
participant ":NearbyCommandParser" as NearbyCommandParser LOGIC_COLOR
participant "n:NearbyCommand" as NearbyCommand LOGIC_COLOR
participant ":DistrictInfo" as DistrictInfo LOGIC_COLOR
participant "result:CommandResult" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
end box

[-> LogicManager : execute("nearby -o central")
activate LogicManager

LogicManager -> OrderBookParser : parseCommand("nearby -o central")
activate OrderBookParser

create NearbyCommandParser
OrderBookParser -> NearbyCommandParser
activate NearbyCommandParser

NearbyCommandParser --> OrderBookParser
deactivate NearbyCommandParser

OrderBookParser -> NearbyCommandParser : parse(" -o central")
activate NearbyCommandParser

create NearbyCommand
NearbyCommandParser -> NearbyCommand
activate NearbyCommand

NearbyCommand --> NearbyCommandParser : n
deactivate NearbyCommand

NearbyCommandParser --> OrderBookParser : n
deactivate NearbyCommandParser
'Hidden arrow to position the destroy marker below the end of the activation bar.
NearbyCommandParser -[hidden]-> OrderBookParser
destroy NearbyCommandParser

OrderBookParser --> LogicManager : n
deactivate OrderBookParser

LogicManager -> NearbyCommand : execute(model)
activate NearbyCommand

NearbyCommand -> DistrictInfo: isValidArea("central")
activate DistrictInfo
DistrictInfo --> NearbyCommand: true
deactivate DistrictInfo

NearbyCommand -> NearbyCommand : getAreaCommandResult(model)
activate NearbyCommand
NearbyCommand -> NearbyCommand : showArea(model)
activate NearbyCommand
NearbyCommand -> Model++ : updateFilteredOrderList(orderPredicate)
Model --> NearbyCommand
deactivate Model
NearbyCommand --> NearbyCommand
deactivate NearbyCommand

create CommandResult
NearbyCommand -> CommandResult
activate CommandResult

CommandResult --> NearbyCommand: result
deactivate CommandResult
NearbyCommand --> NearbyCommand: result
deactivate NearbyCommand

NearbyCommand --> LogicManager : result
deactivate NearbyCommand

[<--LogicManager: result
deactivate LogicManager
@enduml
