@startuml
!include style.puml

box UI UI_COLOR_T1
participant ":CommandBox" as CommandBox UI_COLOR
participant ":MainWindow" as MainWindow UI_COLOR
end box

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":ModdyParser" as ModdyParser LOGIC_COLOR
participant ":NewCommandParser" as NewCommandParser LOGIC_COLOR
participant "n:NewCommand" as NewCommand LOGIC_COLOR
participant ":CommandResult" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
end box

[-> CommandBox : "new n/John c/Computer Science\n y/2.2"
activate CommandBox

CommandBox -> MainWindow : executeCommand("new n/John \nc/Computer Science y/2.2")
activate MainWindow

MainWindow -> LogicManager : execute("new n/John \nc/Computer Science y/2.2")
activate LogicManager

LogicManager -> ModdyParser : parseCommand("new n/John \nc/Computer Science y/2.2")
activate ModdyParser

create NewCommandParser
ModdyParser -> NewCommandParser
activate NewCommandParser

NewCommandParser --> ModdyParser
deactivate NewCommandParser

ModdyParser -> NewCommandParser : parse("n/John \nc/Computer Science y/2.2")
activate NewCommandParser

create NewCommand
NewCommandParser -> NewCommand
activate NewCommand

NewCommand --> NewCommandParser : n
deactivate NewCommand

NewCommandParser --> ModdyParser : n
deactivate NewCommandParser
'Hidden arrow to position the destroy marker below the end of the activation bar.
NewCommandParser -[hidden]-> ModdyParser
destroy NewCommandParser

ModdyParser --> LogicManager : n
deactivate ModdyParser

LogicManager -> NewCommand : execute()
activate NewCommand

NewCommand -> Model : addProfile()
activate Model

Model --> NewCommand
deactivate Model

create CommandResult
NewCommand -> CommandResult
activate CommandResult

CommandResult --> NewCommand
deactivate CommandResult

NewCommand --> LogicManager : result
deactivate NewCommand

LogicManager --> MainWindow
deactivate LogicManager

MainWindow --> CommandBox
deactivate MainWindow

[<--CommandBox
deactivate CommandBox
@enduml
