@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

UniqueOfferList *-right-> "*" Offer

Offer *--> "1" GoodName
Offer *--> "1" Price

@enduml
