@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor LOGIC_COLOR
skinparam classBackgroundColor LOGIC_COLOR

Package Parser <<Rectangle>>{
Class Prefixes
Class Prefix

Package Commons {
    Class HI1 #FFFFFF
}
Package Module {
    Class HI2 #FFFFFF
}
Package Group {
    Class HI3 #FFFFFF
}
Package Student {
    Class HI4 #FFFFFF
}
Package Sort {
    Class HI5 #FFFFFF
}
Package Session {
    Class HI6 #FFFFFF
}
Package Statistic {
    Class HI7 #FFFFFF
}

HI1 .down.> Prefixes
HI2 .down.> Prefixes
HI3 .down.> Prefixes
HI4 .down.> Prefixes
HI5 .down.> Prefixes
HI6 .down.> Prefixes
HI7 .down.> Prefixes

Prefixes .down.> Prefix
@enduml

@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor LOGIC_COLOR
skinparam classBackgroundColor LOGIC_COLOR


Package Parser <<Rectangle>>{
Class PrefixDetails
Class Prefixes
Class PrefixDictionary
Class Prefix

PrefixDictionary -left-> "*" Prefix : parameters
PrefixDictionary -left-> "*" Prefix : optionals
PrefixDictionary .up.> Prefixes
PrefixDictionary -down-> "*" PrefixDetails : prefix details

Prefixes .down.> Prefix
PrefixDetails -up-> "0..1" Prefix
@enduml
