@startuml
!include style.puml

package Model {
    Class Client MODEL_COLOR
    Class PersonalBest MODEL_COLOR
    Class UniqueExerciseList MODEL_COLOR
}

package Logic {
    Class ViewCommand LOGIC_COLOR
    Class AddExerciseCommand LOGIC_COLOR
    Class EditExerciseCommand LOGIC_COLOR
    Class DeleteExerciseCommand LOGIC_COLOR
    Class PersonalBestFinder LOGIC_COLOR
}

Client "1" *-down-> "1" PersonalBest
Client "1" *-up-> "1" UniqueExerciseList

PersonalBestFinder "1" -left-> "1" PersonalBest : sets >
PersonalBestFinder "1" -left-> "1" Client
PersonalBestFinder "1" -left-> "1" UniqueExerciseList

ViewCommand "1" -up[LOGIC_COLOR]-> "1" PersonalBestFinder
AddExerciseCommand "1" -up[LOGIC_COLOR]-> "1" PersonalBestFinder
DeleteExerciseCommand "1" -left[LOGIC_COLOR]-> "1" PersonalBestFinder
EditExerciseCommand "1" -up[LOGIC_COLOR]-> "1" PersonalBestFinder

@enduml
