@startuml
start
:User Executes Randomize Command;

'Since the beta syntax does not support placing the condition outside the
'diamond we place it as the true branch instead.

:Update Canteen List;
:Update Stall List;

if () then ([randomize c/ CANTEEN_NAME])
    :Set Canteens;
    :Get an Option from Chosen Canteen;
    :Add Option for Display;
else ([else])
    if () then ([randomize t/ TAG])
        :Set Canteens;
        :Get an Option by Tag;
        :Add Option for Display;
    else ([else])
        :Get an Option;
        :Add Option for Display;
    endif
endif
stop
@enduml