@startuml
/' Sequence Diagram for postal sector search '/
!include style.puml
box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":OrderBookParser" as OrderBookParser LOGIC_COLOR
participant ":ReturnOrder" as ReturnOrder LOGIC_COLOR
participant ":ReturnCommandParser" as ReturnCommandParser LOGIC_COLOR
participant "n:ReturnCommand" as ReturnCommand LOGIC_COLOR
participant "result:CommandResult" as CommandResult LOGIC_COLOR
participant ":ReturnOrderBook" as ReturnOrderBook LOGIC_COLOR
participant ":OrderBook" as OrderBook LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
participant ":ModelManager" as ModelManager LOGIC_COLOR
end box

[-> LogicManager : execute("return tid/...")
activate LogicManager

LogicManager -> OrderBookParser : parseCommand("return tid/...")
activate OrderBookParser

create ReturnCommandParser
OrderBookParser -> ReturnCommandParser
activate ReturnCommandParser

ReturnCommandParser --> OrderBookParser
deactivate ReturnCommandParser

OrderBookParser -> ReturnCommandParser : parse("tid/...")
activate ReturnCommandParser

create ReturnCommand
ReturnCommandParser -> ReturnCommand
activate ReturnCommand

ReturnCommand --> ReturnCommandParser : n
deactivate ReturnCommand

ReturnCommandParser --> OrderBookParser : n
deactivate ReturnCommandParser

'Hidden arrow to position the destroy marker below the end of the activation bar.
ReturnCommandParser -[hidden]-> OrderBookParser
destroy ReturnCommandParser

OrderBookParser --> LogicManager : n
deactivate OrderBookParser

LogicManager -> ReturnCommand : execute()
activate ReturnCommand

activate ReturnOrder
ReturnCommand -> ReturnOrder
ReturnOrder -> ReturnCommand: hasReturnOrder()
ReturnCommand --> ReturnCommand: false

activate Model
ReturnCommand -> Model: addReturnOrder()
Model --> ModelManager: ReturnOrderBook()
Model --> ModelManager :OrderBook()

ReturnCommand -> Model: updateFilteredOrderList(orderPredicate)


[<--LogicManager
deactivate LogicManager
@enduml
