@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

ScheduleList "1" *--> "*" Schedule

Schedule "1" *--> "1" Day
Schedule "1" *--> "1" StartTime
Schedule "1" *--> "1" EndTime

StartTime --|> Time
EndTime --|> Time
@enduml
