@startuml
/' Sequence Diagram for postal sector search '/
!include style.puml
box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":DelinoParser" as DelinoParser LOGIC_COLOR
participant ":SearchCommandParser" as SearchCommandParser LOGIC_COLOR
participant "orderPred:OrderContainsKeywordsPredicate" as OrderContainsKeywordsPredicate LOGIC_COLOR
participant "returnPred:ReturnOrderContiansKeywordsPredicate" as ReturnOrderContiansKeywordsPredicate LOGIC_COLOR
participant "s:SearchCommand" as SearchCommand LOGIC_COLOR
participant "result:CommandResult" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
end box

[-> LogicManager : execute("search Alice")
activate LogicManager

LogicManager -> DelinoParser : parseCommand("search Alice")
activate DelinoParser

create SearchCommandParser
DelinoParser -> SearchCommandParser
activate SearchCommandParser

SearchCommandParser --> DelinoParser
deactivate SearchCommandParser

DelinoParser -> SearchCommandParser : parse("Alice")
activate SearchCommandParser

create OrderContainsKeywordsPredicate
SearchCommandParser -> OrderContainsKeywordsPredicate
activate OrderContainsKeywordsPredicate

OrderContainsKeywordsPredicate --> SearchCommandParser : orderPred
deactivate OrderContainsKeywordsPredicate

create ReturnOrderContiansKeywordsPredicate
SearchCommandParser -> ReturnOrderContiansKeywordsPredicate
activate ReturnOrderContiansKeywordsPredicate

ReturnOrderContiansKeywordsPredicate --> SearchCommandParser : returnPred
deactivate ReturnOrderContiansKeywordsPredicate

create SearchCommand
SearchCommandParser -> SearchCommand
activate SearchCommand

SearchCommand --> SearchCommandParser : s
deactivate SearchCommand

SearchCommandParser --> DelinoParser : s
deactivate SearchCommandParser
SearchCommandParser -[hidden]-> DelinoParser
destroy SearchCommandParser

DelinoParser --> LogicManager : s
deactivate DelinoParser

LogicManager -> SearchCommand : execute(model)
activate SearchCommand


SearchCommand -> Model : updateFilteredOrderList(orderPred)
activate Model

Model --> SearchCommand
deactivate Model
SearchCommand -> Model : updateFilteredReturnOrderList(returnPred)
activate Model

Model --> SearchCommand
deactivate Model


create CommandResult
SearchCommand -> CommandResult
activate CommandResult

CommandResult --> SearchCommand
deactivate CommandResult

SearchCommand --> LogicManager : result
deactivate SearchCommand

[<--LogicManager
deactivate LogicManager
@enduml
