@startuml
/' Sequence Diagram for insert '/
!include style.puml
box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":DelinoParser" as DelinoParser LOGIC_COLOR
participant "command:ShowCommand" as ShowCommand LOGIC_COLOR
participant "commandResult:CommandResult" as CommandResult LOGIC_COLOR
end box

create LogicManager
[-> LogicManager : execute("show all")
activate LogicManager

LogicManager ->DelinoParser : parseCommand()
activate DelinoParser

create ShowCommand

DelinoParser -> ShowCommand ++ : arguments

ShowCommand -> ShowCommand ++ : parseData()
ShowCommand -> ShowCommand -- :

ShowCommand --> DelinoParser -- : showCommand

DelinoParser --> LogicManager : showCommand

deactivate DelinoParser

LogicManager -> ShowCommand ++ : execute(model)

create CommandResult
ShowCommand -> CommandResult ++ : MESSAGE_TODAY
activate CommandResult
CommandResult --> ShowCommand -- : commandResult
deactivate CommandResult

ShowCommand --> LogicManager -- : commandResult


deactivate ShowCommand

ref over LogicManager, CommandResult : Execution of the Show Command Sequence Diagram
[<--LogicManager
deactivate LogicManager
@enduml
