@startuml
!include style.puml

box UI UI_COLOR_T1
participant ":CommandBox" as CommandBox UI_COLOR
participant ":MainWindow" as MainWindow UI_COLOR
end box

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":ModdyParser" as ModdyParser LOGIC_COLOR
participant ":ShowCommandParser" as ShowCommandParser LOGIC_COLOR
participant "s:ShowCommand" as ShowCommand LOGIC_COLOR
participant ":CommandResult" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
participant "Profile" as Profile MODEL_COLOR

end box

[-> CommandBox : "show n/John"
activate CommandBox

CommandBox --> MainWindow : executeCommand("show n/John")
activate MainWindow

MainWindow -> LogicManager : execute("show n/John")
activate LogicManager

LogicManager -> ModdyParser : parseCommand("show n/John")
activate ModdyParser

create ShowCommandParser
ModdyParser -> ShowCommandParser : parse("n/John")
activate ShowCommandParser

ShowCommandParser --> ModdyParser
deactivate ShowCommandParser

ModdyParser --> ShowCommandParser : parse("n/John")
activate ShowCommandParser

create ShowCommand
ShowCommandParser --> ShowCommand
activate ShowCommand

ShowCommand --> ShowCommandParser : s
deactivate ShowCommand

ShowCommandParser --> ModdyParser : s
destroy ShowCommandParser

ModdyParser --> LogicManager : s
deactivate ModdyParser


LogicManager --> ShowCommand : execute()
activate ShowCommand

ShowCommand --> Model : getFirstProfile()
activate Model

Model --> Profile
activate Profile

Profile --> Model
deactivate Profile

Model --> ShowCommand
deactivate Model


ShowCommand --> Profile : setDisplayedView()
activate Profile

Profile --> ShowCommand
deactivate Profile

create CommandResult
ShowCommand -> CommandResult
activate CommandResult

CommandResult --> ShowCommand
deactivate CommandResult

ShowCommand --> LogicManager : result
deactivate ShowCommand

LogicManager --> MainWindow : getDisplayedView()
deactivate LogicManager

MainWindow --> CommandBox

[<-- CommandBox
deactivate LogicManager
@enduml
