@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor LOGIC_COLOR
skinparam classBackgroundColor LOGIC_COLOR

package Logic {
Class "{abstract}\nCommand" as Command
Class StatementCommand
}

package Model {
Class ModelManager MODEL_COLOR
}

StatementCommand .up.|> Command
Command .right.> ModelManager
@enduml
