@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor STORAGE_COLOR
skinparam classBackgroundColor STORAGE_COLOR

Interface Storage <<Interface>>
Interface UserPrefsStorage <<Interface>>
Interface FoodieBotStorage <<Interface>>

Class StorageManager
Class JsonUserPrefsStorage
Class JsonFoodieBotStorage

StorageManager .left.|> Storage
StorageManager o-right-> UserPrefsStorage
StorageManager o--> FoodieBotStorage

JsonUserPrefsStorage .left.|> UserPrefsStorage
JsonFoodieBotStorage .left.|> FoodieBotStorage
JsonFoodieBotStorage .down.> JsonSerializableFoodieBotStorage
JsonSerializableFoodieBotStorage .right.> JsonSerializableCanteen
JsonSerializableCanteen .right.> JsonAdaptedTag
@enduml
