@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor STORAGE_COLOR
skinparam classBackgroundColor STORAGE_COLOR

Interface Storage <<Interface>>
Interface FitHelperStorage <<Interface>>

Class StorageManager
Class JsonFitHelperStorage

StorageManager .left.|> Storage
StorageManager o--> FitHelperStorage

JsonFitHelperStorage .left.|> FitHelperStorage
JsonFitHelperStorage .down.> JsonSerializableFitHelperStorage
JsonSerializableFitHelperStorage .right.> JsonSerializableEntry
@enduml
