@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor STORAGE_COLOR
skinparam classBackgroundColor STORAGE_COLOR

Interface Storage <<Interface>>
Interface UserPrefsStorage <<Interface>>
Interface OrderBookStorage <<Interface>>
Interface ReturnOrderBookStorage <<Interface>>

Class StorageManager
Class JsonUserPrefsStorage
Class JsonOrderBookStorage
Class JsonReturnOrderBookStorage
Class JsonSerializableOrderBookStorage
Class JsonSerializableReturnOrderBookStorage
Class JsonAdaptedOrder

StorageManager .left.|> Storage
StorageManager o-up-> UserPrefsStorage
StorageManager o--> OrderBookStorage
StorageManager o--> ReturnOrderBookStorage

JsonUserPrefsStorage .left.|> UserPrefsStorage
JsonOrderBookStorage .left.|> OrderBookStorage
OrderBookStorage .left[hidden].> ReturnOrderBookStorage
JsonReturnOrderBookStorage .right.|> ReturnOrderBookStorage
JsonOrderBookStorage .down.> JsonSerializableOrderBookStorage
JsonReturnOrderBookStorage .down.> JsonSerializableReturnOrderBookStorage
JsonSerializableOrderBookStorage .down.> JsonAdaptedOrder
JsonSerializableReturnOrderBookStorage .down.> JsonAdaptedReturnOrder
@enduml
