@startuml
!include style.puml

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":SuggestionEngine" as SuggestionEngine LOGIC_COLOR
participant ":StringCorrectionEngine" as StringCorrectionEngine LOGIC_COLOR
participant ":AbsolutePathCorrectionEngine" as AbsolutePathCorrectionEngine LOGIC_COLOR
participant ":OpenSuggestionArgHandler" as OpenSuggestionArgHandler LOGIC_COLOR
participant "o:OpenSuggestionGenerator" as OpenSuggestionGenerator LOGIC_COLOR
participant ":SuggestionItemImpl" as SuggestionItemImpl LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
end box

[-> LogicManager
activate LogicManager

create SuggestionEngine
LogicManager -> SuggestionEngine
activate SuggestionEngine

create StringCorrectionEngine
SuggestionEngine -> StringCorrectionEngine
activate StringCorrectionEngine

StringCorrectionEngine --> SuggestionEngine
deactivate StringCorrectionEngine

create AbsolutePathCorrectionEngine
SuggestionEngine -> AbsolutePathCorrectionEngine
activate AbsolutePathCorrectionEngine

AbsolutePathCorrectionEngine --> SuggestionEngine
deactivate AbsolutePathCorrectionEngine

SuggestionEngine -> SuggestionEngine : autoUpdateInput("opne /a")
activate SuggestionEngine

SuggestionEngine -> Model : clearSuggestions()
activate Model

Model --> SuggestionEngine
deactivate Model

SuggestionEngine -> Model : clearResponseText()
activate Model

Model --> SuggestionEngine
deactivate Model

SuggestionEngine -> SuggestionEngine : suggest("opne /a")
activate SuggestionEngine

SuggestionEngine -> SuggestionEngine : parseCommand("opne /a");
activate SuggestionEngine

SuggestionEngine -> StringCorrectionEngine : correct("opne")
activate StringCorrectionEngine

StringCorrectionEngine --> SuggestionEngine : correctionResult
deactivate StringCorrectionEngine

create OpenSuggestionArgHandler
SuggestionEngine -> OpenSuggestionArgHandler
activate OpenSuggestionArgHandler

OpenSuggestionArgHandler --> SuggestionEngine
deactivate OpenSuggestionArgHandler

SuggestionEngine -> OpenSuggestionArgHandler : handleArg(" /a")
activate OpenSuggestionArgHandler

OpenSuggestionArgHandler -> Model : setResponseText("Open a note titled "a"")
activate Model

Model --> OpenSuggestionArgHandler
deactivate Model

OpenSuggestionArgHandler -> AbsolutePathCorrectionEngine : correct(" /a")
activate AbsolutePathCorrectionEngine

AbsolutePathCorrectionEngine --> OpenSuggestionArgHandler : correctionResult
deactivate AbsolutePathCorrectionEngine

create OpenSuggestionGenerator
OpenSuggestionArgHandler -> OpenSuggestionGenerator
activate OpenSuggestionGenerator

OpenSuggestionGenerator --> OpenSuggestionArgHandler : o
deactivate OpenSuggestionGenerator

OpenSuggestionArgHandler --> SuggestionEngine : o
deactivate OpenSuggestionArgHandler
'Hidden arrow to position the destroy marker below the end of the activation bar.
OpenSuggestionArgHandler -[hidden]-> SuggestionEngine
destroy OpenSuggestionArgHandler

SuggestionEngine --> SuggestionEngine
deactivate SuggestionEngine

SuggestionEngine -> OpenSuggestionGenerator : execute(model)
activate OpenSuggestionGenerator

OpenSuggestionGenerator -> OpenSuggestionGenerator : getPossiblePaths\n(correctionResult.getCorrectedItems(), model)
activate OpenSuggestionGenerator

OpenSuggestionGenerator --> OpenSuggestionGenerator : possiblePaths
deactivate OpenSuggestionGenerator

OpenSuggestionGenerator -> OpenSuggestionGenerator : getSuggestions(possiblePaths, model)
activate OpenSuggestionGenerator

create SuggestionItemImpl
OpenSuggestionGenerator -> SuggestionItemImpl
activate SuggestionItemImpl

SuggestionItemImpl --> OpenSuggestionGenerator : item
deactivate SuggestionItemImpl

OpenSuggestionGenerator --> OpenSuggestionGenerator : suggestions
deactivate OpenSuggestionGenerator

OpenSuggestionGenerator -> Model : setSuggestions(suggestions)
activate Model

Model --> OpenSuggestionGenerator
deactivate Model

OpenSuggestionGenerator --> SuggestionEngine
deactivate OpenSuggestionGenerator

SuggestionEngine --> SuggestionEngine
deactivate SuggestionEngine

SuggestionEngine --> SuggestionEngine
deactivate SuggestionEngine

SuggestionEngine --> LogicManager
deactivate SuggestionEngine

[<--LogicManager
deactivate LogicManager
@enduml
