@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor LOGIC_COLOR_T4
skinparam classBackgroundColor LOGIC_COLOR

package Logic {

package SuggestionEngine {
Class SuggestionEngine
}

package Handler {
Interface SuggestionArgHandler <<Interface>>
Class XYZSuggestionArgHandler
}

package SuggestionGenerator {
Interface SuggestionGenerator <<Interface>>
Class XYZSuggestionGenerator
}

package SuggestionItem {
Interface SuggestionItem <<interface>>
Class SuggestionItemImpl
}

Interface Logic <<Interface>>
Class LogicManager
}

package Model{
Class HiddenModel #FFFFFF
}

Class HiddenOutside #FFFFFF
HiddenOutside ..> Logic



LogicManager .up.|> Logic
LogicManager -down->"1" SuggestionEngine
SuggestionEngine .right.> XYZSuggestionArgHandler: creates >

XYZSuggestionArgHandler .up.> XYZSuggestionGenerator : creates >
XYZSuggestionArgHandler .down.|> SuggestionArgHandler

XYZSuggestionGenerator .up.|> SuggestionGenerator
LogicManager .right.> SuggestionGenerator : executes >
XYZSuggestionGenerator .right.> SuggestionItemImpl : creates >

LogicManager --> Model
SuggestionGenerator ..> Model
note bottom of XYZSuggestionGenerator: XYZSuggestionGenerator = OpenSuggestionGenerator, \nNewSuggestionGenerator, etc

SuggestionItemImpl .up.|> SuggestionItem
@enduml
