@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

package Supplier {
    class UniqueSupplierList
    class Supplier
    class Name
    class Phone
    class Email
    class Address
}

package Offer {
    class Offer
    class Price
}

package Good {
    class GoodName
}

AddressBook *-right- "1" UniqueSupplierList

UniqueSupplierList o-right- "*" Supplier

Supplier *-- "*" Offer
Supplier *--"1" Name
Supplier *--"1" Phone
Supplier *--"1" Email
Supplier *--"1" Address

Offer *-- "1" GoodName
Offer *-- "1" Price

@enduml
