@startuml
start

:Create input buffer;
:Input character;

while () is ([else])

    :Read input to buffer;
    :Check command in buffer;

    if () then ([no command word])
    else ([has command word])
        :Highlight command word;
        :Check all command prefixes;

        while () is ([has prefix])
            :Check prefix;

            if () then ([valid prefix])
                :Highlight prefix;
                :Check prefix value;

                if () then ([valid value])
                    :Highlight value;

                else ([invalid value])
                endif

            else ([invalid prefix])
            endif

        endwhile ([no more prefixes])
    endif

    :Input character;

endwhile ([enter key pressed])

stop
@enduml
