@startuml
!include style.puml
package Model {

skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

Package Model <<Rectangle>> {
package TSS {
class TSS
class TotalEarnings
class TotalHours
class Rate
}
}

Class HiddenOutside #FFFFFF

TaTracker *--> "1" TSS
TSS *-->"1" TotalEarnings
TSS *-->"1" TotalHours
TSS *-->"1" Rate

@enduml
