@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor UI_COLOR_T4
skinparam classBackgroundColor UI_COLOR

package UI <<Rectangle>>{
Interface Ui <<Interface>>
Class "{abstract}\nUiPart" as UiPart
Class UiManager
Class MainWindow
Class CommandBox
Class ResultDisplay
Class Pages
}

package Model <<Rectangle>> {
Class HiddenModel #FFFFFF
}

package Logic <<Rectangle>> {
Class HiddenLogic #FFFFFF
}

note "XYZCard & Pages refer to the\nindividual components of FitHelper GUI." as N1
note "Pages represents a several GUI page classes\n located at the `PagePane` placeholder in MainWindow.\nIt includes DashBoard, TodayPage, CalendarPage,\n ProfilePage, DiaryPage,WeightPage, and HelpPage,\n which can be switched." as N2
note "XYZCard corresponds to the GUI elements in Pages,\nincluding FoodCard, SportCard, DiaryCard,\nReminderCard, DayCard, and EventCard." as N3
Class HiddenOutside #FFFFFF
HiddenOutside ..> Ui

UiManager .left.|> Ui
UiManager -down-> MainWindow

MainWindow *-down-> CommandBox
MainWindow *-down-> ResultDisplay
MainWindow *-down-> Pages

Pages -down-> XYZCard

MainWindow -left-|> UiPart

ResultDisplay --|> UiPart
CommandBox --|> UiPart
Pages --|> UiPart
XYZCard --|> UiPart

XYZCard ..> Model
UiManager -right-> Logic
MainWindow -left-> Logic

CommandBox -[hidden]left- ResultDisplay

Pages .. N1
XYZCard .. N1
Pages .. N2
XYZCard .. N3
MainWindow -[hidden]-|> UiPart
@enduml
