@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor UI_COLOR_T4
skinparam classBackgroundColor UI_COLOR

package VIEW <<Rectangle>>{
Interface View <<Interface>>
Class "{abstract}\nViewPart" as ViewPart
Class ViewManager
Class MainWindow
Class SuggestionsList
Class HelpModal
Class SideBarTree
Class CommandBox
Class BlockContent
}

package Model <<Rectangle>> {
Class HiddenModel #FFFFFF
}

package Logic <<Rectangle>> {
Class HiddenLogic #FFFFFF
}

Class HiddenOutside #FFFFFF
HiddenOutside ..> View

ViewManager .left.|> View
ViewManager -down-> MainWindow
MainWindow *-down-> SuggestionsList
MainWindow *-down-> CommandBox
MainWindow *-down-> HelpModal
MainWindow *-down-> SideBarTree
MainWindow *-down-> BlockContent

MainWindow ----|> ViewPart

HelpModal --|> ViewPart
CommandBox --|> ViewPart
SideBarTree --|> ViewPart
SuggestionsList -down-|> ViewPart
BlockContent --|> ViewPart

SideBarTree .left...> Model
BlockContent .down..> Model
SuggestionsList ....> Model
ViewManager -right-> Logic
MainWindow -left-> Logic
MainWindow -left-> Model

SideBarTree -[hidden]left- SuggestionsList
SuggestionsList -[hidden]left- CommandBox
CommandBox -[hidden]left- HelpModal
BlockContent -[hidden]left-SideBarTree

MainWindow -[hidden]-|> ViewPart
@enduml
