@startuml
!include style.puml
show members
hide empty members

skinparam ClassFontColor #000000
skinparam ClassBorderColor #000000

title After "sell g/banana q/1 p/5" command

package LinearHistory<Inventory> {
    package History {
        object "__saved3:Inventory__" as State3
        State3 : goods = {"apple 1", "banana 1"}

        object "__saved1:Inventory__" as State1
        State1 : goods = {"apple 1", "banana 2"}

        object "__saved0:Inventory__" as State0
        State0 : goods = {"apple 1", "banana 2", "citrus 3"}
    }

    object "__currentState:Inventory__" as curr
    curr : goods = {"apple 1", "banana 1"}

    class "statePointer" as StatePointer #FFFFFF
    State3 <-- StatePointer
    note right on link: State saved2 deleted.
}

@end
