@startuml
!include style.puml
show members
hide empty members

skinparam ClassFontColor #000000
skinparam ClassBorderColor #000000

title Initial state

package LinearHistory<Inventory> {
    package History {
        object "__saved0:Inventory__" as State0
        State0 : goods = {"apple 1", "banana 2", "citrus 3"}
    }

    object "__currentState:Inventory__" as curr
    curr : goods = {"apple 1", "banana 2", "citrus 3"}

    class "statePointer" as StatePointer #FFFFFF
    State0 <-- StatePointer
}

@end
