@startuml
!include style.puml

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":InventoryManagerParser" as InventoryManagerParser LOGIC_COLOR
participant "u:UndoCommand" as UndoCommand LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
participant ":VersionedInventory" as VersionedInventory MODEL_COLOR
end box
[-> LogicManager : execute(undo)
activate LogicManager

LogicManager -> InventoryManagerParser : parseCommand(undo)
activate InventoryManagerParser

create UndoCommand
InventoryManagerParser -> UndoCommand
activate UndoCommand

UndoCommand --> InventoryManagerParser
deactivate UndoCommand

InventoryManagerParser --> LogicManager : u
deactivate InventoryManagerParser

LogicManager -> UndoCommand : execute()
activate UndoCommand

UndoCommand -> Model : undo()
activate Model

Model -> VersionedInventory : undo()
activate VersionedInventory

VersionedInventory --> Model :
deactivate VersionedInventory

Model --> UndoCommand
deactivate Model

UndoCommand --> LogicManager : result
deactivate UndoCommand
UndoCommand -[hidden]-> LogicManager : result
destroy UndoCommand

[<--LogicManager
deactivate LogicManager
@enduml
