@startuml
!include style.puml

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":FitHelperParser" as FitHelperParser LOGIC_COLOR
participant "u:UndoCommand" as UndoCommand LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
participant ":VersionedFitHelper" as VersionedFitHelper MODEL_COLOR
end box
[-> LogicManager : execute(undo)
activate LogicManager

LogicManager -> FitHelperParser : parseCommand(undo)
activate FitHelperParser

create UndoCommand
FitHelperParser -> UndoCommand
activate UndoCommand

UndoCommand --> FitHelperParser
deactivate UndoCommand

FitHelperParser --> LogicManager : u
deactivate FitHelperParser

LogicManager -> UndoCommand : execute()
activate UndoCommand

UndoCommand -> Model : undoFitHelper()
activate Model

Model -> VersionedFitHelper : undo()
activate VersionedFitHelper

VersionedFitHelper -> VersionedFitHelper :resetData(ReadOnlyFitHelper)
VersionedFitHelper --> Model :
deactivate VersionedFitHelper

Model --> UndoCommand
deactivate Model

UndoCommand --> LogicManager : result
deactivate UndoCommand
UndoCommand -[hidden]-> LogicManager : result
destroy UndoCommand

[<--LogicManager
deactivate LogicManager
@enduml
