@startuml
!include style.puml
show members
hide empty members

skinparam ClassFontColor #000000
skinparam ClassBorderColor #000000

title After "list-g" command

package LinearHistory {
    package History {
        object "__saved2:Inventory__" as State2
        State2 : goods = {"apple 6", "banana 2"}

        object "__saved1:Inventory__" as State1
        State1 : goods = {"apple 1", "banana 2"}

        object "__saved0:Inventory__" as State0
        State0 : goods = {"apple 1", "banana 2", "citrus 3"}
    }

    object "__currentState:Inventory__" as curr
    curr : goods = {"apple 1", "banana 2"}

    class "statePointer" as StatePointer #FFFFFF
    State1 <-- StatePointer
}

@end
