@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR
skinparam classAttributeIconSize 0
skinparam classAttributeFontColor #FFFFFF

Interface ReadOnlyUserPrefs <<Interface>>
Class UserPrefs
Class GuiSettings
Class Path

UserPrefs *-down-> "1" GuiSettings
UserPrefs *-down-> "3" Path
UserPrefs .up.|> ReadOnlyUserPrefs

@enduml
