@startuml
!include style.puml

start
:User inputs view command;

:Parser parses input;

If () then ([Recipe index exists])
    :Updates the GUI to display the recipe at specified index;
    :Returns success message;
else ([Recipe index does not exist])
    :Returns failure message
    (Invalid index);
endif
:LogicManager prints message to user;

stop
@enduml
