@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor WORKOUT_MANAGER_COLOR
skinparam classBackgroundColor WORKOUT_MANAGER_COLOR_T1

Package WorkoutManager <<Rectangle>> {
Class WorkoutManager
Class WorkoutList
Class FilteredWorkoutList
Class Workout

Class WorkoutName
Class WorkoutId
Class WorkoutExerciseList
}

WorkoutManager *-right-> "1" WorkoutList
WorkoutList *-right-> "1" FilteredWorkoutList
WorkoutList *-down-> "*" Workout

Workout *-down-> WorkoutId
Workout *-down-> WorkoutName
Workout *-down-> WorkoutExerciseList
@enduml
