@startuml

class WorkoutSession extends ReadOnlyWorkoutSession {
    -startTime: LocalDateTime
    -endTime: LocalDateTime
    -workout: Workout
    -exerciseResults: List<ExerciseResult>


    +Workout getWorkout()
    +void setWorkout(Workout workout)
    +WorkoutResult getWorkoutResult()
    +void addWorkoutResult(WorkoutResult workoutResult)
    +LocalDateTime getStartTime()
    +void setStartTime()
    +LocalDateTime getEndTime()
    +void setEndTime()
}


interface ReadOnlyWorkoutSession {
    +Workout getWorkout()
    +WorkoutResult getWorkoutResult()
    +LocalDateTime getStartTime()
    +LocalDateTime getEndTime()
}

class ExerciseResult {
    -status: ExerciseStatus
    -setResults: List<SetResult>
    +ExerciseStatus getExerciseStatus()
    +void setExerciseStatus()
}

class SetResult {
    -setStatus: SetStatus
    -timing: Integer
    +void updateStatus()
    +void getStatus()
    +Integer getTiming()
    +void setTiming();
}

enum ExerciseStatus {
    HAVENT_STARTED
    IN_PROGRESS
    FINISHED
}

enum SetStatus {
    HAVENT_STARTED
    IN_PROGRESS
    SKIPPED
    FINISHED
}

ExerciseStatus --- ExerciseResult
SetResult --- SetStatus

WorkoutSession "1" *-- "many" ExerciseResult : contains
ExerciseResult "1" *-- "many" SetResult : contains
@enduml
