@startuml

' start
' :View list of exercises;
' :Find exercise;

' if (Desired exercise found?) then ([yes])

' else ([no])
'     repeat :Create new exercise;
'     repeat while (More exercises to create?)
' endif

' repeat :Add exercise to workout;
' repeat while (More exercises to add?)
' stop

start
:Create an empty workout with a name;
:View list of exercises;
:Find exercises to add;

if (Desired exercise found?) then ([yes])
else ([no])
    :Create new exercise;
endif
:Add new exercise to workout;
stop

@enduml
