package fithelper.model.calorietable;

/**
 * Data about calorie consumption of a sports in primitive form.
 */
public class SportsCalorieDataUtil {
    public static final String DATA = "Cycling (<22.5 kmph)\t563\n"
            + "Cycling (22.5-26 kmph)\t704\n"
            + "Weightlifting (light)\t211\n"
            + "Weightlifting (vigorous)\t387\n"
            + "Cycling (>26 kmph)\t844\n"
            + "Rowing machine (light)\t246\n"
            + "Rowing machine (moderate)\t493\n"
            + "Rowing machine (vigorous)\t600\n"
            + "Aerobics (low impact)\t352\n"
            + "Aerobics (high impact)\t493\n"
            + "Aerobics (step aerobics)\t598\n"
            + "Stretching (mild)\t176\n"
            + "Stretching (intense)\t281\n"
            + "Running (8-11 kmph)\t563 - 800\n"
            + "Running (12-14 kmph)\t880 - 985\n"
            + "Running (14.5-17.5 kmph)\t1056 - 1267\n"
            + "Cross country\t633\n"
            + "Stairclimbing\t1056\n"
            + "Track and field (shot, discus)\t281\n"
            + "Track and field (high jump, pole vault)\t422\n"
            + "Track and field (hurdles)\t704\n"
            + "Archery\t246\n"
            + "Badminton\t317\n"
            + "Basketball (competitive)\t563\n"
            + "Basketball (shooting baskets)\t317\n"
            + "Bowling\t211\n"
            + "Boxing (in ring)\t844\n"
            + "Boxing (punching bag)\t422\n"
            + "Boxing (sparring)\t633\n"
            + "Croquet\t176\n"
            + "Curling\t281\n"
            + "Fencing\t422\n"
            + "Football (competitive)\t633\n"
            + "Frisbee (competitive)\t563\n"
            + "Frisbbee (playing)\t211\n"
            + "Gymnastics\t281\n"
            + "Handball\t844\n"
            + "Hockey (field hockey)\t563\n"
            + "Hockey (ice hockey)\t563\n"
            + "Martial arts\t704\n"
            + "Juggling\t281\n"
            + "Kickball\t493\n"
            + "Lacrosse\t563\n"
            + "Paddleball (competitive)\t704\n"
            + "Paddleball (playing)\t422\n"
            + "Racquetbal (competitive)\t704\n"
            + "Racquetbal (playing)\t493\n"
            + "Rock climbing (ascending)\t774\n"
            + "Rock climbing (rappelling)\t563\n"
            + "Jumping rope (fast)\t844\n"
            + "Jumping rope (moderate)\t704\n"
            + "Jumping rope (slow)\t563\n"
            + "Rugby\t704\n"
            + "Shuffleboard, lawn bowling)\t211\n"
            + "Skateboarding\t352\n"
            + "Roller skating\t493\n"
            + "Sky diving\t211\n"
            + "Soccer (competitive)\t704\n"
            + "Soccer (playing)\t493\n"
            + "Softball or baseball\t352\n"
            + "Squash\t844\n"
            + "Table tennis, ping pong)\t281\n"
            + "Tai chi\t281\n"
            + "Tennis\t493\n"
            + "Volleyball (competitive)\t563\n"
            + "Volleyball (playing)\t211\n"
            + "Wrestling\t422\n"
            + "Wallyball\t493\n"
            + "Backpacking, Hiking with pack\t493\n"
            + "Canoeing (light)\t211\n"
            + "Canoeing (moderate)\t493\n"
            + "Canoeing (vigorous)\t844\n"
            + "Swimming backstroke\t493\n"
            + "Swimming breaststroke\t704\n"
            + "Swimming butterfly\t744\n"
            + "Swimming sidestroke\t563\n"
            + "Swimming leisurely, not laps\t422\n"
            + "Water polo\t704\n"
            + "Water volleyball\t211\n"
            + "Water jogging\t563\n"
            + "Walk (2-4 kmph)\t100 - 211\n"
            + "Walk (5-6.5 kmph)\t232 - 352\n"
            + "Walk (7-8 kmph)\t443 - 563\n"
            + "Race walking\t457\n";
}
