= Aaron Choo - Project Portfolio
:site-section: AboutUs
:imagesDir: ../images
:stylesDir: ../stylesheets
:experimental:

== PROJECT: FitBiz

== Overview

FitBiz is a fitness business management application, specially made for fitness coaches to manage their clients. It is primarily a desktop application where the user interacts via the Command Line Interface (CLI), and views data via the Graphical User Interface (GUI). This project is written in Java 11, using JavaFX for the GUI.

== Summary of contributions

* *Major enhancement*: added the ability to autocomplete commands and their prefixes using the kbd:[Tab] key.
** *What it does*: allows the user to input FitBiz's commands with ease without having to memorise the syntax of every command available. It also allows users to efficiently get to the next prefix by just hitting kbd:[Tab] once instead of using their mouse.
** *Justification*: this feature improves the product significantly because it removes the need for users to constantly refer to the user guide. It also greatly enhances the user experience by providing a much faster way for users to interact with the CLI.
** *Highlights*: this enhancement supports all existing commands of varying formats and was designed to be easily extensible for future commands to be added. The autocomplete system is also contextually aware, and will autocomplete the corresponding command prefixes and user help messages accordingly.

* *Minor enhancement*: added the command history feature that stores user entered commands, which can then be accessed using the kbd:[] and kbd:[] keys.

* *Minor enhancement*: added an export command that allows the user to export their clients' recorded exercises into a CSV file.

* *Code contributed*: [https://github.com[Functional code]] [https://github.com[Test code]] _{give links to collated code files}_

* *Other contributions*:

** Project management:
*** Managed releases `v1.3` - `v1.5rc` (3 releases) on GitHub
** Enhancements to existing features:
*** Updated the GUI color scheme (Pull requests https://github.com[#33], https://github.com[#34])
*** Wrote additional tests for existing features to increase coverage from 88% to 92% (Pull requests https://github.com[#36], https://github.com[#38])
** Documentation:
*** Did cosmetic tweaks to existing contents of the User Guide: https://github.com[#14]
** Community:
*** PRs reviewed (with non-trivial review comments): https://github.com[#12], https://github.com[#32], https://github.com[#19], https://github.com[#42]
*** Contributed to forum discussions (examples:  https://github.com[1], https://github.com[2], https://github.com[3], https://github.com[4])
*** Reported bugs and suggestions for other teams in the class (examples:  https://github.com[1], https://github.com[2], https://github.com[3])
*** Some parts of the history feature I added was adopted by several other class mates (https://github.com[1], https://github.com[2])
** Tools:
*** Integrated a third party library (Natty) to the project (https://github.com[#42])
*** Integrated a new Github plugin (CircleCI) to the team repo

_{you can add/remove categories in the list above}_

== Contributions to the User Guide


|===
|_Given below are sections I contributed to the User Guide. They showcase my ability to write documentation targeting end-users._
|===

include::../UserGuide.adoc[tag=delete]

include::../UserGuide.adoc[tag=dataencryption]

== Contributions to the Developer Guide

|===
|_Given below are sections I contributed to the Developer Guide. They showcase my ability to write technical documentation and the technical depth of my contributions to the project._
|===

include::../DeveloperGuide.adoc[tag=undoredo]

include::../DeveloperGuide.adoc[tag=dataencryption]


== PROJECT: PowerPointLabs

---

_{Optionally, you may include other projects in your portfolio.}_
