= Amos Cheong - Project Portfolio
:site-section: AboutUs
:imagesDir: ../images
:stylesDir: ../stylesheets

== PROJECT: Delino

---

== Overview

Delino is a desktop application for couriers to manage delivery tasks. The user
interacts with it using a CLI, and it has a GUI created with JavaFX. It is written in Java, and has about 10 kLoC.

== Summary of contributions

* *Major enhancement*:
** Added `insert` command (Pull request https://github.com/AY1920S2-CS2103T-W12-1/main/pull/189[#189])
*** What it does: Allows the user to insert new delivery order into the Order List. The user can add an order
that contains the following attributes : +
**** Transaction ID
**** Name
**** Phone
**** Address
**** Email
**** Delivery Timestamp
**** Warehouse location
**** Cash on Delivery
**** Comment (Optional)
**** Type Of Item (Optional)
*** Justification: This is an important feature and it is a must-have. It allows user to insert multiple orders into
the list.
** Refactor the `list` command (Pull request https://github.com/AY1920S2-CS2103T-W12-1/main/pull/239[#239])
*** What it does: Instead of simply displaying all the orders, the user can choose to list : +
**** Delivered orders
**** Undelivered orders
*** Justification: The feature helps the user, as a courier, to know how many orders have to be completed and how many orders
are already completed.

** Added the `show` command (Pull request https://github.com/AY1920S2-CS2103T-W12-1/main/pull/199[#199])
*** What it does: It gives a more detailed information about the orders and return orders in their lists, in the form
of numbers and PieChart. The information shown is : +
**** Total Earnings
**** Orders Completed
**** Orders Returned
**** A PieChart to show to the user on how many orders are completed and not completed, returned and not returned.
** *Highlights*: +
Ability to let user to see information based on the date(s) provided. For example, the user can enter :
`show` `2020-02-02` `2020-09-01` to see all the information about the orders that are from the date `2020-02-02`
up to the date `2020-09-01`. In addition, user can show statistics about everything in all the lists or just
simply showing the statistics for today.

** Credits: UI Design ideas for `show` Command from https://www.youtube.com/watch?v=UDi051XyQ-U&t=339s

* *Minor enhancement*:
** Fix bugs for the Application (Pull requests https://github.com/AY1920S2-CS2103T-W12-1/main/pull/309[#309], https://github.com/AY1920S2-CS2103T-W12-1/main/pull/233[#233])
*** What it does: Restricts user from entering any invalid values
*** Justification: This is an essential update, as the invalid values will affect the rest of the features.

* *Code contributed*: [https://nus-cs2103-ay1920s2.github.io/tp-dashboard/#search=Amoscheong97&sort=groupTitle&sortWithin=title&since=2020-02-14&timeframe=commit&mergegroup=false&groupSelect=groupByRepos&breakdown=false&tabOpen=true&tabType=authorship&tabAuthor=Amoscheong97&tabRepo=AY1920S2-CS2103T-W12-1%2Fmain%5Bmaster%5D[Functional code and Test code]]

* *Other contributions*:

** Project management:
*** Responsible for ensuring that the team's code is compliant with the coding standards and in charge of defining, assigning and tracking all project tasks.

** Enhancements to existing GUI:
*** Make major changes to the UI to change from Window to TabView (Pull request https://github.com/AY1920S2-CS2103T-W12-1/main/pull/318[#318])

** Documentation:
*** Add Manual Testing Instructions for Developer Guide. (Pull request https://github.com/AY1920S2-CS2103T-W12-1/main/pull/81[#81])
*** Update Developer Developer Guide. (Pull requests https://github.com/AY1920S2-CS2103T-W12-1/main/pull/171[#171], https://github.com/AY1920S2-CS2103T-W12-1/main/pull/252[#252])

** Community:
*** PRs reviewed (with non-trivial review comments): (Pull requests https://github.com/AY1920S2-CS2103T-W12-1/main/pull/299[#299],
 https://github.com/AY1920S2-CS2103T-W12-1/main/pull/227[#227], https://github.com/AY1920S2-CS2103T-W12-1/main/pull/218[#218],
 https://github.com/AY1920S2-CS2103T-W12-1/main/pull/193[#193], ...)

** Tools:
*** Integrated a third party library (Netlify) to the project (https://github.com/AY1920S2-CS2103T-W12-1/main/commit/1708e0b7f72eb3eb5edaa471eda37c836fcfdbc9[#1708e0b])


== Contributions to the User Guide


|===
|_Given below are sections I contributed to the User Guide. They showcase my ability to write documentation targeting end-users._
|===

== Features

== *Insert feature*
This whole section of the Insert feature can be found https://ay1920s2-cs2103t-w12-1.github.io/main/UserGuide.html#insert[here].
This link is provided in the event if some of the cross links are not working, as they refer to documents done by another team member

include::../UserGuide.adoc[tag=insert]

== *List feature*
This whole section of the List feature can be found https://ay1920s2-cs2103t-w12-1.github.io/main/UserGuide.html#list[here].
This link is provided in the event if some of the cross links are not working, as they refer to documents done by another team member

include::../UserGuide.adoc[tag=list]

== *Show feature*
This whole section of the Show feature can be found https://ay1920s2-cs2103t-w12-1.github.io/main/UserGuide.html#show[here].
This link is provided in the event if some of the cross links are not working, as they refer to documents done by another team member

include::../UserGuide.adoc[tag=show]

== Contributions to the Developer Guide

|===
|_Given below are sections I contributed to the Developer Guide. They showcase my ability to write technical documentation and the technical depth of my contributions to the project._
|===

== Features

== *Insert feature*
This whole section of the Insert feature can be found https://ay1920s2-cs2103t-w12-1.github.io/main/DeveloperGuide.html#insert[here].
This link is provided in the event if some of the cross links are not working, as they refer to documents done by another team member

include::../DeveloperGuide.adoc[tag=insert]

== *List feature*
This whole section of the List feature can be found https://ay1920s2-cs2103t-w12-1.github.io/main/DeveloperGuide.html#list[here].
This link is provided in the event if some of the cross links are not working, as they refer to documents done by another team member

include::../DeveloperGuide.adoc[tag=list]

== *Show feature*
This whole section of the Show feature can be found https://ay1920s2-cs2103t-w12-1.github.io/main/DeveloperGuide.html#show[here].
This link is provided in the event if some of the cross links are not working, as they refer to documents done by another team member

include::../DeveloperGuide.adoc[tag=show]

== Use Cases

== *Use case for insert feature*
This whole section on Use case for insert feature can be found at https://ay1920s2-cs2103t-w12-1.github.io/main/DeveloperGuide.html#use-cases[here].
This link is provided in the event if some of the cross links are not working, as they refer to documents done by another team member

include::../DeveloperGuide.adoc[tag=use_case_insert]

== *Use case for show feature*
This whole section on Use case for show feature can be found at https://ay1920s2-cs2103t-w12-1.github.io/main/DeveloperGuide.html#use-cases[here].
This link is provided in the event if some of the cross links are not working, as they refer to documents done by another team member

include::../DeveloperGuide.adoc[tag=use_case_show]

== *Use case for list feature*
This whole section on Use case for list feature can be found at https://ay1920s2-cs2103t-w12-1.github.io/main/DeveloperGuide.html#use-cases[here].
This link is provided in the event if some of the cross links are not working, as they refer to documents done by another team member

include::../DeveloperGuide.adoc[tag=use_case_list]

== Glossary

This whole section on Glossary can be found at https://ay1920s2-cs2103t-w12-1.github.io/main/UserGuide.html#glossary[here].
This link is provided in the event if some of the cross links are not working, as they refer to documents done by another team member

include::../UserGuide.adoc[tag=command_prefix]

== Appendix G: Instructions for Manual Testing

== *Manual Testing for insert*
This whole section on manual testing for insert feature can be found at https://ay1920s2-cs2103t-w12-1.github.io/main/DeveloperGuide.html#inserting-an-order[here].
This link is provided in the event if some of the cross links are not working, as they refer to documents done by another team member

include::../DeveloperGuide.adoc[tag=appendix-insert]

== *Manual Testing for list*
This whole section on manual testing for list feature can be found at https://ay1920s2-cs2103t-w12-1.github.io/main/DeveloperGuide.html#list-orders[here].
This link is provided in the event if some of the cross links are not working, as they refer to documents done by another team member

include::../DeveloperGuide.adoc[tag=appendix-list]

== *Manual Testing for show*
This whole section on manual testing for show feature can be found at https://ay1920s2-cs2103t-w12-1.github.io/main/DeveloperGuide.html#show-2[here].
This link is provided in the event if some of the cross links are not working, as they refer to documents done by another team member

include::../DeveloperGuide.adoc[tag=appendix-show]
