= Arthur Lee - Project Portfolio
:site-section: AboutUs
:imagesDir: ../images
:stylesDir: ../stylesheets

== PROJECT: BB Productive - Level 3

---

== Overview

My team of 5 Computer Science students, including myself, aimed to build a product centered on making students who procrastinate more productive. This manifested itself into BBProductive. It is a gamified task manager that utilizes the Pomodoro productivity technique. The gamefied aspect comes into play in the form of a pet that gets hangry(hungry and angry) when tasks are not completed. The pomodoro technique consists of 25 minutes focused work and 5 minutes rest. These 2 aspects of the application as well as the task manager come together as a comprehensive solution for procrastinators to be productive.

== Summary of contributions

* *Major enhancement*: I added the ability to have reminders for the tasks.
** What it does: The “r/” flag allows the user to set the date and time inputted to be the time they are reminded. Once the time has arrived, a pop up with the task’s name and description appears, alerting and reminding the user to do the task.
** Justification: In the event users have a time sensitive task or wants to come back to the task at a later date, the “r/” flag can be added in the AddCommand or EditCommand to remind the user of the task.
** Highlights: This enhancement works with the AddCommand or EditCommand and is optional. This implementation was challenging due to the nature of when the user closes the application. The duration until the stipulated time has to be recalculated on boot and thus the decision to trigger the reminder has to be made. Also when a task is marked as done, the reminder should not be triggered.

* *Major enhancement*: I added the ability to have recurring tasks.
** What it does: The “rec/” flag allows the user to make the task reappear on a daily or weekly basis.
** Justification:  In the event users have a repeatable task that occurs on a weekly basis, he can set the task as either daily or weekly recurring to ensure the task is set as undone after the stipulated time interval. (daily or weekly)
** Highlights: This enhancement works with the AddCommand or EditCommand and is optional as well. This implementation was challenging due to how it requires to be deeply intertwined in the application’s logic and model manager, this resulted in me applying the observer design pattern to facilitate further communication between the logic and model manager.

* *Code contributed*: [https://github.com[Functional code]] [https://github.com[Test code]] _{give links to collated code files}_

* *Other contributions*:

** Project management:
*** Managed releases `v1.1` - `v1.4rc` (3 releases) on GitHub
** Enhancements to existing features:
*** Implemented the foundation of the new stylesheet used for the application
*** Adjusted the JavaFX layout to fit the Adobe XD 
*** Wrote tests for both reminders and recurring tasks

** Documentation:
** Community:
*** PRs reviewed (with non-trivial review comments): https://github.com[#12], https://github.com[#32], https://github.com[#19], https://github.com[#42]
*** Contributed to forum discussions (examples:  https://github.com[1], https://github.com[2], https://github.com[3], https://github.com[4])
*** Reported bugs and suggestions for other teams in the class (examples:  https://github.com[1], https://github.com[2], https://github.com[3])
*** Some parts of the history feature I added was adopted by several other class mates (https://github.com[1], https://github.com[2])
** Tools:
*** Adobe XD

_{you can add/remove categories in the list above}_

== Contributions to the User Guide


|===
|_Given below are sections I contributed to the User Guide. They showcase my ability to write documentation targeting end-users._
|===

include::../UserGuide.adoc[tag=delete]

include::../UserGuide.adoc[tag=dataencryption]

== Contributions to the Developer Guide

|===
|_Given below are sections I contributed to the Developer Guide. They showcase my ability to write technical documentation and the technical depth of my contributions to the project._
|===


== PROJECT: PowerPointLabs

---

_{Optionally, you may include other projects in your portfolio.}_
