= Beatrice Tay - Project Portfolio
:site-section: AboutUs
:imagesDir: ../images
:stylesDir: ../stylesheets

== PROJECT: HealthyBaby

---

== Overview

*HealthyBaby* (HYBB) is a desktop application targeted towards university students that provides users with a database of quick, easy, and healthy recipes.
HYBB helps alleviate the challenges faced while maintaining healthy eating habits, easing the transition from eating
out everyday to cooking healthy meals regularly.

The user interacts with HYBB using a Command Line Interface, and it has a Graphical User Interface created with JavaFX.

It is written in Java, and has about 18 kLoC.

== Summary of contributions

* *Major enhancement*: Added the *Planning feature*
** What it does: Allows the user to plan and remove the plans for a recipe on a certain date. The user is also able to
obtain all ingredients required for the planned recipes on a simple grocery list.
** Justification: The planning feature assists university students on their path towards healthy cooking as the user
can create a complete, healthy meal plan for the next few weeks (or even the entire year) with one simple command.
This aims ... busy students... plan cooking needsto be planned to fit the right recipe on the right day.
containing all the required ingredients alleviate costs and food wastage
** Highlights: This enhancement is affected by recipes being modified, as the plans of the modified recipe needs to be
updated as well. Ensuring that each plan is deleted or updated after each modification was challenging as HYBB supports
many recipe customisation methods (9 in total).

* *Minor enhancement*: Added Ingredient and Quantity classes to allow HYBB to estimate the portion of each food
group in the recipes.

* *Code contributed*: [https://github.com[Functional code]] [https://github.com[Test code]] _{give links to collated code files}_
. Commands: https://github.com/AY1920S2-CS2103T-T10-1/main/tree/master/src/main/java/seedu/recipe/logic/commands/plan[Functional code]
https://github.com/AY1920S2-CS2103T-T10-1/main/tree/master/src/test/java/seedu/recipe/logic/commands/plan[Test code]

. Parsers: https://github.com/AY1920S2-CS2103T-T10-1/main/tree/master/src/main/java/seedu/recipe/logic/parser/plan[Functional code]
https://github.com/AY1920S2-CS2103T-T10-1/main/tree/master/src/test/java/seedu/recipe/logic/parser/plan[Test code]

. Models: https://github.com/AY1920S2-CS2103T-T10-1/main/tree/master/src/main/java/seedu/recipe/model/plan[Functional code]
https://github.com/AY1920S2-CS2103T-T10-1/main/tree/master/src/test/java/seedu/recipe/model/plan[Test code]

. Storage: https://github.com/AY1920S2-CS2103T-T10-1/main/tree/master/src/main/java/seedu/recipe/storage/plan[Functional code]
https://github.com/AY1920S2-CS2103T-T10-1/main/tree/master/src/test/java/seedu/recipe/storage/plan[Test code]

. UI: https://github.com/AY1920S2-CS2103T-T10-1/main/tree/master/src/main/java/seedu/recipe/ui/plan[Functional code]

. FXML: https://github.com/AY1920S2-CS2103T-T10-1/main/tree/master/src/main/resources/view[Functional code]

* *Other contributions*:

** Project management:
*** Managed releases `v1.2.1` - `v1.3.1` (3 releases) on GitHub
** Enhancements to existing features:
*** Did cosmetic tweaks to the GUI: (Pull requests
https://github.com/AY1920S2-CS2103T-T10-1/main/pull/192[#192],
https://github.com/AY1920S2-CS2103T-T10-1/main/pull/195[#195])
** Documentation:
*** Did cosmetic tweaks to existing contents of the User Guide: https://github.com[#14]
** Community:
*** PRs reviewed (with non-trivial review comments):
https://github.com/nus-cs2103-AY1920S2/addressbook-level3/pull/3[#3],
https://github.com/nus-cs2103-AY1920S2/addressbook-level3/pull/26[#26],
https://github.com/nus-cs2103-AY1920S2/addressbook-level3/pull/33[#33]

*** Reported bugs and suggestions for other teams in the class (examples:
https://github.com[1],
https://github.com[2],
https://github.com[3])
*** Some parts of the history feature I added was adopted by several other class mates (https://github.com[1], https://github.com[2])
** Tools:
*** Integrated a third party library (Natty) to the project (https://github.com[#42])
*** Integrated a new Github plugin (CircleCI) to the team repo

_{you can add/remove categories in the list above}_

== Contributions to the User Guide


|===
|_Given below are sections I contributed to the User Guide. They showcase my ability to write documentation targeting end-users._
|===

include::../UserGuide.adoc[tag=delete]

include::../UserGuide.adoc[tag=dataencryption]

== Contributions to the Developer Guide

|===
|_Given below are sections I contributed to the Developer Guide. They showcase my ability to write technical documentation and the technical depth of my contributions to the project._
|===

include::../DeveloperGuide.adoc[tag=undoredo]

include::../DeveloperGuide.adoc[tag=dataencryption]


== PROJECT: PowerPointLabs

---

_{Optionally, you may include other projects in your portfolio.}_
