= Cher Wei Jie - Project Portfolio
:site-section: AboutUs
:imagesDir: ../images
:stylesDir: ../stylesheets

== PROJECT: Delino

---

== Overview

Delino is a desktop application for couriers to manage delivery tasks. The user
interacts with it using a CLI, and it has a GUI created with JavaFX.
It is written in Java and has about 10 kLoC.

== Summary of contributions

* *Major enhancement*:
** Added `return` command (Pull request: https://github.com/AY1920S2-CS2103T-W12-1/main/pull/353[#353])
*** What it does: This command allows the user to create a new return order and add it into the Return Order List or
convert a delivered order into a return order
and add it into the Return Order List.
*** Justification: This feature is a must-have in Delino as it is a delivery management app. It allows the user to convert
delivered orders into return orders and even create new return orders from scratch with the given parcel attributes.
*** Highlights: This feature requires a deep understanding of the AddressBook 3 (AB3) codebase and that took quite a bit of time.
Two different logic execution paths had to be implemented and the testing of this feature also had to be extensive
and exhaustive to ensure that no test cases were missed in the process of testing. The parametized testing functionality
provided by JUnit 5 made this process to be much more convenient (https://www.baeldung.com/parameterized-tests-junit-5).
Furthermore, new classes such as ReturnOrder, ReturnCommand, Parcel abstract class also had to be implemented for this
feature to be fully functional. Therefore, this feature affects subsequent features to be added due to changes in inheritance of classes.

** Added `delivered` command (Pull request: https://github.com/AY1920S2-CS2103T-W12-1/main/pull/302[#302] )
*** What it does: Allows the user to mark orders or return orders as delivered.
*** Justification: This is a must-have feature for a delivery management app like Delino. It allows the user to easily
mark an order or return order as delivered after delivering the parcel.
*** Highlights: This feature required good understanding of the AB3 codebase and how the entire order list and return order
list are edited to display the changes in the GUI. As such, this required a deep level of understanding of how the entire
app worked so that the changes can be executed and displayed on the GUI from the start of the command till the end of execution.

** Added the `help` command (Pull requests: https://github.com/AY1920S2-CS2103T-W12-1/main/pull/310[#310])
*** What it does: It displays a list of all Delino's commands and llows the user to see the usage of each command in Delino and
quickly be able to utilise Delino's available features.
*** Justification: This command was rather simple to implement but the main problem faced was deciding the right window size
for the pop-up help window as different screens have different resolutions and this resulted in some bugs that had to be
re-looked at and fixed.


* *Minor enhancement*:
. Updated Delino's icon image and link in the Developer Guide (Pull request: https://github.com/AY1920S2-CS2103T-W12-1/main/pull/245[#245])
. Added Non-functional requirements (NFR) in the Developer Guide (Pull request: https://github.com/AY1920S2-CS2103T-W12-1/main/pull/89[#89])
. Wrote Must-haves for user stories in Developer Guide (Pull request: https://github.com/AY1920S2-CS2103T-W12-1/main/pull/65[#65])
. Did the first mock-up for Delino's UI using Adobe XD (Pull request: https://github.com/AY1920S2-CS2103T-W12-1/main/pull/85[#85])

* *Code contributed*: [https://nus-cs2103-ay1920s2.github.io/tp-dashboard/#search=cherweijie&sort=groupTitle&sortWithin=title&since=2020-02-14&timeframe=commit&mergegroup=false&groupSelect=groupByRepos&breakdown=false[Functional code & Test code]]

* *Other contributions*:

** Project management:
. In charge of team facilitation, code integration and UI design.
. Set up Codacy with Jeremy to improve code quality of Delino's repository. (Pull request: https://github.com/AY1920S2-CS2103T-W12-1/main/pull/61[#61])
. Ensure that project deliverables are completed on time.

** Enhancements to existing features:
*** Adapted the given Address Book UI into Delino's first draft UI. (Pull request: https://github.com/AY1920S2-CS2103T-W12-1/main/pull/85[#85])

** Documentation:
*** Updated Developer Guide to include Delivered Command (Pull request: https://github.com/AY1920S2-CS2103T-W12-1/main/pull/253[#253])
*** Updated Developer Guide to include Return Command (Pull request: )
*** Updated Developer Guide to include Help Command (Pull request: )

** Community:
*** PRs reviewed (with non-trivial review comments): (Pull requests: https://github.com/AY1920S2-CS2103T-W12-1/main/pull/118[#118],
 https://github.com/AY1920S2-CS2103T-W12-1/main/pull/191[#191],
 https://github.com/AY1920S2-CS2103T-W12-1/main/pull/226[#226])

*** Reported bugs and suggestions for other teams in the class (examples:  https://github.com/Cherweijie/ped/issues)

** Tools:
*** Set up Codacy and updated its badge to link to our repository together with Jeremy (Pull request: https://github.com/AY1920S2-CS2103T-W12-1/main/pull/61[#61])

== Contributions to the User Guide


|===
|_Given below are sections I contributed to the User Guide. They showcase my ability to write documentation targeting end-users._
|===
include::../UserGuide.adoc[tag=introduction]
include::../UserGuide.adoc[tag=help]
include::../UserGuide.adoc[tag=return]
include::../UserGuide.adoc[tag=delivered]
include::../UserGuide.adoc[tag=product_information]

== Contributions to the Developer Guide

|===
|_Given below are sections I contributed to the Developer Guide. They showcase my ability to write technical documentation and the technical depth of my contributions to the project._
|===

== Design
This whole section on Delino's Design Model can be found at https://ay1920s2-cs2103t-w12-1.github.io/main/DeveloperGuide.html#Design-Model[here].
This link is provided in the event if some of the cross links are not working, as they refer to
documents done by another team member.
include::../DeveloperGuide.adoc[tag=design_model]

== Features
This whole section on the Return feature can be found at https://ay1920s2-cs2103t-w12-1.github.io/main/DeveloperGuide.html#return[here].
This link is provided in the event if some of the cross links are not working, as they refer to
documents done by another team member.
include::../DeveloperGuide.adoc[tag=return]
This whole section on the Help feature can be found at https://ay1920s2-cs2103t-w12-1.github.io/main/DeveloperGuide.html#help[here].
This link is provided in the event if some of the cross links are not working, as they refer to
documents done by another team member.
include::../DeveloperGuide.adoc[tag=help]
This whole section on the Delivered feature can be found at https://ay1920s2-cs2103t-w12-1.github.io/main/DeveloperGuide.html#delivered[here].
This link is provided in the event if some of the cross links are not working, as they refer to
documents done by another team member.
include::../DeveloperGuide.adoc[tag=delivered]

== Use Cases
This whole section on use cases for Help can be found https://ay1920s2-cs2103t-w12-1.github.io/main/DeveloperGuide.html#use-cases[here].
This link is provided in the event if some of the cross links are not working, as they refer to
documents done by another team member.
include::../DeveloperGuide.adoc[tag=use_case_help]

This whole section on use cases for Return can be found https://ay1920s2-cs2103t-w12-1.github.io/main/DeveloperGuide.html#use-cases[here].
This link is provided in the event if some of the cross links are not working, as they refer to
documents done by another team member.
include::../DeveloperGuide.adoc[tag=use_case_return]

This whole section on use cases for Delivered can be found at https://ay1920s2-cs2103t-w12-1.github.io/main/DeveloperGuide.html#use-cases[here].
This link is provided in the event if some of the cross links are not working, as they refer to
documents done by another team member.
include::../DeveloperGuide.adoc[tag=use_case_delivered]

== Glossary
This whole section on command prefixes can be found at https://ay1920s2-cs2103t-w12-1.github.io/main/DeveloperGuide.html#glossary[here].
This link is provided in the event if some of the cross links are not working, as they refer to
documents done by another team member.
include::../DeveloperGuide.adoc[tag=command_prefix]

This whole section on command flags can be found at https://ay1920s2-cs2103t-w12-1.github.io/main/DeveloperGuide.html#glossary[here].
This link is provided in the event if some of the cross links are not working, as they refer to
documents done by another team member.
include::../DeveloperGuide.adoc[tag=command_flags]

== Appendix G: Instructions for Manual Testing
This whole section on the delivered feature's instructions for manual testing can be found at https://ay1920s2-cs2103t-w12-1.github.io/main/DeveloperGuide.html#mark-parcel-as-delivered[here].
This link is provided in the event if some of the cross links are not working, as they refer to
documents done by another team member.
include::../DeveloperGuide.adoc[tag=appendix-delivered]

This whole section on the return feature's instructions for manual testing can be found at https://ay1920s2-cs2103t-w12-1.github.io/main/DeveloperGuide.html#returning-an-order[here].
This link is provided in the event if some of the cross links are not working, as they refer to
documents done by another team member.
include::../DeveloperGuide.adoc[tag=appendix-return]

This whole section on the help feature's instructions for manual testing can be found at https://ay1920s2-cs2103t-w12-1.github.io/main/DeveloperGuide.html#help-2[here].
This link is provided in the event if some of the cross links are not working, as they refer to
documents done by another team member.
include::../DeveloperGuide.adoc[tag=appendix-help]
