= Chester Sim - Project Portfolio
:site-section: AboutUs
:imagesDir: ../images
:stylesDir: ../stylesheets

== PROJECT: Coupon Stash

---

== Overview

Coupon Stash is a desktop coupons manager that allows users to keep track of
their coupons. The user interacts with it using a CLI, and it has a beautiful
GUI created with JavaFX. It is written in Java, and has about 15kLoC.

== Summary of contributions

* *Major enhancement*: added *the ability to use a coupon* (Pull request
https://github.com/AY1920S2-CS2103T-F09-1/main/pull/80[#80],
https://github.com/AY1920S2-CS2103T-F09-1/main/pull/98[#98])
** What it does: allows the user to keep track of his usage for each and every
coupon.
** Justification: This feature is essential in keeping track of coupons and
also its generated savings.
** Highlights: This enhancement ties in with other coupon fields to ensure
the valid usage of a coupon. From the start date of the coupon, to the type
of savings generated, this feature is critical to the functioning of Coupon Stash.

* *Major enhancement*: added *archiving mechanism* (Pull Request
https://github.com/AY1920S2-CS2103T-F09-1/main/pull/137[#137])
** What it does: automatically archive the coupon when it has expired or
exhausted its usages.
** Justification: This feature declutters the user's visible list of active
coupons, while retaining the ability to access the archived coupons if needed.

** Highlights: Considerations were made on the design of the archiving system, where the
initial phase focused on two separate data files for active and archived coupons. This was
found to be highly coupled, and would increase complexity and maintainability of the
application. This enhancement ties in with the Used and Expiring functionality of
Coupons to ensure correct archiving of coupons.

* *Minor enhancement*: Added shortcut (Ctrl + Q) to quit windows that do not have a CLI in
Coupon Stash (e.g. Coupon, Remind Window), to maintain the ability to use Coupon Stash with
only a keyboard (except scrolling of lists). (Pull Request
https://github.com/AY1920S2-CS2103T-F09-1/main/pull/323[#323])

* *Code contributed*: [https://nus-cs2103-ay1920s2.github.io/tp-dashboard/#search=chester[Functional & Test Code]]

* *Other contributions*:

** UI Lead:
*** Drafted and designed the overall User Interface and Logo of Coupon Stash
(https://www.figma.com/file/y2jlxT2hlLKC9THWPjUr3b/Coupon-Stash-Iterations?node-id=0%3A1[link])
*** Created Coupon, Coupon Window, and Remind Window base FXML code
(Pull Request https://github.com/AY1920S2-CS2103T-F09-1/main/pull/170[#170],
https://github.com/AY1920S2-CS2103T-F09-1/main/pull/300[#300],
https://github.com/AY1920S2-CS2103T-F09-1/main/pull/317[#317],
https://github.com/AY1920S2-CS2103T-F09-1/main/pull/323[#328])

** Project management:
*** Lead the project in terms of direction of product, defining and assigning tasks.

** Documentation:
*** Added Use Cases in User Guide (Pull Request
https://github.com/AY1920S2-CS2103T-F09-1/main/pull/28[#28])
*** Edit various part of User Guide (Pull request
https://github.com/AY1920S2-CS2103T-F09-1/main/pull/148[#148])

** Community:
*** PRs reviewed (with non-trivial review comments):
https://github.com/AY1920S2-CS2103T-F09-1/main/pull/110[#110],
https://github.com/AY1920S2-CS2103T-F09-1/main/pull/115[#115],
https://github.com/AY1920S2-CS2103T-F09-1/main/pull/154[#154]
*** Reported bugs and suggestions for other teams in the class (examples:  https://github.com[1], https://github.com[2], https://github.com[3])


== Contributions to the User Guide

|===
|_Given below are sections I contributed to the User Guide. They showcase my ability to write documentation targeting end-users._
|===

include::../UserGuide.adoc[tag=used]

include::../UserGuide.adoc[tag=archive]

include::../UserGuide.adoc[tag=unarchive]

== Contributions to the Developer Guide

|===
|_Given below are sections I contributed to the Developer Guide. They showcase my ability to write technical documentation and the technical depth of my contributions to the project._
|===

include::../DeveloperGuide.adoc[tag=archiving]

== PROJECT: Package

---

== Overview

Package is a platform tailored to the needs of a specific food business, allowing for a seamless
platform for both the business and its customers to use to order food packages. The platform manages
food packages, menus, and the delivery area of customers, which can help save the business time and
energy over using the conventional method of recording on paper and communicating over instant messaging.

Website: https://foodanatomy.herokuapp.com/

== Summary of contributions

* Communicated with business client
* Planned functionality of the platform
* Designed platform UI on https://www.figma.com/file/O1JiLIhOknekXlux9UiSDy/Package.com?node-id=0%3A1[Figma]
* Build both frontend and backend from scratch

== PROJECT: chestersim.dev

---

== Overview

https://www.chestersim.dev[chestersim.dev] is meant to be a personal website for myself, but was also used intially for me to build something
with my newfound knowledge for React. An updated https://www.figma.com/file/7DObklugMkxWiZA6YdBDgC/Website[version] is coming up soon!

== PROJECT: MoneyMove$

---

== Overview

MoneyMove$ is a project born out of the Razer Fintech Hackathon (video https://www.facebook.com/102706714599106/videos/1128359337496993[here] at the 1:10:18 mark!).
It is a savings/Sub-Accounts app that provides a curated, personalized content experience which ties directly into savings goals and habits. The app relies on Mambu's APIs to create sub-accounts - buckets - for each item, good, or service the user desires. The team intends to offer a plethora of content for the user to save up to, including gaming, food deals, movies, events and even personal banking services. The project won the prize for the top 2 in the hackathon!

== Summary of contribtions
* Main frontend engineer - build the entire app in React Native

== PROJECT: Clique

---

== Overview

Clique was a project done by me and my partner for Project Orbital (CP2106, and won the Judge's Choice Award. It is a messaging-cum-calendar mobile app,
where we try to integrate events into messaging. Read more about it in depth in the https://github.com/clique-orbital/clique2[repo]!

== Summary of contributions
* Designed majority of the UI using Sketch
* Developed and build equal share of both the frontend and the backend.


