= Choi Min Suk - Project Portfolio
:site-section: AboutUs
:imagesDir: ../images
:stylesDir: ../stylesheets

== PROJECT: ExpenseLa

---

== Overview

ExpenseLa is a desktop expense tracking application. The user interacts with it using a CLI, and it has a GUI created
with JavaFX. It is written in Java for an NUS module CS2103/CS2103T Software Engineering.

== Summary of contributions

This section provides a summary of the various contributions I have made to ExpenseLa.

=== Code contributed
You can follow these links to view a sample of my code: +
[https://github.com/AY1920S2-CS2103-T09-3/main/commits/master?author=chlalstjr[Commits]] [https://github.com/AY1920S2-CS2103-T09-3/main/pulls?utf8=%E2%9C%93&q=is%3Amerged+is%3Apr+author%3Achlalstjr+[Pull requests]] [https://nus-cs2103-ay1920s2.github.io/tp-dashboard/#search=chlalstjr&sort=groupTitle&sortWithin=title&since=2020-02-14&timeframe=commit&mergegroup=false&groupSelect=groupByRepos&breakdown=false[RepoSense Dashboard]]

=== Enhancements implemented

* *Major enhancement*: Created *bar chart* of the expenditures
** What it does: Allows the user analyse his expenditure using bar chart.
** Justification: Viewing just a list of transactions does not provide much information of his expenditure, especially if there are many transactions. Viewing it as a bar chart will allow him to analyse his expenditures better.
** Highlights: Different kinds of bar chart can be showed depending on the filter set on the transactions. When filter is of a certain month,
a stacked bar chart with days of the week as the x-axis is formed, with different weeks stacked on top of each other in ascending order.
While there is no filter, a bar chart with month as the x-axis is formed, with total expenditures of current year and previous year each shown.
Which has to reference many things from `Model` making it not easy to implement.

* *Major enhancement*: Added the ability to *toggle view* between list of transactions and chart analysis
** What it does: The `toggleview` command allows the user to switch between viewing the list of transactions and chart analysis(as said above) containing the bar chart and a pie chart.
** Justification: The user gets to view more things given the limited space the app has. This prevents compromising the amount of space given to viewing the list of transactions or the chart analysis.
** Highlights: The `toggleview` was implemented as a separate class residing in `ModelManager` for better extendability next time to toggle view between more features.

* *Minor enhancement*: Added an export command that allows the user to export the filtered transactions into a csv file.
** Justification: The user can use the data to do his own analysis of his earnings and expenditure, and in a csv file format it is organized as well as allows the user to easily use excel functions for his analysis.

* *Minor enhancement*: Added percentage to be shown for on pie chart created by my teammate (Pie chart of total expenditure separated by categories).
** Justification: A pie chart for expenditure is to show the relative amount spent on each category relative to the total expenditure. Without percentage shown it can be quite hard to tell the relative amount.
** Highlights: The pie chart library in Java does not support showing percentage, so I had to research how Java's pie chart stores the values, and use that to figure out how to calculate the percentage and concat it into the pie chart, which was not easy to implement.

=== Other contributions
* Project management:
** I managed issues assigned to me from version 1.0 to 1.4 on https://github.com/AY1920S2-CS2103-T09-3/main/milestones[GitHub].

* Enhancements to existing features:
** Refactored the original AddressBook-Level3 codebase to fit our requirements.
(Pull requests https://github.com/AY1920S2-CS2103-T09-3/main/pull/50[#50], https://github.com/AY1920S2-CS2103-T09-3/main/pull/57[#57])
** Wrote additional tests for existing features to increase coverage from 88% to 92%
(Pull request https://github.com/AY1920S2-CS2103-T09-3/main/pull/146[#146])
* Documentation:
** Did the first version of the User Guide early on with our vision for the application: (Pull request https://github.com/AY1920S2-CS2103-T09-3/main/pull/6[#6])
* Community:
*** Reviewed pull requests from my teammates: https://github.com/AY1920S2-CS2103-T09-3/main/pull/36[#36], https://github.com/AY1920S2-CS2103-T09-3/main/pull/37[#37]

== Contributions to the User Guide


|===
|_Given below are sections I contributed to the User Guide. They showcase my ability to write documentation targeting end-users._
|===

include::../UserGuide.adoc[tag=delete]

include::../UserGuide.adoc[tag=dataencryption]

== Contributions to the Developer Guide

|===
|_Given below are sections I contributed to the Developer Guide. They showcase my ability to write technical documentation and the technical depth of my contributions to the project._
|===

include::../DeveloperGuide.adoc[tag=undoredo]

include::../DeveloperGuide.adoc[tag=dataencryption]
