= CornCobs - Project Portfolio
:site-section: AboutUs
:imagesDir: ../images
:stylesDir: ../stylesheets

== PROJECT: HireLah!

---

== Overview

HireLah! is an app that helps interviewers manage their interviewees, the attributes
you look out for in these interviewees, and the questions to ask during the interviews.
As a complete solution for interviewers, HireLah! also helps interviewers conduct interviews
on the app and identify the best interviewees.

== Summary of contributions

* *Major enhancement*: Added the ability to conduct interviews from within the app itself.
** What it does: Allows the user to give the command `interview <interviewee>` to turn HireLah! into
   a note-taking app to take down comments and remarks while interviewing the candidate. Also allows
   the user to score candidates on the created attributes, and indicate when questions were asked for
   easy retrieval later.
** Justification: This is a critical feature for the app as it allows users to be more productive using our app as
   compared to maintaining their lists of candidates, questions and interview rubrics (attributes) separately. When
   conducting the interview within the app, it is easy to check the questions, the app reminds you to assign scores to all
   attributes and makes it easy to track who is interviewed.
** Credits: Team mate Agnes Natasya for creating the Transcript class and providing a clear API for the interview
   commands to consume, thus making the implementation of the commands simpler.

* *Major enhancement*: Added the ability to manage multiple interview sessions from within the app.
** What it does: When the app starts, rather than loading a default session, the app shows the user his/her
   available sessions, and allows them to choose to open a previous session or start a new one.
** Justification: This feature significantly improves the user experience of the app as previously, to change sessions,
   one would have to manually modify the `preferences.json` file before starting the app, a feature which some users
   would not be able to discover while using the app.
** Highlights: This enhancement was challenging to implement as we had to retrofit it after feedback in v1.3.
   It involved planning when and how to perform the initializing of the session-specific Storage, UI and Model components
   after the app has already started, without affecting the implementation of these classes, which had been written under
   the assumption that they would be initialized at app startup.

* *Code contributed*: https://nus-cs2103-ay1920s2.github.io/tp-dashboard/#search=corncobs&sort=groupTitle&sortWithin=title&since=2020-02-14&timeframe=commit&mergegroup=false&groupSelect=groupByRepos&breakdown=false&tabOpen=true&tabType=authorship&tabAuthor=CornCobs&tabRepo=AY1920S2-CS2103-W15-2%2Fmain%5Bmaster%5D[Both test code and functional code here]

* *Other contributions*:
** Project Management:
*** Managed release of v1.3 milestone
*** Planned division of work at the beginning of each milestone v1.2-1.4
*** Regularly checked on team mates progress to ensure each milestone's goals could be met
** Review/mentoring contributions:
*** Some PRs reviewed: https://github.com/AY1920S2-CS2103-W15-2/main/pull/103[#103], https://github.com/AY1920S2-CS2103-W15-2/main/pull/90[#90], https://github.com/AY1920S2-CS2103-W15-2/main/pull/81[#81], https://github.com/AY1920S2-CS2103-W15-2/main/pull/203[#203], https://github.com/AY1920S2-CS2103-W15-2/main/pull/190[#190], https://github.com/AY1920S2-CS2103-W15-2/main/pull/187[#187], https://github.com/AY1920S2-CS2103-W15-2/main/pull/186[#186], https://github.com/AY1920S2-CS2103-W15-2/main/pull/66[#66]
*** Helped team mate https://github.com/Weiichengg[Wei Cheng] with design and implementation of Storage component, to allow saving of individual components (AttributeList, IntervieweeList, etc),
    and saving each interviewee's transcript into a separate json file. The design allowed HireLah! to take a fine-grained approach to saving each component when changed, improving performance, and also
    validated the stored data when loading, to ensure the Model is always in a valid state. Coauthored https://github.com/AY1920S2-CS2103-W15-2/main/pull/103[#103] which implemented this design.
*** Bug reports filed: https://github.com/AY1920S2-CS2103-W15-2/main/issues/60[#60], https://github.com/AY1920S2-CS2103-W15-2/main/issues/79[#79]
** Documentation:
*** Updated use cases and user stories https://github.com/AY1920S2-CS2103-W15-2/main/pull/212[#212]
** Team-based tasks:
*** Updated the team website
*** Renamed the project and package name
** Tools:
*** Setup AppVeyor when Travis-CI was undergoing maintenance
*** Setup Coveralls to check our code coverage

== Contributions to the User Guide

include::../UserGuide.adoc[tag=FeaturesIntro]

include::../UserGuide.adoc[tag=session]

include::../UserGuide.adoc[tag=view]

include::../UserGuide.adoc[tag=finalise]

include::../UserGuide.adoc[tag=interviewPhase]

include::../UserGuide.adoc[tag=prefix]

== Contributions to the Developer Guide

include::../DeveloperGuide.adoc[tag=sessionFeature]
