= Eng Xuan En - Project Portfolio
:site-section: AboutUs
:imagesDir: ../images
:stylesDir: ../stylesheets

== PROJECT: Delino

---

== Overview

*Delino* is a desktop delivery application for couriers to manage delivery tasks. The user
interacts with it using a CLI, and it has a GUI created with JavaFX. It is written in Java, and has about 10 kLoC

== Summary of contributions

|===
|_Given below are the summary of the contributions I have made for this project._
|===

* *Major enhancement*:
** Added `import` command (Pull request https://github.com/AY1920S2-CS2103T-W12-1/main/pull/215[#215])
*** What it does: Allows the user to add multiple orders and return orders via a CSV file.
*** Justification: This is an essential update, which allows the user to save time from adding multiple orders and
return order one by one.
*** Highlights: This enhancement depends heavily on `InsertCommandParser` and `ReturnCommandParser` to process the data
retrieve from the data. Considerations have to be made to differentiate the data for `Order` and `ReturnOrder`, as they
have different attributes in their models.

** Add return order book for storage (Pull request https://github.com/AY1920S2-CS2103T-W12-1/main/pull/186[#186])
*** What it does: Stores return orders.
*** Justification: The storage of return orders is important, as the return orders are required to be separate from
orders and store as a separate json file in the hard disk from the orders.
*** Highlights: Considerations are to be made for how to store and retrieve the return order data from the json file
which is stored in hard disk.

** Modify the `clear` command (Pull requests https://github.com/AY1920S2-CS2103T-W12-1/main/pull/180[#180], https://github.com/AY1920S2-CS2103T-W12-1/main/pull/218[#218])
*** What it does: Gives the user three options to clear:
**** Only order list
**** Only return order list
**** Both order list and return order list
*** Justification: This is an essential update, which prevent the user from having the trouble clearing the orders or return orders one by one.
*** Highlights: Considerations are to be made for the clearing either one of the list or both order list and return order list,
as clearing the wrong list, the data in that list would be lost permanently.

* *Minor enhancement*:
** Add `timestamp` field into the model(Pull requests https://github.com/AY1920S2-CS2103T-W12-1/main/pull/175[#175], https://github.com/AY1920S2-CS2103T-W12-1/main/pull/198[#198])
*** What it does: Allows orders and return orders to keep track of the delivery date and time.
*** Justification: This is an essential update, which allows user to input timestamp for the order and return order.

** Add `comment` field into the model(Pull request https://github.com/AY1920S2-CS2103T-W12-1/main/pull/172[#172])
*** What it does: Allows orders and return orders to store customer comment.
*** Justification: This is an essential update, which allows the courier to be able to take note about +
the customer's request, such as sending a message to notify the customer that the courier will be sending +
their parcel on that day.

* *Code contributed*: [https://nus-cs2103-ay1920s2.github.io/tp-dashboard/#search=exeexe93&sort=groupTitle&sortWithin=title&since=2020-02-14&timeframe=commit&mergegroup=false&groupSelect=groupByRepos&breakdown=true[Functional code & Test code]]

* *Other contributions*:

** Enhancements to existing GUI:
** Modified the `Clear Window` to suit the needs for the modified `clear` command. (Pull request https://github.com/AY1920S2-CS2103T-W12-1/main/pull/180[#180])
** Replaced the address book icon to Delino icon. (Pull request https://github.com/AY1920S2-CS2103T-W12-1/main/pull/226/commits/d7c029f7cdf8a11f42bbae6d3f5c49f6a0f19eee[226])

** Project management:
*** Co-team lead of the project, in charge of defining, assigning, and tracking project tasks.
Furthermore, ensure project deliverables are done on time and in the right format.

** Documentation:
*** Updated the product website's heading and navigation bar. (Pull request https://github.com/AY1920S2-CS2103T-W12-1/main/pull/119[#119])
*** Edited various parts of the User Guide (Pull requests https://github.com/AY1920S2-CS2103T-W12-1/main/pull/173[#173], https://github.com/AY1920S2-CS2103T-W12-1/main/pull/226[#226])
*** Added use cases and updated the Storage and Implementation part of the Developer Guide for saving, import
and clear features (Pull requests https://github.com/AY1920S2-CS2103T-W12-1/main/pull/186[#186], https://github.com/AY1920S2-CS2103T-W12-1/main/pull/197[#197], https://github.com/AY1920S2-CS2103T-W12-1/main/pull/218[#218])


** Community:
*** PRs reviewed (with non-trivial review comments): (Pull requests https://github.com/AY1920S2-CS2103T-W12-1/main/pull/126[#126],
https://github.com/AY1920S2-CS2103T-W12-1/main/pull/139[#139], https://github.com/AY1920S2-CS2103T-W12-1/main/pull/174[#174], https://github.com/AY1920S2-CS2103T-W12-1/main/pull/189[#189])
*** Reported bugs and suggestions for other teams in the class: (Examples: https://github.com/Exeexe93/ped/issues[PE dry run issue])
*** Contributed to forum discussion  by asking help question: (Example: https://github.com/nus-cs2103-AY1920S2/forum/issues/104[#104])
** Tools:
*** Integrated a new Github plugin (AppVeyor) to the team repo (https://github.com/AY1920S2-CS2103T-W12-1/main/commit/37b0cd15b16cfe6fe08cb9bdba9ac8e37a1722a3[#37b0cd1])

== Contributions to the User Guide

|===
|_Given below are sections I contributed to the User Guide. They showcase my ability to write documentation targeting end-users._
|===

== Features

=== Clear feature
This whole section on Clear feature can be found at https://ay1920s2-cs2103t-w12-1.github.io/main/UserGuide.html#clear[here]. This link is provided in the event if some of the cross links are not working, as they refer to documents
done by another team member.
include::../UserGuide.adoc[tag=clear]

=== Import feature
This whole section on Import feature can be found at https://ay1920s2-cs2103t-w12-1.github.io/main/UserGuide.html#import[here]. This link is provided in the event if some of the cross links are not working, as they refer to documents
done by another team member.
include::../UserGuide.adoc[tag=import]

== Command Summary
This whole section on command summary can be found at https://ay1920s2-cs2103t-w12-1.github.io/main/UserGuide.html#command-summary[here]. This link is provided in the event if some of the cross links are not working, as they refer to documents
done by another team member.
include::../UserGuide.adoc[tag=command_summary]

== Command Prefix
This whole section on command prefix can be found at https://ay1920s2-cs2103t-w12-1.github.io/main/UserGuide.html#command_prefix[here]. This link is provided in the event if some of the cross links are not working, as they refer to documents
done by another team member.
include::../UserGuide.adoc[tag=command_prefix]

== Command Flags
This whole section on command flags can be found at https://ay1920s2-cs2103t-w12-1.github.io/main/UserGuide.html#command_flags[here]. This link is provided in the event if some of the cross links are not working, as they refer to documents
done by another team member.
include::../UserGuide.adoc[tag=command_flags]

== Contributions to the Developer Guide

|===
|_Given below are sections I contributed to the Developer Guide. They showcase my ability to write technical documentation and the technical depth of my contributions to the project._
|===

== Storage Design
This whole section on storage design can be found at https://ay1920s2-cs2103t-w12-1.github.io/main/DeveloperGuide.html#Design-Storage[here]. This link is provided in the event if some of the cross links are not working, as they refer to documents
done by another team member.
include::../DeveloperGuide.adoc[tag=Design-Storage]

== Clear feature
This whole section on Clear feature can be found at https://ay1920s2-cs2103t-w12-1.github.io/main/DeveloperGuide.html#clear-feature[here]. This link is provided in the event if some of the cross links are not working, as they refer to documents
done by another team member.

include::../DeveloperGuide.adoc[tag=clear]

== Import feature
This whole section on Import feature can be found at https://ay1920s2-cs2103t-w12-1.github.io/main/DeveloperGuide.html#import[here]. This link is provided in the event if some of the cross links are not working, as they refer to documents
done by another team member.
include::../DeveloperGuide.adoc[tag=import]

== Use Case for Clear feature
This whole section on Use Case for Clear feature can be found at https://ay1920s2-cs2103t-w12-1.github.io/main/DeveloperGuide.html#use-cases[here]. This link is provided in the event if some of the cross links are not working, as they refer to documents
done by another team member.
include::../DeveloperGuide.adoc[tag=use_case_clear]

== Use Case for Import feature
This whole section on Use Case for Import feature can be found at https://ay1920s2-cs2103t-w12-1.github.io/main/DeveloperGuide.html#use-cases[here]. This link is provided in the event if some of the cross links are not working, as they refer to documents
done by another team member.
include::../DeveloperGuide.adoc[tag=use_case_import]

== Command Prefix
This whole section on command prefix can be found at https://ay1920s2-cs2103t-w12-1.github.io/main/DeveloperGuide.html#glossary[here]. This link is provided in the event if some of the cross links are not working, as they refer to documents
done by another team member.
include::../DeveloperGuide.adoc[tag=command_prefix]

== Command Flags
This whole section on command flags can be found at https://ay1920s2-cs2103t-w12-1.github.io/main/DeveloperGuide.html#glossary[here]. This link is provided in the event if some of the cross links are not working, as they refer to documents
done by another team member.
include::../DeveloperGuide.adoc[tag=command_flags]

== Clear feature
This whole section on Manual Testing for Clear feature can be found at https://ay1920s2-cs2103t-w12-1.github.io/main/DeveloperGuide.html#clear-orders[here]. This link is provided in the event if some of the cross links are not working, as they refer to documents
done by another team member.
include::../DeveloperGuide.adoc[tag=appendix-clear]

== Import feature
This whole section on Manual Testing for Import feature can be found at https://ay1920s2-cs2103t-w12-1.github.io/main/DeveloperGuide.html#import-orders[here]. This link is provided in the event if some of the cross links are not working, as they refer to documents
done by another team member.
include::../DeveloperGuide.adoc[tag=appendix-import]
