= Fatin - Project Portfolio
:site-section: AboutUs
:imagesDir: ../images
:stylesDir: ../stylesheets

== Project: TA-Tracker

== Overview

TA-Tracker is a productivity tool made for NUS School of Computing (SoC) Teaching Assistants (TAs) who want to be able
to track and manage their students and teaching duties in in a single, convenient-to-use platform rather than using
several excel spreadsheets or notes. The application is mainly written in Java and spans a considerable 20k Lines of
Code (LoC). The codebase is well-maintained with a rigorous system of checks and tests in place to ensure that code
quality is consistently high. A comprehensive set of guides are also provided to ensure a smooth on-boarding process
for both users and contributors alike.

== Summary of contributions
As the main developer of the application’s User Interface (UI), I played a crucial role in integrating my teammates’
features with the UI. During group discussions, I placed extra emphasis on guiding my teammates to create engineering
solutions that allowed for easier assimilation into the UI, to ensure that their work becomes user-visible. As a
result, my team was able to morph the given codebase from a trivial application into a polished product.

I put my considerable experience with designing the application to use by being available at all times to help out with
various tasks, like design considerations and debugging. As the most experienced UI developer in the team, I was
highly involved in helping my teammates become more familiar with JavaFX and CSS. I believe that my role in the
development of the project was especially crucial as I enabled my teammates to be able to display all the hard work
that they have put into the development of their respective features to the users. My major contributions are as follows:

=== Updated the UI and implemented relevant commands to improve User Experience

=== Improved upon overall code quality

=== Adding extensive automated tests

Here is the code that I have written for this product: [https://github.com/CS2103-AY1819S1-T09-3/main/commits?author=j-lum[All commits]] [https://nus-cs2103-ay1819s1.github.io/cs2103-dashboard/#=undefined&search=j-lum[Dashboard]]

=== Other contributions

** Project management:

I commented on critical pull requests.
I also extensively tested and reported bugs along with a comprehensive reproduction reports: https://github.com/CS2103-AY1819S1-W14-4/main/issues/170[#170] https://github.com/CS2103-AY1819S1-W14-4/main/issues/175[#175]

** Documentation:

I wrote a tutorial to walk users through the on-boarding process with a sample project that demonstrates most of the key features of our application. This light-hearted tutorial also serves to show that our application is relevant and solves problems that the reader can relate to.

I also contributed multiple new illustrations to the developer's guide to help future contributors visualise what each command does.
The illustrations are included in my contributions below.

== Contributions to the User Guide

|===
|_Given below are sections I contributed to the User Guide.
They showcase my ability to write comprehensive but simple documentation that addresses the needs of users._
|===

include::../UserGuide.adoc[tag=getting_started1]

The tutorial is truncated to account for the page limit.

=== User guide command documentation
---
include::../UserGuide.adoc[tag=canvas]

== Contributions to the Developer Guide

|===
|_Given below are sections I contributed to the Developer Guide. They showcase my ability to write technical documentation and the technical depth of my contributions to the project._
|===

include::../DeveloperGuide.adoc[tag=layer]
