= Jeremy Loh - Project Portfolio
:site-section: AboutUs
:imagesDir: ../images
:stylesDir: ../stylesheets

== PROJECT: Delino

== Overview

Delino is a desktop application for couriers to manage delivery tasks. The user
interacts with it using a CLI, and it has a GUI created with JavaFX. It is written in Java, and has about 10 kLoC.

== Summary of contributions

* *Major enhancement*: Add `nearby` command (searching by postal sector) *(+1091 -45 LOC)* +
(Pull request https://github.com/AY1920S2-CS2103T-W12-1/main/pull/181[#181])

** *What it does*: +
Allows the user to find all orders located at a specified postal sector.
** *Justification*: +
It is helpful for our target audience, couriers, to find all relevant orders
at a specific postal sector. +
This would allow them to deliver their pending orders in
a more efficient manner.
** *Highlights*: +
Ability to find orders based on all postal codes in Singapore. +
A helpful message regarding the specified postal code is also shown. +
Parsing has been done to user input of a valid postal sector (the first two digits of a six digit Singapore postal code).
Figuring out an effective way of testing and implementing all possible postal sectors
was time consuming as there are 28 postal sectors in Singapore. +
Thankfully, JUnit 5 has https://www.baeldung.com/parameterized-tests-junit-5[parameterized tests]
that allowed me to test more effectively. The mapping of postal sectors was done using a *HashMap*.

** *Credits*: Information about the various postal sectors was obtained from https://www.ura.gov.sg/realEstateIIWeb/resources/misc/list_of_postal_districts.htm[here]



* *Major enhancement*: Enhancement to `nearby` command to search the 5 general regions of Singapore +

** Add ability for `nearby` command to search orders located at one of the 5 areas of Singapore: +
Central, East, North-east, West, North. *(+1,579 −164 LOC)* +
(Pull request https://github.com/AY1920S2-CS2103T-W12-1/main/pull/194[#194]) +

** *What it does*: +
Allows the user to find all orders located at a specified region of Singapore. +
** *Justification*: +
This makes it easy for couriers in a certain area to select orders to be done in that region.
** *Highlights*: +
Ability to find orders based on the 5 regions in Singapore. A helpful message regarding the specified area is also shown. +
The 5 regions were mapped using a separate helper class as these regions were
grouped using their postal sectors.

** *Credits*: Information about the various areas was obtained from https://keylocation.sg/singapore/districts-map


* *Minor enhancement*:
** Add Warehouse field for Orders. +
(Pull request https://github.com/AY1920S2-CS2103T-W12-1/main/pull/174[#174])
*** What it does: Allows for orders to keep track of warehouse.
*** Justification: It is a must have. Couriers need to keep track of the warehouse they need to collect/return
the order to.

* *Minor enhancement*:
** Modify delete command to take in flags. +
(Pull request https://github.com/AY1920S2-CS2103T-W12-1/main/pull/240[#240])
(Pull request https://github.com/AY1920S2-CS2103T-W12-1/main/pull/304[#304])
*** What it does: Allows for deletion of orders or return orders.
*** Justification: It is a must have. Couriers need to be able to delete from a specific list.
Our application has two lists: Order list and Return Order list.
Deletion is done by providing an appropriate flag.

* *Code contributed*: [https://nus-cs2103-ay1920s2.github.io/tp-dashboard/#search=jeremyloh&sort=groupTitle&sortWithin=title&since=2020-02-14&timeframe=commit&mergegroup=false&groupSelect=groupByRepos&breakdown=false[Functional code and Test Code]]

* *Other contributions*:

** Project management: In charge of Documentation. Supporting role in Testing and Code Quality. +

** Documentation:
*** Update delete and nearby command DG:
https://github.com/AY1920S2-CS2103T-W12-1/main/pull/251[#251]
** Community:
*** PRs reviewed (with non-trivial review comments): +
https://github.com/AY1920S2-CS2103T-W12-1/main/pull/71[#71]
https://github.com/AY1920S2-CS2103T-W12-1/main/pull/171[#171]
https://github.com/AY1920S2-CS2103T-W12-1/main/pull/187[#187]
https://github.com/AY1920S2-CS2103T-W12-1/main/pull/226[#226]
https://github.com/AY1920S2-CS2103T-W12-1/main/pull/310[#310]

*** Contributed to forum discussions (https://github.com/nus-cs2103-AY1920S2/forum/issues/88[88])
*** Reported bugs and suggestions for other teams in the class (https://github.com/JeremyLoh/ped/issues[PE dry run issues])
** Tools:
*** Integrated a third party library (Coveralls) to the project (https://github.com/AY1920S2-CS2103T-W12-1/main/commit/248bb4db86666270ee5025f1d4f9276ef1d530ec[248bb4d])
*** Configure Repo to Provide Additional Data to RepoSense (Pull request https://github.com/AY1920S2-CS2103T-W12-1/main/pull/220[#220])


== Contributions to the User Guide


|===
|_Given below are sections I contributed to the User Guide. They showcase my ability to write documentation targeting end-users._
|===
include::../UserGuide.adoc[tag=how_to_navigate_user_guide]

== Features
include::../UserGuide.adoc[tag=delete]
include::../UserGuide.adoc[tag=nearby]

== Glossary
include::../UserGuide.adoc[tag=command_prefix]
include::../UserGuide.adoc[tag=command_flags]
include::../UserGuide.adoc[tag=area_table]

== Contributions to the Developer Guide

|===
|_Given below are sections I contributed to the Developer Guide. They showcase my ability to write technical documentation and the technical depth of my contributions to the project._
|===

== Features
include::../DeveloperGuide.adoc[tag=delete]

include::../DeveloperGuide.adoc[tag=nearby]

== Glossary
include::../DeveloperGuide.adoc[tag=command_prefix]
include::../DeveloperGuide.adoc[tag=command_flags]

== Use Case
include::../DeveloperGuide.adoc[tag=use_case_delete]
include::../DeveloperGuide.adoc[tag=use_case_nearby]

// Appendix F: Product Survey
include::../DeveloperGuide.adoc[tag=appendix-product-survey]

== Appendix G: Instructions for Manual Testing
include::../DeveloperGuide.adoc[tag=appendix-delete]
include::../DeveloperGuide.adoc[tag=appendix-nearby]
