= Jeremy Loh - Project Portfolio
:site-section: AboutUs
:imagesDir: ../images
:stylesDir: ../stylesheets

== PROJECT: Delino

'''

== Overview

Delino is a desktop application for couriers to manage delivery tasks. The user
interacts with it using a CLI, and it has a GUI created with JavaFX. It is written in Java, and has about 10 kLoC.

== Summary of contributions

====
* *Major enhancement*: +
Add `nearby` command +
(searching by postal sector) +
(March 17 2020) +
*(+1091 -45 LOC)* +
(Pull request https://github.com/AY1920S2-CS2103T-W12-1/main/pull/181[#181])

** *What it does*: +
Allows the user to find all orders located at a specified postal sector.
** *Justification*: +
It is helpful for our target audience, couriers, to find all relevant orders
at a specific postal sector. +
This would allow them to deliver their pending orders in
a more efficient manner.
** *Highlights*: +
Ability to find orders based on all postal codes in Singapore. +
A helpful message regarding the specified postal code is also shown. +
Parsing has been done to user input of a valid postal sector (the first two digits of a six digit Singapore postal code)

** Credits: Information about the various postal sectors was obtained from https://www.ura.gov.sg/realEstateIIWeb/resources/misc/list_of_postal_districts.htm[here]
====

====
* *Major enhancement*:

Enhancement to `nearby` command to search the 5 general regions of Singapore +

Add ability for `nearby` command to search orders located at one of the 5 areas of Singapore: +

1. Central
2. East
3. North-east
4. West
5. North

(March 22 2020) +
*(+1,579 −164 LOC)* +
(Pull request https://github.com/AY1920S2-CS2103T-W12-1/main/pull/194[#194]) +

** *What it does*: +
Allows the user to find all orders located at a specified region of Singapore. +
** *Justification*: +
This makes it easy for couriers in a certain area to select orders to be done in that region.
** *Highlights*: +
Ability to find orders based on the 5 regions in Singapore. +
A helpful message regarding the specified area is also shown. +

** Credits: Information about the various areas was obtained from https://keylocation.sg/singapore/districts-map
====

* *Minor enhancement*:
** Add Warehouse field for Orders. +
(Pull request https://github.com/AY1920S2-CS2103T-W12-1/main/pull/174[#174])
*** What it does: Allows for orders to keep track of warehouse.
*** Justification: It is a must have. Couriers need to keep track of the warehouse they need to collect/return
the order to.

* *Minor enhancement*:
** Modify Ui for application (temporary change). +
(Pull request https://github.com/AY1920S2-CS2103T-W12-1/main/pull/192[#192])
*** What it does: Cosmetic change to UI (change in colours and placement of UI elements).
*** Justification: A temporary UI change to differentiate our application from the
original UI of AddressBook Level 3.

* *Minor enhancement*:
** Modify delete command to take in flags. +
(Pull request https://github.com/AY1920S2-CS2103T-W12-1/main/pull/240[#240])
(Pull request https://github.com/AY1920S2-CS2103T-W12-1/main/pull/304[#304])
*** What it does: Allows for deletion of orders or return orders.
*** Justification: It is a must have. Couriers need to be able to delete from a specific list.
Our application has two lists: Order list and Return Order list.

* *Code contributed*: [https://github.com[Functional code]] [https://github.com[Test code]] _{give links to collated code files}_

* *Other contributions*:

** Project management:
*** In charge of Documentation. Supporting role in Testing and Code Quality.
** Enhancements to existing features:

** Documentation:
*** Did cosmetic tweaks to existing contents of the User Guide: https://github.com[#14]
** Community:
*** PRs reviewed (with non-trivial review comments):
*** Contributed to forum discussions (examples:  https://github.com[1], https://github.com[2], https://github.com[3], https://github.com[4])
*** Reported bugs and suggestions for other teams in the class (examples:  https://github.com[1], https://github.com[2], https://github.com[3])
** Tools:
*** Integrated a third party library (Coveralls) to the project (https://github.com/AY1920S2-CS2103T-W12-1/main/commit/248bb4db86666270ee5025f1d4f9276ef1d530ec[248bb4d])
*** Configure Repo to Provide Additional Data to RepoSense (Pull request https://github.com/AY1920S2-CS2103T-W12-1/main/pull/220[#220])


== Contributions to the User Guide


|===
|_Given below are sections I contributed to the User Guide. They showcase my ability to write documentation targeting end-users._
|===

include::../UserGuide.adoc[tag=delete]

include::../UserGuide.adoc[tag=dataencryption]

== Contributions to the Developer Guide

|===
|_Given below are sections I contributed to the Developer Guide. They showcase my ability to write technical documentation and the technical depth of my contributions to the project._
|===

include::../DeveloperGuide.adoc[tag=undoredo]

include::../DeveloperGuide.adoc[tag=dataencryption]

