= Elysia Tan - Project Portfolio
:site-section: AboutUs
:imagesDir: ../images
:stylesDir: ../stylesheets

== PROJECT: Naggy Joel

---

== Overview

Naggy Joel is a desktop social life manager application for University students to manage their social life and studies. The user interacts with it using a Command Line Interface (CLI), and it has a GUI created with JavaFX. It is written in Java, and has about 15k Loc.

Naggy Joel allows users to keep track of contacts, restaurants, school deadlines, and events - 4 different but closely related aspects of a University student's life. It aims to help the user live life to the fullest!

== Summary of contributions
=== Major Enhancements
* *Added the feature to allow users to `add/edit/delete` restaurants*
** What it does: Allows the user to `add/edit/delete` a restaurant with the specified name, location, visited status, type of cuisine, price point, and operating hours
** Justification: This set of features improves the application significantly, because other then keeping contacts, students might want to take note of goods restaurants that they visited, restaurants that they wish to try but did not yet have the opportunity to try, and most importantly, restaurants that open at odd hours (when they need food studying late) and these features allow the student to do that
** Highlights:
*** This set of enhancements comprise a huge amount of code as it required building the Restaurant and RestaurantBook model from scratch, this also required a thorough understanding of restaurants and how they differ from contacts
*** To maintain consistency of the code, an in-depth understanding of RegEx expressions for validation of input parameters was also required and had to be learnt
** Credits: _{referenced the original AddressBook and Person model}_

* *Added the feature to allow users to `undo/redo` previous commands*
** What it does: Allows the user to `undo` all previous commands one at a time; preceding `undo` commands can be reversed by using the `redo` command
** Justification: This feature improves the product significantly because a user can make mistakes in commands and this provides a convenient way for users to rectify them
** Highlights:
*** This enhancement affects existing commands and commands to be added in future, and hence required an in-depth analysis of design alternatives (for example, how do we want to modify Model and ModelManager, how do we want to store the different states, what is the implementation that uses the least memory, what are the commands that changes the state, etc)
*** The implementation was also challenging as it required a manual inspection and changing of the 20 commands that changes the state of the model (for example, adding an item into an ArrayList had to be done by first creating a new ArrayList and copying all existing items instead of simply adding the new item into the ArrayList, etc)
*** This enhancement also had to consider what was shown on the GUI, on top of reversing the database, as an indication/confirmation to the user that the command was indeed undone/redone
** Credits: _NIL_

=== Minor Enhancements
* *Edited the `edit/addnote/editnote/deletenote` command for AddressBook*
** What it does: Shows the details of the contact edited upon the successful execution of each of these 4 commands
** Justification: The list of contact shows only the name, tags, and phone number; showing the user the details of these contacts when the user edits the user provides visual confirmation of the successful execution of the commands
** Highlights:
*** These 4 commands that show the details of a contact changes the state of the data while the `(ab)get` command does not change the state of the data; hence a careful distinction between the 2 is essential to ensuring `undo/redo` works properly
** Credits: _NIL_

* *Reworked the `clear` command to clear all entries from the entire application*
** What it does: Clears all entries in the entire application instead of just the AddressBook
** Justification: `clear` as intuitively understood should be to clear the entire application and not just one portion (AddressBook) of the application
** Highlights:
*** As the only command that does more than modifies more than 1 area of the model (clears AddressBook, RestaurantBook, SchoolworkTracker, EventTracker), it had to be implemented properly to trigger only 1 state change, and not 4 for `undo/redo` to work properly
** Credits: _NIL_

=== Code
* Code contributed: [https://nus-cs2103-ay1920s2.github.io/tp-dashboard/#=undefined&search=hhjoel[Code]]

=== Other Contributions
* Enhancements to existing features
** Wrote additional tests for existing features to increase coverage (PR https://github.com/AY1920S2-CS2103-W14-3/main/pull/192[PR #192])
** Re-organised layout of the `help` command to group similar commands together (PR https://github.com/AY1920S2-CS2103-W14-3/main/pull/77[#77], https://github.com/AY1920S2-CS2103-W14-3/main/pull/181[#181])
** Edited the GUI of the application (PR https://github.com/AY1920S2-CS2103-W14-3/main/pull/171[#171])
* Documentation
** Contributed to both the User Guide and Developer Guide for this project
* Contribution to team-based tasks
** Updated the User Guide to match the application for Week 11's dry run (Commit https://github.com/AY1920S2-CS2103-W14-3/main/commit/e909a7260abedf874db5f05fb36dbfb71aaba5c0#diff-d80058c033b9f127ec727c18cc84ce4d[e909a72])
** Designed and modelled the initial UI (Commit https://github.com/AY1920S2-CS2103-W14-3/main/commit/463ab1cb3078dc37b443eba7d2a648d510c27f63[463ab1c])
** Tested all the features in the application for potential bugs
* Community
** Contributed to forum discussions (Example: https://github.com/nus-cs2103-AY1920S2/forum/issues/116[#116])
** Reported bugs and suggestions for other teams in the class (Repository https://github.com/hhjoel/ped/issues[PED])
** Reviewed and merged PRs by team members
** Helped team members debug problems in their code and gave suggestions on how to enhance features

== Contributions to the User Guide

|===
|_Given below are sections I contributed to the User Guide. They showcase my ability to write documentation targeting end-users._
|===

== Contributions to the Developer Guide

|===
|_Given below are sections I contributed to the Developer Guide. They showcase my ability to write technical documentation and the technical depth of my contributions to the project._
|===

---