= Ng Yi Long, Kester - Project Portfolio
:site-section: AboutUs
:imagesDir: ../images
:stylesDir: ../stylesheets

== PROJECT: Nice and Amazing Student Assistant (NASA)

== Overview

Nice & Amazing Student Assistant (NASA) is an application for busy university students to manage their module
assignments, lessons, exams and consultations etc.

== Code Contribution

Click on the following link to see the code contributed to the project on RepoSENSE. +
https://nus-cs2103-ay1920s2.github.io/tp-dashboard/#search=kester-ng&sort=groupTitle&sortWithin=title&since=2020-02-14&timeframe=commit&mergegroup=false&groupSelect=groupByRepos&breakdown=false[Code Contribution]

== Summary of contributions

* *Major Enhancement*: Added Calendar view for activities.
** What it does: Allows users to see their activities displayed onto a calendar.
** Justification: This feature allows users to be able to see upcoming activities for upcoming week etc which allows them to better plan their schedule.
** Highlights: The calendar Ui and view was created from scratch. There are many challenges involved in this enhancement:
*** Populating the calendar grids with the correct dates were difficult as there were many conditions to take note of, examples include what day does the month start, is it leap year this year etc.
*** Populating the grids with the deadlines was not very difficult. But events was very difficult. As events can span from start date to end date, making sure the events are populated on the calendar during this time interval was very tedious as there are many conditions to take note of.
*** Syncing with the user input was also not very easy, given our model structure. Adding event-listeners had to be done in a proper way to ensure the calendar syncs with the current state of the application.

* *Major enhancement*: added the ability for users to export the calendar onto a .ics file for portability
** What it does: Allows users to export the current calendar in the application onto a .ics file for use in other calendar applications.
** Justification: While the calendar view is useful, there are certain dedicated calendar applications with more features. And hence being able to export the calendar view to their favourite calendar app will make user experience better. In addition, it is more convenient as it allows the calendar to be viewed on multiple devices and platforms or shared among others.
** Highlights: The following enhancement was also very challenging. Understanding the format and how to write .ics file was not easy. Secondly, writing the logic on how deadline and events are to be displayed took a bit of thinking. Lastly, being able to have auto-rescheduling of events/deadlines also required quite a bit of effort as well.

* *Minor enhancement*: Updated list command to be able to filter based on modules.

* *Minor enhancement*: Updated the find command.

* *Minor enhancement*: Added all the CRUD functionality for the application.

* *Minor enhancement*: Added a refresh command that allows users to refresh to update the UI statuses.

* *Other contributions*:

** Project management:
*** Managed releases `v1.3` on GitHub
** Enhancements to existing features:
*** Fixed GUI display of calendar not syncing properly with the tab/command box. (Pull Requests https://github.com/AY1920S2-CS2103T-T10-4/main/pull/272[#272])
*** Fixed bugs related to model, commands and UI. (Pull Requests https://github.com/AY1920S2-CS2103T-T10-4/main/pull/262[#262], https://github.com/AY1920S2-CS2103T-T10-4/main/pull/256[#256], https://github.com/AY1920S2-CS2103T-T10-4/main/pull/163[#163], https://github.com/AY1920S2-CS2103T-T10-4/main/pull/146[#146], https://github.com/AY1920S2-CS2103T-T10-4/main/pull/132[#132])
*** Added logic for commands, parsers and JUNIT tests for them. (Pull Requests https://github.com/AY1920S2-CS2103T-T10-4/main/pull/246[#246], https://github.com/AY1920S2-CS2103T-T10-4/main/pull/178[#178], https://github.com/AY1920S2-CS2103T-T10-4/main/pull/100[#100], https://github.com/AY1920S2-CS2103T-T10-4/main/pull/94[#94])
*** Refactored the whole code base. (Pull Requests https://github.com/AY1920S2-CS2103T-T10-4/main/pull/246[#246], https://github.com/AY1920S2-CS2103T-T10-4/main/pull/90[#90])
** Documentation:
*** Updated basic command usage, test cases for DG and updated images for UG and DG. (Pull Requests https://github.com/AY1920S2-CS2103T-T10-4/main/pull/22[#22], https://github.com/AY1920S2-CS2103T-T10-4/main/pull/65/files[#65], https://github.com/AY1920S2-CS2103T-T10-4/main/pull/168[#168])
*** Updated DG with proper UML diagrams. (Pull Request https://github.com/AY1920S2-CS2103T-T10-4/main/pull/151[#151])
*** UML diagrams for DG includes the adding deadline, export calendar and reminder features.
*** Updated UG commands for adding activities, find, list, delete activities, calendar and reminder features.
** Community:
*** PRs reviewed (with non-trivial comments): https://github.com/AY1920S2-CS2103T-T10-4/main/pull/263[#263], https://github.com/AY1920S2-CS2103T-T10-4/main/pull/89[#89], https://github.com/AY1920S2-CS2103T-T10-4/main/pull/77[#77], https://github.com/AY1920S2-CS2103T-T10-4/main/pull/142[#142]
*** Reported bugs for teammates (Example: https://github.com/AY1920S2-CS2103T-T10-4/main/issues/249[#249])
** Tools:
*** Integrated travis, appveyor, coverage/coveralls, codeacy into project.

_{you can add/remove categories in the list above}_

== Contributions to the User Guide


|===
|_Given below are sections I contributed to the User Guide. They showcase my ability to write documentation targeting end-users._
|===

include::../UserGuide.adoc[tag=add]

include::../UserGuide.adoc[tag=done]

include::../UserGuide.adoc[tag=calendar]

== Contributions to the Developer Guide

|===
|_Given below are sections I contributed to the Developer Guide. They showcase my ability to write technical documentation and the technical depth of my contributions to the project._
|===

include::../DeveloperGuide.adoc[tag=deadlines]

include::../DeveloperGuide.adoc[tag=calendar]

include::../DeveloperGuide.adoc[tag=reminder]

