= Kenny Ho - Project Portfolio
:site-section: AboutUs
:imagesDir: ../images
:stylesDir: ../stylesheets

== PROJECT: Delino

---

== Overview

Delino is a desktop application for couriers to manage delivery tasks. The user
interacts with it using a CLI, and it has a GUI created with JavaFX. It is written in Java, and has about 16 kLoC.

== Summary of contributions

* *Major enhancement*:

. *Added `search` feature* (Pull request https://github.com/AY1920S2-CS2103T-W12-1/main/pull/187[#187]) +
Functionality of feature can be found https://ay1920s2-cs2103t-w12-1.github.io/main/UserGuide.html#search[here] and implementation of it can be found https://ay1920s2-cs2103t-w12-1.github.io/main/DeveloperGuide.html#search[here].

*** *What it does*: +
Allows the user to specifically search for keywords that matches any fields of the parcel. The user are also able to narrow down their search range by providing different flags and prefixes.

*** *Justification*: +
This is one of the key feature of Delino as it allows the user to sieve out parcels of their interest from the large parcels list.

*** *Highlights*: +
This enhancement is heavily affected by the fields added in parcel. A new field requires an update for Search, hence affecting future implementation. Implementing this feature requires
the thorough understanding of the existing class in AB3 such as the `ArgumentMultimap` and the `NameContainsKeywordsPredicate`. Furthermore, JavaFX class `Predicate` was used to achieve functionality of this feature.
Moreover, as this features allows user to search in many different possible way, testing the different scenarios are hard. ParametizedTest of JUnit testing was used to make my test code much cleaner.

. *Updated `edit` feature* (Pull request https://github.com/AY1920S2-CS2103T-W12-1/main/pull/234[#234]) +
Functionality of feature can be found https://ay1920s2-cs2103t-w12-1.github.io/main/UserGuide.html#edit[here] and implementation of it can be found https://ay1920s2-cs2103t-w12-1.github.io/main/DeveloperGuide.html#edit[here].

*** *What it does*: +
Allows the user to edit specific fields of a parcel, Order or Return Order.

*** *Justification*: +
This is one of the key feature of Delino as it allows the user to edit any field in Orders or Return Orders. It is especially important as the user might need to reschedule the delivery date due to unforeseen circumstances.

*** *Highlights*: +
This enhancement is affected by the design of parcel class. It affects the future implementation of any future features that will alter the parcel design.
This feature requires a thorough understanding of the existing code of AB3 such as the `ArgumentMultimap` class.

* *Minor enhancement*: +

. Improve UI of Delino (Pull requests: https://github.com/AY1920S2-CS2103T-W12-1/main/pull/209[#209], https://github.com/AY1920S2-CS2103T-W12-1/main/pull/221[#221]), https://github.com/AY1920S2-CS2103T-W12-1/main/pull/363[#363].

. Allow user to easily see the time in Delino by adding a real-time clock (Pull requests: https://github.com/AY1920S2-CS2103T-W12-1/main/pull/336[#336]).

* *Code contributed*: [https://nus-cs2103-ay1920s2.github.io/tp-dashboard/#search=khsc96&sort=groupTitle&sortWithin=title&since=2020-02-14&timeframe=commit&mergegroup=false&groupSelect=groupByRepos&breakdown=false[Functional code & Test code]]

* *Other contributions*:

** Project management:
. In charge of both code integration and testing.
. Finalised the pre-releases and releases of Delino https://github.com/AY1920S2-CS2103T-W12-1/main/releases/tag/v1.2[v1.2], https://github.com/AY1920S2-CS2103T-W12-1/main/releases/tag/v1.3[v1.3] and https://github.com/AY1920S2-CS2103T-W12-1/main/releases/tag/v1.4[v1.4] on github.

** Enhancements to existing features:
. UI changes Pull requests : https://github.com/AY1920S2-CS2103T-W12-1/main/pull/209[#209], https://github.com/AY1920S2-CS2103T-W12-1/main/pull/221[#221], https://github.com/AY1920S2-CS2103T-W12-1/main/pull/363[#363].
. Improve search feature and edit feature functionality to cover Return Order as well as coverage of test case and error messages https://github.com/AY1920S2-CS2103T-W12-1/main/pull/187[#187], https://github.com/AY1920S2-CS2103T-W12-1/main/pull/234[#234], https://github.com/AY1920S2-CS2103T-W12-1/main/pull/248[#248], https://github.com/AY1920S2-CS2103T-W12-1/main/pull/305[#305].

** Documentation:
. Update Edit feature, Search feature, Quick start, Glossary and minor documentation bugs of https://ay1920s2-cs2103t-w12-1.github.io/main/UserGuide.html[*User Guide*] (Pull requests: https://github.com/AY1920S2-CS2103T-W12-1/main/pull/91[#91], https://github.com/AY1920S2-CS2103T-W12-1/main/pull/92[#92], https://github.com/AY1920S2-CS2103T-W12-1/main/pull/128[#128], https://github.com/AY1920S2-CS2103T-W12-1/main/pull/135[#135], https://github.com/AY1920S2-CS2103T-W12-1/main/pull/177[#177], https://github.com/AY1920S2-CS2103T-W12-1/main/pull/195[#195], https://github.com/AY1920S2-CS2103T-W12-1/main/pull/227[#227], https://github.com/AY1920S2-CS2103T-W12-1/main/pull/316[#316]).
. Update Use cases 1-6, Product Scope, Image rendering bug, Search feature and Edit feature of https://ay1920s2-cs2103t-w12-1.github.io/main/DeveloperGuide.html[*Developer Guide*] (Pull requests: https://github.com/AY1920S2-CS2103T-W12-1/main/pull/76[#76], https://github.com/AY1920S2-CS2103T-W12-1/main/pull/114[#114], https://github.com/AY1920S2-CS2103T-W12-1/main/pull/178[#178], https://github.com/AY1920S2-CS2103T-W12-1/main/pull/204[#204], https://github.com/AY1920S2-CS2103T-W12-1/main/pull/208[#208], https://github.com/AY1920S2-CS2103T-W12-1/main/pull/231[#231], https://github.com/AY1920S2-CS2103T-W12-1/main/pull/249[#249], https://github.com/AY1920S2-CS2103T-W12-1/main/pull/259[#259], https://github.com/AY1920S2-CS2103T-W12-1/main/pull/316[#316]).
. Added own email in ContactUs, changed title of all documents to match Delino name and Update of own PPP (Pull requests : https://github.com/AY1920S2-CS2103T-W12-1/main/pull/80[#80], https://github.com/AY1920S2-CS2103T-W12-1/main/pull/92[#92], https://github.com/AY1920S2-CS2103T-W12-1/main/pull/321[#321]).

** Community:
*** PRs reviewed (with non-trivial review comments): https://github.com/AY1920S2-CS2103T-W12-1/main/pull/81[#81], https://github.com/AY1920S2-CS2103T-W12-1/main/pull/116[#116], https://github.com/AY1920S2-CS2103T-W12-1/main/pull/121[#121], https://github.com/AY1920S2-CS2103T-W12-1/main/pull/171[#171], https://github.com/AY1920S2-CS2103T-W12-1/main/pull/181[#181], https://github.com/AY1920S2-CS2103T-W12-1/main/pull/194[#194], https://github.com/AY1920S2-CS2103T-W12-1/main/pull/309[#309], https://github.com/AY1920S2-CS2103T-W12-1/main/pull/318[#318]
*** Contributed to forum discussions by asking a few help questions https://github.com/nus-cs2103-AY1920S2/forum/issues/32[#32], https://github.com/nus-cs2103-AY1920S2/forum/issues/35[#35], https://github.com/nus-cs2103-AY1920S2/forum/issues/89[#89], https://github.com/nus-cs2103-AY1920S2/forum/issues/108[#108].
*** Reported bugs and suggestions for other teams in the class https://github.com/khsc96/ped/issues/1[#1], https://github.com/khsc96/ped/issues/2[#2], https://github.com/khsc96/ped/issues/3[#3], https://github.com/khsc96/ped/issues/4[#4], https://github.com/khsc96/ped/issues/5[#5], https://github.com/khsc96/ped/issues/6[#6], https://github.com/khsc96/ped/issues/7[#7], https://github.com/khsc96/ped/issues/8[#8].

** Tools:
*** Integrated a third party library (Travis) to the project (https://github.com/AY1920S2-CS2103T-W12-1/main/commit/8f78de044b27b80a9ca893234a11ca184e114f50[#8f78de0])


== Contributions to the User Guide

|===
|_Given below are sections that I have contributed to Delino's User Guide. They showcase my ability to write documentation targeting end-users._
|===

== *Edit feature*
This whole section on Edit feature can be found https://ay1920s2-cs2103t-w12-1.github.io/main/UserGuide.html#edit[here]. This link is provided in the event if some of the cross links are not working, as they refer to documents
done by another team member.

include::../UserGuide.adoc[tag=edit]

== *Search feature*
This whole section on Search feature can be found at https://ay1920s2-cs2103t-w12-1.github.io/main/UserGuide.html#search[here]. This link is provided in the event if some of the cross links are not working, as they refer to documents
done by another team member.

include::../UserGuide.adoc[tag=search]

== *Command summary*
This whole section on Command summary can be found at https://ay1920s2-cs2103t-w12-1.github.io/main/UserGuide.html#command-summary[here]. This link is provided in the event if some of the cross links are not working, as they refer to documents
done by another team member.

include::../UserGuide.adoc[tag=command_summary]

== Contributions to the Developer Guide

|===
|_Given below are sections that I have contributed to Delino's Developer Guide. They showcase my ability to write technical documentation and the technical depth of my contributions to the project._
|===

== *Edit feature*
This whole section on Edit feature can be found https://ay1920s2-cs2103t-w12-1.github.io/main/DeveloperGuide.html#edit[here]. This link is provided in the event if some of the cross links are not working, as they refer to documents
done by another team member.

include::../DeveloperGuide.adoc[tag=edit]

== *Search feature*
This whole section on Search feature can be found at https://ay1920s2-cs2103t-w12-1.github.io/main/DeveloperGuide.html#search[here]. This link is provided in the event if some of the cross links are not working, as they refer to documents
done by another team member.

include::../DeveloperGuide.adoc[tag=search]

== *Use case for Edit*
This whole section on Use case for edit feature can be found at UC05 of https://ay1920s2-cs2103t-w12-1.github.io/main/DeveloperGuide.html#use-cases[here]. This link is provided in the event if some of the cross links are not working, as they refer to documents
done by another team member.

include::../DeveloperGuide.adoc[tag=use_case_edit]

== *Use case for search*
This whole section on Use case for search feature can be found at UC07 of https://ay1920s2-cs2103t-w12-1.github.io/main/DeveloperGuide.html#use-cases[here]. This link is provided in the event if some of the cross links are not working, as they refer to documents
done by another team member.

include::../DeveloperGuide.adoc[tag=use_case_search]

== *Manual Testing - Appendix Edit*
This whole section on Manual testing of Edit feature can be found https://ay1920s2-cs2103t-w12-1.github.io/main/DeveloperGuide.html#edit-orders[here]. This link is provided in the event if some of the cross links are not working, as they refer to documents
done by another team member.

include::../DeveloperGuide.adoc[tag=appendix-edit]

== *Manual Testing - Appendix Search*
This whole section on Manual testing of Search feature can be found https://ay1920s2-cs2103t-w12-1.github.io/main/DeveloperGuide.html#search-an-order[here]. This link is provided in the event if some of the cross links are not working, as they refer to documents
done by another team member.

include::../DeveloperGuide.adoc[tag=appendix-search]
