= Max Pang - Project Portjolio

== Project: NUSProductivity

---

== Overview

NUSProductivity is a desktop application for NUS students. The user interacts with it using a CLI, and it has a GUI creasted with JavaFX.
The application is intended to help NUS students solve their productivity issues and ease student's daily task in NUS.

== Summary of contributions

* *Major Enchancement*: Added all classes and functions in `searcher` package.
** What it does: `searcher` package contains support for all module related tasks in the project.
** Justification: Makes it easier for team to handle all module related functions in their own code.
** Highlights: This enchancement forms the backbone of all module related tasks in each function, such as moduleTask in calender, or getting grades for cap calculator.
** Credits: NUSMods API, for all module related information.

* *Major Enchancement 2*: Module search function.
** What it does: `search` command returns a module object parsed from the JSON object requested with NUSmods's API and caches it.
** Justification: Parsing the information from NUSmods into a format we can more easily used has saved us alot of trouble with coding. Plus caching results means we are less reliant on internet in the long run.
** Highlights: The module object returned is used in many other parts of the project, such as calender and cap calculator.
** Credits: NUSmods API, for all module related information.

* *Minor contributions*: Wireframed the entire UI Design

* *Code contributed*: [https://nus-cs2103-ay1920s2.github.io/tp-dashboard/#search=mpang45456&sort=groupTitle&sortWithin=title&since=2020-02-14&timeframe=commit&mergegroup=false&groupSelect=groupByRepos&breakdown=false[All my Code]]

* *Other Contributions*:

** Documentation:
*** Tweaks to existing Developers Guide
** Reviewing/mentoring contribution:
*** Gave feedbacks and reviewed on code pull requests
** Community:
*** Reported bugs and suggestions for other teams in the class (examples: https://github.com/mpang45456/ped/issues/1[1])
