= Shaun Goh - Project Portfolio
:site-section: AboutUs
:imagesDir: ../images
:stylesDir: ../stylesheets

== PROJECT: FoodieBot

---

== Overview

Our team was tasked with the objective of morphing AddressBook Level 3 and further building from it.
We came to a decision to create FoodieBot, an application that caters to the broad masses that dine at NUS.

FoodieBot maintains the original CLI interface and we updated the GUI using JavaFX along with adding
new functionality to fulfil the requirements of FoodieBot.

FoodieBot was created with the vision of catering to the various needs of people of dine at NUS, and solve
the pain points that these groups of people have. We narrowed our focus down to three issues, people who cannot
find their way around, people who want to save money and people who cannot decide where to eat. FoodieBot
solves all these problems with key features such as a _navigation_ feature to help people find their way,
a _budget_ feature to help NUS students keep track of their spendings and a _randomizer_ feature that makes
the decision of where to eat for you.

== Summary of contributions

* *Enhancement*: added the *select* function
** What it does: The `select` function allows users to select food they are planning to purchase directly from
   the application
** Justification: The `select' function gives the user the ability to keep track of food he is planning to eat, and
   FoodieBot saves the selected food in its internal database so that it can be retrieved when required for other features.
** Highlights: When the user selects the food, FoodieBot automatically updates the budget if the user has set a
  budget. This makes it convenient for the user to keep track of his/her spending.
** Credits: -

* *Code contributed*: [https://github.com/AY1920S2-CS2103T-F11-3/main/commits?author=SHAUNGOH97[Functional code]]
[https://github.com/AY1920S2-CS2103T-F11-3/main/commit/de8636e50a4984ffa98ae6ff66e29344cc1b9efa[Test code]]

* *Other contributions*:
** Enhancements to existing features:
*** Updated UI with a budget bar to give visual indication of remaining budget (Pull request https://github.com/AY1920S2-CS2103T-F11-3/main/pull/206[#206])
** Entry of Sample Data:
*** Filled FoodieBot with input data of Canteens, Stalls and Food. (Pull Request https://github.com/AY1920S2-CS2103T-F11-3/main/pull/91[#91])
*** Inserted pictures for the sample data to improve quality of UI (Pull Request https://github.com/AY1920S2-CS2103T-F11-3/main/pull/147[#147])

== Contributions to the User Guide
|===
|_Given below are sections I contributed to the User Guide. They showcase my ability to write documentation targeting end-users._
|===
* https://github.com/AY1920S2-CS2103T-F11-3/main/blob/master/docs/UserGuide.adoc#46-select-the-food--select[SelectItemCommand Selection]


== Contributions to the Developer Guide
|===
|_Given below are sections I contributed to the Developer Guide. They showcase my ability to write technical documentation and the technical depth of my contributions to the project._
|===
* https://github.com/AY1920S2-CS2103T-F11-3/main/blob/master/docs/DeveloperGuide.adoc#511-select-command[SelectItem Command]
