= Sim Sheng Xue - Project Portfolio
:site-section: AboutUs
:imagesDir: ../images
:stylesDir: ../stylesheets

== PROJECT: Code Camp X

---

== Overview

Code Camp X (CCX) is for those who prefer to use a desktop app to manage the administrative tasks of running a coding camp. More importantly, CCX is optimized for those who prefer to work with a Command Line Interface (CLI) while still having the benefits of a Graphical User Interface (GUI). If you can type fast, CCX can allow you to manage your camp’s administrative tasks faster than traditional GUI apps.

In the document below, the *four main features* refers to Student, Staff, Course and Finance

== Summary of contributions

* *Major enhancement*: added initial code base for the *four main features*
** What it does: implemented the major functionality needed for each of the *four main features*.
This includes the fields needed for each features such as ID and course fee amount, Add, Delete, Edit, Clear, Find, List.
** Justification: This feature improves the product significantly because the initial code base allows us to work on each of our
own assigned features with fewer code conflicts.
** Highlights: This enhancement affects the commands to be added in the future, hence it sets the initial
code base needed for future features to be built upon. This implementation is especially challenging,
because alternative design implementations need to be considered, and numerous commands are added to the application.

* *Major enhancement*: added *the GUI alone* over *three* iterations
** First iteration: added four different *tabs* to the GUI, displaying Student, Staff, Course and Finance
** Second iteration: updated the GUI to look like our initial mock-up. Changed color schemes and added Summary Panel
** Third iteration: revamped the GUI by improving the color schemes further. Added sub-panels in each tab.
For example, the Student tab now has an additional selected Student panel, along with a panel showing the list of courses assigned to the student
T
** Justification: This feature improves the product significantly because a user can see clearly the effects of the changes made in the GUI
This implementation is especially challenging, because of the amount of effort taken to plan how the GUI should look like,
and ensuring that the GUI is suitable for every member of the team.
** Highlights: This enhancement also supports the clicking of the GUI. For example, the Student bar can be clicked to show the list of course assigned to the student. Every GUI interaction can be be replicated using a CLI command.

* *Minor enhancement*: added the support of a summary panel which displays the overall statistics of the coding camp
* *Minor enhancement*: added a quick navigation command that allows the user to switch between different tabs quickly (Select command and CTRL+UP/DOWN shortcuts)
* *Minor enhancement*: added a history command that allows the user to navigate to previous commands using up/down keys.

* *Code contributed*: [https://github.com[Functional code]] [https://github.com[Test code]] _{give links to collated code files}_

* *Other contributions*:

** Project management:
*** Managed releases `v1.3` - `v1.5rc` (3 releases) on GitHub
** Enhancements to existing features:
*** Updated the GUI color scheme (Pull requests https://github.com[#33], https://github.com[#34])
*** Wrote additional tests for existing features to increase coverage from 88% to 92% (Pull requests https://github.com[#36], https://github.com[#38])
** Documentation:
*** Did cosmetic tweaks to existing contents of the User Guide: https://github.com[#14]
** Community:
*** PRs reviewed (with non-trivial review comments): https://github.com[#12], https://github.com[#32], https://github.com[#19], https://github.com[#42]
*** Contributed to forum discussions (examples:  https://github.com[1], https://github.com[2], https://github.com[3], https://github.com[4])
*** Reported bugs and suggestions for other teams in the class (examples:  https://github.com[1], https://github.com[2], https://github.com[3])
*** Some parts of the history feature I added was adopted by several other class mates (https://github.com[1], https://github.com[2])
** Tools:
*** Integrated a third party library (Natty) to the project (https://github.com[#42])
*** Integrated a new Github plugin (CircleCI) to the team repo

_{you can add/remove categories in the list above}_

== Contributions to the User Guide


|===
|_Given below are sections I contributed to the User Guide. They showcase my ability to write documentation targeting end-users._
|===

include::../UserGuide.adoc[tag=delete]

include::../UserGuide.adoc[tag=dataencryption]

== Contributions to the Developer Guide

|===
|_Given below are sections I contributed to the Developer Guide. They showcase my ability to write technical documentation and the technical depth of my contributions to the project._
|===

include::../DeveloperGuide.adoc[tag=undoredo]

include::../DeveloperGuide.adoc[tag=dataencryption]


== PROJECT: PowerPointLabs

---

_{Optionally, you may include other projects in your portfolio.}_
