= Kwan Xin Jie - Project Portfolio
:site-section: AboutUs
:imagesDir: ../images
:stylesDir: ../stylesheets

== PROJECT: Naggy Joel

---

== Overview

Naggy Joel is a desktop application used by University students to manage social life. The user interacts with it using a CLI, and it has a GUI created with JavaFX.

It is an application that allows users to manage all aspects of their social life, ranging from your different social circles and contacts, to events, as well as, places to hang out and potential practical gifts that will be very much appreciated by the recipients, all without compromising on academic life.

== Summary of contributions

=== Major enhancement:
* *Added the ability to add/edit/delete note commands for each contact*
** What it does: allows the user to add multiple notes, edit the added notes, or delete the added notes.
** Justification: This feature improves the product significantly because a user can add in additional information to a contact that they wish to remember/ is deemed important.
** Highlights: This enhancement affects existing commands and commands to be added in future. It required an in-depth analysis of design alternatives. The implementation too was challenging as it required changes to existing commands.
** Credits: _{reused the original RemarkCommand}_

* *Added the ability to add/edit/delete note commands for each restaurant*
** What it does: allows the user to add multiple notes, edit the added notes, or delete the added notes.
** Justification: This feature improves the product significantly because a user can add in additional information to a restaurant in order to keep track of the dishes' reviews.
** Highlights: This enhancement affects existing commands and commands to be added in future. It required an in-depth analysis of design alternatives. The implementation too was challenging as it required changes to existing commands.
** Credits: _{referenced from RemarkCommand}_

=== Minor enhancement:
* *Added the ability to retrieve a single particular contact.*
** What it does: This allows the user to view the information of a particular contact in full detail.
** Justification: As we added in more fields to a person in the Address Book, we cut down the information listed on the Address Book list command. Thus, this command allows the user to view the rest of the information.
** Highlights: This enhancements requires the understanding of how the filtering of the Address Book contacts are done, and to display it on the application.

* *Added the ability to sort assignments*
** What it does: This allows the user to sort the assignments by deadline, or estimated number of hours to be completed.
** Justification: As our application allows user to keep track of the assignments that they have to complete, providing a sorting feature allows for prioritisation of assignments based on the criteria (deadline/time needed) the user prefers.
** Highlights: Uncompleted assignments will always be listed before completed assignments so that users have a clearer view.

* *Added a visited option for restaurants*
** What it does: This allows the user to indicate if they have visited a restaurant.
** Justification: As there might be a handful of restaurants stored in the Restaurant Book, this feature allows the user to keep track of which restaurants they have visited.

* *Edited the existing delete command for Address Book*
** What it does: This allows the user to delete particular fields of the contact.
** Justification: There might be some fields in a contact that a user no longer needs, thus this helps to tidy up the contact information.
** Highlights: Users can still delete the entire contact, or they may choose to delete particular fields of the contact.

* *Code contributed*: [https://nus-cs2103-ay1920s2.github.io/tp-dashboard/#=undefined&search=vanessa1098[Summary of code contributions]]

* *Other contributions*:

** Project management:
** Enhancements to existing features:
*** Edited the help command to display all commands on the user interface.
*** Edited the GUI of the application (Pull requests https://github.com/AY1920S2-CS2103-W14-3/main/pull/53[#53], https://github.com/AY1920S2-CS2103-W14-3/main/pull/142[#142])
*** Wrote additional tests for existing features to increase coverage (Pull requests https://github.com/AY1920S2-CS2103-W14-3/main/pull/46[#46])
** Documentation:
*** Did cosmetic tweaks to existing contents of the User Guide (Pull requests https://github.com/AY1920S2-CS2103-W14-3/main/pull/152[#152])
** Community:
*** Reviewed PRs and provided suggestions for my teammates
*** Reported bugs and suggestions for other teams in the module

== Contributions to the User Guide


|===
|_Given below are sections I contributed to the User Guide. They showcase my ability to write documentation targeting end-users._
|===

== Contributions to the Developer Guide

|===
|_Given below are sections I contributed to the Developer Guide. They showcase my ability to write technical documentation and the technical depth of my contributions to the project._
|===

== PROJECT: PowerPointLabs

---
