= Ong Wan Xuan - Project Portfolio for MODdy
:site-section: AboutUs
:imagesDir: ../images
:stylesDir: ../stylesheets

== PROJECT: MODdy

---

== Overview

MODdy is a desktop application used by NUS Computing students to track their course progression, manage modules and manage deadlines. The user interacts with it using a CLI, and it has a GUI created with JavaFX. It is written in Java, and has about 10 kLoC.
It is an application developed by a team of 5 NUS Computing students, adapted from AddressBook-Level3 project created by SE-EDU initiative at https://se-education.org/[SE-Education].

== Summary of contributions

* *Major enhancement*: Added the ability to *show profile, module, semester and focus area*
** What it does: Allows the user to display an overview of his profile, display details of a module, display all modules taken in the specified semester, and display all modules available under the specified focus area.
** Justification: This feature improves the product significantly because it allows a user to see all his modules and grades at one glance, and this convenience is a main feature of this app. It also allows user to see the modules he has taken, information on each module and requirements of each focus area so they can plan for modules to take better.
** Highlights: This enhancement required an in-depth analysis of design alternatives as there were many different objects (e.g. `Name`, `ModuleCode`, `Year`, `FocusArea`) to be parsed separately. The implementation too was challenging as it was decided to have a single `ShowCommand` class instead of extracting each `show` feature to inherit a `ShowCommand` class.

* *Major enhancement*: Added the ability to *store modules under each course requirements, as well as modules under each focus areas in JSON format*
** What it does: Allows the app to parse the course data into relevant Java objects, and to be used for the implementations of the app's main features.
** Justification: This feature improves the product significantly because it allows the app to provide users with all of SoC courses' information from different websites in a single app, which is a main feature of this app.
** Highlights: This enhancement required the process of going through each of the course's website under NUS School of Computing, as well as manually extracting and converting information provided by NUS SoC into the JSON file.

* *Minor enhancement*: Added the ability to *manage tasks with deadlines* by implementing deadlines related classes.

* *Code contributed*: https://nus-cs2103-ay1920s2.github.io/tp-dashboard/#=undefined&search=wanxuanong[Functional and test code]


* *Other contributions*:

** Project management:
*** Managed all 5 milestones `v1.0` - `v1.4` on GitHub systematically, linking relevant issues and pull requests for each of them
(Milestone https://github.com/AY1920S2-CS2103T-W13-3/main/milestone/1[v1.0], https://github.com/AY1920S2-CS2103T-W13-3/main/milestone/2[v1.1], https://github.com/AY1920S2-CS2103T-W13-3/main/milestone/3[v1.2], https://github.com/AY1920S2-CS2103T-W13-3/main/milestone/4[v1.3], https://github.com/AY1920S2-CS2103T-W13-3/main/milestone/5[v1.4]).
*** Maintained the entire issue tracker by opening issues for each milestone, tagging with the appropriate labels, assigning issues to members and milestones, authoring up to *79* https://github.com/AY1920S2-CS2103T-W13-3/main/issues/created_by/wanxuanong[issues].

** Team-based tasks:
*** Updated User Guide sections that are not specific to features implemented by each member, e.g.
https://ay1920s2-cs2103t-w13-3.github.io/main/UserGuide.html#introduction[Introduction], https://ay1920s2-cs2103t-w13-3.github.io/main/UserGuide.html#about-the-user-guide[About the user guide], https://ay1920s2-cs2103t-w13-3.github.io/main/UserGuide.html#quick-start[Quick Start], https://ay1920s2-cs2103t-w13-3.github.io/main/UserGuide.html#faq[FAQ], https://ay1920s2-cs2103t-w13-3.github.io/main/UserGuide.html#command-summary[Command Summary].
*** Updated Developer Guide sections that are not specific to features implemented by each member, e.g.
https://ay1920s2-cs2103t-w13-3.github.io/main/DeveloperGuide.html#introduction[Introduction], https://ay1920s2-cs2103t-w13-3.github.io/main/DeveloperGuide.html#setting-up[Setting up], https://ay1920s2-cs2103t-w13-3.github.io/main/DeveloperGuide.html#Design-Architecture[Design: Architecture].
*** Did major cosmetic tweaks to revamp the User Guide, redesigning the way information is presented in the User Guide (Pull requests https://github.com/AY1920S2-CS2103T-W13-3/main/pull/150[#150], https://github.com/AY1920S2-CS2103T-W13-3/main/pull/156[#156], https://github.com/AY1920S2-CS2103T-W13-3/main/pull/160[#160]).

** Enhancements to existing features:
*** Wrote additional tests for existing features (`add` and `delete`) to increase coverage across a few pull requests (Pull requests https://github.com/AY1920S2-CS2103T-W13-3/main/pull/266/commits/3c5900b5df7d592eb4283b44a2ac99db0345c012[#266], https://github.com/AY1920S2-CS2103T-W13-3/main/pull/287[#287], https://github.com/AY1920S2-CS2103T-W13-3/main/pull/314[#314], https://github.com/AY1920S2-CS2103T-W13-3/main/pull/357[#357]).

** Community:
*** PRs reviewed: https://github.com/AY1920S2-CS2103T-W13-3/main/pull/72[#72], https://github.com/AY1920S2-CS2103T-W13-3/main/pull/74[#74], https://github.com/AY1920S2-CS2103T-W13-3/main/pull/75[#75], https://github.com/AY1920S2-CS2103T-W13-3/main/pull/82[#82], https://github.com/AY1920S2-CS2103T-W13-3/main/pull/94[#94]
*** Reported bugs and suggestions for other teams in the class (examples: https://github.com/wanxuanong/ped/issues[ZeroToOne], https://github.com/nus-cs2103-AY1920S2/addressbook-level3/pull/36[CookBuddy Recipe Manager]).


== Contributions to the User Guide


|===
|_Given below are sections I contributed to the User Guide for features implemented. They showcase my ability to write documentation targeting end-users._
|===

include::../UserGuide.adoc[tag=new]

include::../UserGuide.adoc[tag=add]



== Contributions to the Developer Guide

|===
|_Given below are sections I contributed to the Developer Guide for features implemented. They showcase my ability to write technical documentation and the technical depth of my contributions to the project._
|===

include::../DeveloperGuide.adoc[tag=command]

include::../DeveloperGuide.adoc[tag=new]

include::../DeveloperGuide.adoc[tag=add]
