@startuml
!include ../style.puml

skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

Class ToggleView {
    <color:#white>- isViewList: boolean

    <color:#white>+ getIsViewList() : boolean
    <color:#white>+ switchIsViewList()
    <color:#white>+ setIsViewList(isViewList: boolean)
}

show members
@enduml
