:imagesDir: ../../images/

== Eng Xuan En - UML Diagrams

* *Import Feature UML Diagrams* +

image::ImportActivityDiagram.svg[width=75%]
This Activity Diagram purpose is to describe the general work flow of the Import feature. This diagram is especially
useful for users, as it give them a general work flow of how Import command works and what they should expect out of
Delino when performing a Import command.

image::ImportClassDiagram.svg[width=60%]
This Class Diagram purpose is to describe the dependencies of ImportCommand class when implementing this feature.
This diagram is essential to our Delino application because it allows developer or users who are interested to better
understand the underlying dependencies of ImportCommand class.

image::ImportCommandSequenceDiagram.svg[width=75%]
This Sequence Diagram shows a more detailed explanation of the communication between the different classes used in
the Logic after the user execute the import command.

image::ExecuteImportCommand.svg[width=75%]
This Sequence Diagram shows a more detailed explanation of the communication between the different classes used in the
Logic and Model after the ImportCommand being executed by the Logic Manager.

* *Clear Feature UML Diagram*

image::ClearActivityDiagram.svg[width=75%]
The purpose of this Activity Diagram is to describe the general work flow of the Clear feature.
This diagram is especially useful for users, as it give them a general work flow of how Clear command works and what
they should expect out of Delino when performing a Clear command.

image::ClearCommandClassDiagram.svg[width=60%]
This Class Diagram purpose is to describe the dependencies of SearchCommand class when implementing this feature.
This diagram is essential to our Delino application because it allows developer or users who are interested to better
understand the underlying dependencies of SearchCommand class.

image::ExecuteClearCommand.svg[width=75%]
This Sequence Diagram is to show a more detailed explanation of the communication between the Logic and Model class of
Delino once an execution of clear command is performed.

image::StorageClassDiagram.svg[]
This Class Diagram purpose is to give a overview of a storage system in Delino, whereby StorageManager is interacting
with Logic Manager through the interface, Storage. The diagram also shows the relationship between StorageManager and
the other storage class.