:imagesDir: ../../images/

== Amos Cheong UML Diagrams

* *Insert Feature UML Diagrams*

image::InsertClassDiagram.svg[alt=InsertClass, width=40%]
The Insert Command Class Diagram describes and shows the dependencies of the InsertCommand class.
It also shows what are the classes and methods that are being used by the InsertCommand class when
the Insert Command is called.

image::InsertParserClassDiagram.svg[alt=InsertParser, width=40%]
The InsertParser Class Diagram shows the classes that InsertParser Class is dependant on. Developers will be able to
know what classes are involved when the InsertParser class is used in the code. Whenever the Insert Command is
called, the InsertParser class will be involved as well. Therefore, it is also part of the InsertCommand but it
goes into the details of what classes are involved in the parsing and validation of the arguments parsed in.

image::InsertActivityDiagram.svg[alt=InsertActivity, width=40%]
The Insert Command Activity Diagram describes the execution of the Insert command. It considers
the result of every scenarios, command execution success or failure, that could happen during the process.
This diagram can help the reader to understand all the possible outcomes of this command execution.

image::InsertCommandSequenceDiagram.svg[alt=InsertSequence, width=40%]
The Insert Command Sequence Diagram shows the interactions of all the classes objects with the InsertCommand object
during execution. Developers will be able to understand how does the other class objects work with the InsertCommand
object when the user inputs a command.

* *List Feature UML Diagrams*

image::ListClassDiagram.svg[alt=ListClass, width=40%]
The List Command Class Diagram describes and shows the dependencies of the ListCommand class.
It also shows what are the classes and methods that are being used by the ListCommand class when
the List Command is called.

image::ListActivityDiagram.svg[alt=ListActivity, width=40%]
The List Command Activity Diagram describes the execution of the List command. It considers
the result of every scenarios, command execution success or failure, that could happen during the process.
This diagram can help the reader to understand all the possible outcomes of this command execution.

image::ListCommandSequenceDiagram.svg[alt=ListSequence, width=40%]
The List Command Sequence Diagram shows the interactions of all the classes objects with the ListCommand object
during execution. Developers will be able to understand how does other class objects work with the ListCommand
object when the user inputs a command.

* *Show Feature UML Diagrams*

image::ShowCommandClassDiagram.svg[alt=ShowClass, width=40%]
The Show Command Class Diagram describes and shows the dependencies of the ShowCommand class.
It also shows what are the classes and methods that are being used by the ShowCommand class when
the Show Command is called.

image::ShowCommandActivityDiagram.svg[alt=ShowActivity, width=40%]
The Show Command Activity Diagram describes the execution of the Show command. It considers
the result of every scenarios, command execution success or failure, that could happen during the process.
This diagram can help the reader to understand all the possible outcomes of this command execution.

image::ShowCommandSequenceDiagram.svg[alt=ShowSequence, width=40%]
The Show Command Sequence Diagram shows the interactions of all the classes objects with the ShowCommand object
during execution. Developers will be able to understand how does other class objects work with the ShowCommand
object when the user inputs a command.
