@startuml

!include ../style.puml

skinparam classBackgroundColor MODEL_COLOR

package "Transaction List" {
    class transaction1 as "__:Transaction__" {
        <color:#white>Name: "Pizza"
        <color:#white>Amount: - 20.5
        <color:#white>Date: 2020-02-02
        <color:#white>Category: "MISC"
        <color:#white>isRecurring: false
    }
}

show members
@enduml
