@startuml
!include ../style.puml
skinparam arrowThickness 1.1
skinparam arrowColor WORKOUT_COLOR
skinparam classBackgroundColor WORKOUT_COLOR_T1

Package "Workout" <<Rectangle>> {
Interface ReadOnlyWorkoutList <<Interface>>
Class UniqueWorkoutList
Class ModelManager
Class WorkoutList
Class FilteredWorkoutList
Class Workout
Class WorkoutName
Class Exercise
}

Class HiddenOutside #FFFFFF
HiddenOutside .down.> ReadOnlyWorkoutList
ModelManager -left-> WorkoutList
WorkoutList -left-|> ReadOnlyWorkoutList
WorkoutList *-down-> "1" UniqueWorkoutList
UniqueWorkoutList *-down-> "*" Workout
Workout *-down-> "1" WorkoutName
Workout *-down-> "*" Exercise
FilteredWorkoutList o-up-> "1" WorkoutList
@enduml
