= Delino - User Guide
:site-section: UserGuide
:toc:
:toc-title:
:toc-placement: preamble
:sectnums:
:imagesDir: images
:stylesDir: stylesheets
:xrefstyle: full
:experimental:
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
endif::[]
:repoURL: https://github.com/AY1920S2-CS2103T-W12-1/main

By: `CS2103T-W12-01`      Since: `Jan 2020`      Licence: `MIT`

== Introduction
This user guide provides in-depth documentation on the Delino desktop application:
quick start guide, features, FAQ, command summary, and glossary.

Delino is for couriers who *prefer to use a desktop app for managing their delivery tasks*.
It is *optimised for those who have a strong preference towards Command Line Interface* (CLI)
while still enjoying the benefits of a Graphical User Interface (GUI).
Sounds interesting? Have a quick look at our tutorial <<Quick Start>> to get started.
Have a delightful journey using Delino!

=== Product Information
Are you still using pen and papers or Excel to keep track of all your orders? +

With Delino, you can be rest assured that it will help you to keep track of a large number of orders in the most efficient way possible. Are you interested in improving your parcel delivery management? Read further to discover the features of Delino!


=== How to navigate this user guide
Throughout this user guide, you might encounter additional symbols. These symbols are used to
highlight important information. +
This user guide uses the following symbols:

[NOTE]
====
This block contains additional *notes*. +
It contains more information regarding complex content that you should take note of.
====

[TIP]
====
This block contains additional *tips*.
====

[WARNING]
====
This block contains *warning* information.
====

[IMPORTANT]
====
This block contains *important* inforamtion that you should be mindful of.
====

You will also encounter the use of `text markup` to indicate keywords such as
command arguments to Delino. (e.g. `exit`)

[WARNING]
====
For the various commands, you might encounter arguments in square brackets (e.g. `nearby` `[FLAG]` `AREA`).  +
These arguments are optional.
====

Finally, you will encounter links to external web pages for additional information.
These links will link:[look like this].

== Quick Start

.  Ensure you have Java `11` or above installed in your Computer.
.  Download the latest `Delino.jar` link:{repoURL}/releases[here].
.  Copy the file to the folder you want to use as the home folder for your Delino.
.  Double-click the file to start the app. The GUI should appear in a few seconds.
+
image::Delino.svg[width="790"]
+
.  Type the command in the command box and press kbd:[Enter] to execute it. +
e.g. typing *`help`* and pressing kbd:[Enter] will open the help window.
.  Some example commands you can try:

* <<list, `list`>> ` done` : lists all delivered orders and return orders.
* <<insert, `insert`>> `tid/1023456789` `n/Amos Cheong` `a/Blk 572 Hougang st 51 #11-37 S530572` `p/9001 0019` `dts/2020-03-10 1650` `w/Marsiling` `cod/$5` `c/Leave it at the riser type/glass` : adds an order where the receiver name is `Amos Cheong` into Delino.
* <<delete, `delete`>> `-o` `3` : deletes the 3rd delivery order shown in the current list
* <<exit, `exit`>> : exits the app

.  Refer to <<Features>> for a more detailed explanation of each command.

[[Features]]
== Features

====
*Command Format*

* Words in `UPPER_CASE` are the parameters to be supplied by the user e.g. in `insert n/CUSTOMER_NAME`, `CUSTOMER_NAME` is a parameter which can be used as `insert n/John Doe`.
* Items in square brackets are optional e.g `n/CUSTOMER_NAME [c/COMMENT]` can be used as `n/John Doe c/Leave the parcel outside` or as `n/John Doe`.
* Parameters can be in any order e.g. if the command specifies `n/CUSTOMER_NAME` `p/PHONE_NUMBER`, +
`p/PHONE_NUMBER` `n/CUSTOMER_NAME`  is also acceptable.
====

==== Examples

* `insert` `tid/92173754` `n/John Doe` `a/Blk 572 Hougang st 51 #10-33 S530572` `p/98766789` `e/johndoe@example.com` `dts/2020-02-20 1300` `w/Yishun` `cod/$4`

* `insert` `tid/1023456789` `n/Amos Cheong` `a/Blk 572 Hougang st 51 #11-37 S530572` `e/amoscheong@example.com` `p/9001 0019` `dts/2020-03-10 1650` `w/Marsiling` `cod/$5` `c/Leave it at the riser` `type/glass`

[[clear]]
=== Clearing all entries : `clear`

==== Description
* You can use this command to clear all existing orders. By default, the command will ask you for confirmation.
* If an `-f` flag is given, no user confirmation will be requested.

[NOTE]
====
* A space is required in between the command and flags. Refer to the  examples below for more information.
* If *no* `-o` or `-r` flag is given, it will be treated as both. *Both* order book and return order book will be cleared.
====

==== Format:
* `clear` `[FLAG]`

==== Examples
* `clear` +
   Popup will appear and ask the user for double confirm to clear both order and return order book.
* `clear` `-f` +
   Both order book and return order book will be cleared immediately.
* `clear` `-f` `-r` +
   Only return order book is cleared immediately.
* `clear` `-o` `-f` +
   Only order book is cleared immediately.

[[delete]]
=== Deleting an order : `delete`
==== Description
* You can use this command to delete a particular order or return order based on its index. +
 The item to be deleted is taken from the respective list of orders or return orders; depending on its type.

==== Format:
`delete` `FLAG` `INDEX`

****
* Deletes the order/return order at the specified `INDEX`.
* The `FLAG` determines the list which the item to be deleted is taken from.
* The `INDEX` refers to the `INDEX` number shown in the displayed order list.
* The `INDEX` *must be a positive integer* i.e. 1, 2, 3, ...
****

==== Examples:

* `list` +
`delete` `-o` `2` +
Deletes the 2nd order from the order list.
* `list` +
`delete` `-r` `3` +
Deletes the 3rd return order from the return order list.
* `search` `-o` `Betsy` +
`delete` `-o` `1` +
Deletes the 1st order in the results of the `search` command (search all orders with customer's name `Betsy`).
* `search` `-r` `Aaron` +
`delete` `-r` `1` +
Deletes the 1st order in the results of the `search` command (search all orders with customer's name `Aaron`).

[[delivered]]
=== Marks an order or return order as delivered: `delivered`
==== Description
* Once you have delivered a delivery order or a return order, you can mark it as delivered by providing the `FLAG` and `INDEX` of the order/return list.
* The delivery status of the orders or return orders will be changed from ‘Not Delivered’ to ‘Delivered’.
* The list of delivered orders or return orders can then be seen by calling the list command: `list` `done`.

==== Format
`delivered` `FLAG` `INDEX`

==== Examples
* `delivered` `-o` `1` +
The order at the first `INDEX` of the order list is marked as a delivered order.
* `delivered` `-r` `2` +
The return order at the second `INDEX` of the return order list is marked as a delivered order.

[[edit]]
=== Editing an order : `edit`

==== Description

* You can edit the details of the parcel by providing the following in order: +
** the `INDEX` of it +
** `FLAG` corresponding to the order type +
** field you want to change +
** new value to update to.

==== Format

[TIP]
====
* Use the <<list, `list`>> command to see which delivery order you want to edit.
* List of order attribute prefixes can be found <<command_prefix, here>>.
====

* `edit` `FLAG` `INDEX` `ORDER_ATTRIBUTE_PREFIX/NEW_VALUE` `[ORDER_ATTRIBUTE_PREFIXES/NEW_VALUE]...`

[WARNING]
====
* The `INDEX` *must be a positive integer*, e.g: 1, 2, 3, ...
* The `INDEX` *must be in range* of the number of displayed orders
* Only can be used when there is at least an order displayed.
* The `FLAG` can only be either `-o` or `-r`, please refer to <<command_flags, here>> for more information.
====


****
* Edits the parcel at the specified `INDEX`.
* Existing value that corresponds to the `PREFIX` will be updated to the input `NEW_VALUE`.
****

==== Examples

* `edit` `-r` `1` `n/Xuan En` +
The index `1` customer's name of the return order list will be changed to `Xuan En`.
* `edit` `-o` `2` `p/9999 4444` +
The index `2` customer's phone number of the order list will be changed changed to `9999 4444`.
* `edit` `-o` `1` `a/Blk 123 Pasir Ris Street 51 #12-21 S510123` +
The index `1` customer's address of the order list will be changed to `Blk 123 Pasir Ris Street 51 #12-21 S510123`.
* `edit` `-r` `3` `n/Mr Tan` `p/0123 4567` `a/Blk 141 Yishun st 71 #09-09 S760141` +
The index `3` customer's name, phone and address of the return order list will be changed accordingly to the prefix.

[[exit]]
=== Exiting the program : `exit`

==== Description
* You can exit the application using the exit command.

==== Format:
* `exit`

[[help]]
=== Viewing help : `help`

==== Description
* You can use the help command to display all commands that are available to be used so that you can navigate the application easily.

==== Format:
* `help`

==== Examples:
* `help` +
Returns a list of all commands available.

[[show]]
=== Showing statistics : `show` [Done by Amos Cheong Jit Hon]
This section will explain more about the Show command and how to use it.

At some point of time, you would want to know how many orders have you delivered or what is your earnings for today. Therefore,
you have to use the Show Command to view those information.
[[show-works]]
==== How to use the Show command
In this section, you will learn how to use the Show Command.

Here is how you can show the statistics of your orders: +

*Step 1* : Type : `show` +

*Step 2* : Press `Enter` on your keyboard to see the magic!

[NOTE]
====
The `show` command opens up a new window that displays the following information :

* Earnings Today
* Deliveries Made
* Deliveries Today (The number of delivery orders to make today)
* Orders Returned
* Returns Today (The number of return orders to make today)
* Total Orders Today (The total number of all the orders to make today)
====

[[show-examples]]
==== What constitutes a valid Show Command

This is the only syntax of the Show Command: `show`

[NOTE]
====
* No other keywords is allowed other than `show`
====

[[insert]]
=== Inserting an order: `insert` [Done by Amos Cheong Jit Hon]
This section shows you how to use the Insert Command and the relevant examples.

Whenever you have a new delivery order to make, you have to add it into your list of orders.
The Insert Command is in charge of this functionality.

[[insert-works]]
==== How to use the Insert Command
Here are the steps on using the Insert Command: +

*Step 1* : Type in the keyword *insert* +

*Step 2* : Add in the prefixes `<<command_prefix, TRANSACTION_ID>>` `<<command_prefix, CUSTOMER_NAME>>`
 `<<command_prefix, ADDRESS>>` `<<command_prefix, PHONE_NUMBER>>` `<<command_prefix, EMAIL>>`
 `<<command_prefix, ORDER_TIMESTAMP>>` `<<command_prefix, WAREHOUSE_LOCATION>>` `<<command_prefix, CASH_ON_DELIVERY>>`
of the delivery orders +

*Step 3* : Skip Step 4 if the specific order does not have the customer's comment and the type of item. +

*Step 4* : Add in the Customer comment and type of item using the prefixes `<<command_prefix, [COMMENT_BY_CUSTOMER]>>`
 `<<command_prefix, [TYPE_OF_ITEM]>>` +

*Step 5* : Press `Enter` on your keyboard to see the magic!

[[insert-examples]]
==== What constitutes a valid Insert command
Here is the syntax of the *Insert* Command : +
`insert` `tid/TRANSACTION_ID` `n/CUSTOMER_NAME` `a/ADDRESS` `p/PHONE_NUMBER` `e/EMAIL` `dts/DELIVERY_DATE_&_TIME` `w/WAREHOUSE_LOCATION` `cod/CASH_ON_DELIVERY` `[c/COMMENTS_BY_CUSTOMER]` `[type/TYPE_OF_ITEM]`

[NOTE]
====
* The `TRANSACTION_ID` refers to the transaction id of the order.
* The `CUSTOMER_NAME` refers to the name of the recipient of the order.
* The `ADDRESS` refers to the address of the recipient.
* The `PHONE_NUMBER` refers to the phone number of the recipient.
* The `EMAIL` refers to the email address of the recipient.
* The `DELIVERY_DATE_&_TIME` refers to the delivery date and time of the order.
* The `WAREHOUSE_LOCATION` refers to the warehouse that the courier should collect the order from.
* The `CASH_ON_DELIVERY` refers to the money earned from delivering the particular order.
* The `[COMMENTS_BY_CUSTOMER]` refers to the comment made by the recipient to the courier.
* The `[TYPE_OF_ITEM]` refers to the type of item that the courier is delivering.
* The prefixes `tid/TRANSACTION_ID` `n/CUSTOMER_NAME` `a/ADDRESS` `p/PHONE_NUMBER` `e/EMAIL` `dts/DELIVERY_DATE_&_TIME` `w/WAREHOUSE_LOCATION` `cod/CASH_ON_DELIVERY` are compulsory.
* The prefixes `c/COMMENTS_BY_CUSTOMER` `type/TYPE_OF_ITEM` are optional.
* Any compulsory prefixes that is absent will result in the App displaying an error message.
====

[WARNING]
====
* The Email provided must be a valid email address.
* Cash On Delivery must start with a dollar sign followed by the value.
* To add the Delivery Date and Time, first type in the date in this format : YYYY-MM-DD. Followed by adding the time
in 24 hour format.
* Type of Item must be alphanumeric (No numbers or special characters allowed).
====

There are two different scenarios on how to insert the orders :

.Possible combinations of Insert Command
|===
|Scenario |Command |Result

| Insert the order without a comment and no item type
| `insert` `tid/A094844` `n/John Doe` `a/Blk 505 Tampines #10-33 S469695` `p/98761111` `e/johndoe@example.com` `dts/2020-05-20 1300` `w/Yishun` `cod/$4`
| You should be able to see that the order with transaction id 'A094844' will be inserted into the list of delivery orders.

| Insert the order with all the order attributes including the non-compulsory ones
| `insert` `tid/C1023456789` `n/Amos Cheong` `a/Blk 572 Hougang st 51 #11-37 S530572` `e/amoscheong@example.com` `p/9001 0019` `dts/2020-05-10 1650` `w/Marsiling` `cod/$5` `c/Leave it at the riser` `type/glass`
| You should see that the order with transaction id 'C1023456789' is inserted into the list of delivery orders.

|===


[TIP]
====
* List of order attribute prefixes can be found <<command_prefix, here>>.
====

[[import]]
=== Importing a list of orders : `import`
==== Description
* You will be able to import orders and return orders via a csv file that are given to you by your company.
* The CSV file will include all relevant and important details of the parcels; such as the customers’ names,
transaction id of the parcels and the address of the customers, etc.

==== Format
* `import` `FILE_NAME`

[WARNING]
====
* Only csv file could be imported.
* Only *one* csv file can be imported at one time.
* The `FILE_NAME` should include the extension. For example: `*orders.csv*`.
* The folder, *data*, which the csv files are stored in, should be in the same directory as the JAR file.
* Import the specific csv with the `FILE_NAME` in *data* folder to the application.
====

* The data in the `csv file` should be written in the following format:

[format=csv]
.Order data format
|===
ot/ORDER_TYPE, tid/TRANSACTION_ID, n/NAME, a/ADDRESS, p/PHONE_NUMBER, e/EMAIL, dts/DELIVERY_DATE_&_TIME, w/WAREHOUSE_LOCATION, cod/CASH_ON_DELIVERY, [c/COMMENTS_BY_CUSTOMER], [type/TYPE_OF_ITEM]
|===
* Examples:
** `ot/order`,`tid/1023456789`,`n/Amos Cheong`,`a/Blk 572 Hougang st 51 #11-37 S530572`,`p/90010019`,
`e/amos@example.com`, `dts/2020-05-10 1650`,`w/Marsiling`,`cod/$9.50`,`c/Leave it at the riser`,`type/glass`

[format=csv]
.Return data format
|===
ot/ORDER_TYPE,tid/TRANSACTION_ID, n/NAME, a/ADDRESS, p/PHONE_NUMBER, e/EMAIL, rts/RETURN_DATE_&_TIME, w/WAREHOUSE_LOCATION, [c/COMMENTS_BY_CUSTOMER], [type/TYPE_OF_ITEM]
|===

* Examples:
** `ot/return`,`tid/b1230512`,`n/Aaron Teo`,`a/256 Alpha Road #03-22 S123567`,`p/91230456`, `e/aaron@example.com`, +
`rts/2020-05-10 1400`,`w/Jurong Warehouse`,`c/Leave it at the lobby`,`type/metal`

[NOTE]
====
* Commas `,` are required in between of the different fields.
* Prefixes are required before any value for that field.
* `ORDER_TYPE` can only be either `order` or `return`.
* Only `COMMENTS_BY_CUSTOMER` and `TYPE_OF_ITEM` are optional.
* `ORDER_TYPE` denote the start of an delivery order or return order.
* The last value of the same type will be stored if duplicate prefix type is found in a single order sentence.
* Duplicate and invalid order or return order will not be imported into Delino.
====

==== Examples

* `import` `orders.csv` +
Import the contents of the csv file, `orders.csv`, to Delino.

[[list]]
=== Listing orders : `list`  [Done by Amos Cheong Jit Hon]
In this section, you will learn more about the List command and how to use it.

As a courier, you would want to take a look at all the orders that you have in your list of orders regardless of the type of orders or the order status. The List Command will enable you to
view all these orders.
[[list-works]]
==== How does the List Command works

Here are the steps to execute the List command:

*Step 1* : Type in the keyword *list*. +

*Step 2* : If you want to simply see all your delivery and return orders.
Otherwise, please proceed to Step 3. Else, skip to Step 4 +

*Step 3* : Provide the following `[KEYWORD]` : `done` (Showing all your completed orders) or `undone` (Show all your
uncompleted orders) +

*Step 4* : Press `Enter` on your keyboard and see the magic!

[[list-examples]]
==== What constitutes a valid List command

The syntax of a valid `list` command is as shown:
`list` `[KEYWORD]`

There are three types of list commands that are shown in the examples below :

.Possible combinations of List Command

|===
|Scenario |Command |Result

| Display all orders
| `list`
| Show two lists of all orders. One list for delivery orders, the other for return orders

| Display all completed orders
| `list` `done`
| Show two lists of all completed orders. One list for delivery orders, the other for return orders


| Display all uncompleted orders
| `list` `undone`
| Show two lists of all uncompleted orders. One list for delivery orders, the other for return orders

|===

[IMPORTANT]
====
* `KEYWORD` can only be either `done` or `undone`.
====

[[nearby]]
=== View orders located at the same area or postal sector: `nearby`
==== Description
The `nearby` command can be used to search either the order list or return order list. +
You *may* give either a `-o` flag for viewing nearby orders in the order list
or a `-r` flag for viewing nearby orders in the returns list. +
By default, the `nearby` command will search both the order list and return order list.

There are two possible search criteria for the `nearby` command:

. By *postal sector*: +
Command Usage: `nearby` `[FLAG]` `POSTAL_SECTOR`


[NOTE]
====
A `POSTAL_SECTOR` refers to the first *two* digits of a six digit Singapore postal code. +
A `FLAG` refers to either `-o` or `-r` and is *optional*. +
A `-o` flag is used to indicate searching on the order list. +
A `-r` flag is used to indicate searching on the return order list.
====
* You can view the orders at a specified Singapore *postal sector*.
* The general location for the order will be identified if a valid postal sector is given.
* The list of postal sectors and their corresponding general locations can be found
https://www.ura.gov.sg/realEstateIIWeb/resources/misc/list_of_postal_districts.htm[here].

.Postal Sectors in Singapore
|===
|Postal Sector |General Location

|01, 02, 03, 04, 05, 06 |Raffles Place, Cecil, Marina, People's Park
|07, 08 |Anson, Tanjong Pagar
|14, 15, 16 |Queenstown, Tiong Bahru
|09, 10 |Telok Blangah, Harbourfront
|11, 12, 13 |Pasir Panjang, Hong Leong Garden, Clementi New Town
|17 |High Street, Beach Road (part)
|18, 19 |Middle Road, Golden Mile
|20, 21 |Little India
|22, 23 |Orchard, Cairnhill, River Valley
|24, 25, 26, 27 |Ardmore, Bukit Timah, Holland Road, Tanglin
|28, 29, 30 |Watten Estate, Novena, Thomson
|31, 32, 33 |Balestier, Toa Payoh, Serangoon
|34, 35, 36, 37 |Macpherson, Braddell
|38, 39, 40, 41 |Geylang, Eunos
|42, 43, 44, 45 |Katong, Joo Chiat, Amber Road
|46, 47, 48 |Bedok, Upper East Coast, Eastwood, Kew Drive
|49, 50, 81 |Loyang, Changi
|51, 52 |Tampines, Pasir Ris
|53, 54, 55, 82 |Serangoon Garden, Hougang, Punggol
|56, 57 |Bishan, Ang Mo Kio
|58, 59 |Upper Bukit Timah, Clementi Park, Ulu Pandan
|60, 61, 62, 63, 64 |Jurong
|65, 66, 67, 68 |Hillview, Dairy Farm, Bukit Panjang, Choa Chu Kang
|69, 70, 71 |Lim Chu Kang, Tengah
|72, 73 |Kranji, Woodgrove
|77, 78 |Upper Thomson, Springleaf
|75, 76 |Yishun, Sembawang
|79, 80 |Seletar
|===


[start=2]
. By *area*: +
Command Usage: `nearby` `[FLAG]` `AREA`

[NOTE]
====
An *area* refers to one of the five areas of Singapore +

. Central
. East
. North East
. West
. North

A quick reference for the five areas of Singapore can be <<area_table, found here>>

A `FLAG` refers to either `-o` or `-r` and is *optional*. +
A `-o` flag is used to indicate searching on the order list. +
A `-r` flag is used to indicate searching on the return order list.
====
* You can view all the orders located at a specified *area*.

You can obtain more detailed information about each area from
https://keylocation.sg/singapore/districts-map[this website]


==== Format
. `nearby` `[FLAG]` `POSTAL_SECTOR` +

[IMPORTANT]
====
`POSTAL_SECTOR` is the first *two* digits of a six digit Singapore postal code +
Example: The postal code `140239` has a `POSTAL_SECTOR` of `14`

A `FLAG` refers to either `-o` or `-r` and is *optional*. +
A `-o` flag is used to indicate searching on the order list. +
A `-r` flag is used to indicate searching on the return order list.
====

[start=2]
. `nearby` `FLAG` `AREA`

==== Examples
* `nearby` `-o` `14` +
You will view all orders in the order list located in the general location of `Queenstown, Tiong Bahru`.
* `nearby` `-r` `04` +
You will view all return orders located in the general location of `Raffles Place, Cecil, Marina, People's Park`.
* `nearby` `north` +
You will view all orders in the order list and return order list located in the north area of Singapore.

[[return]]
=== Returning an order: `return`

==== Description
* If the order to be returned is an existing order in the list, you may convert it into a return order by typing `return` `TRANSACTION_ID` of the order. This will remove it from the list of orders and add it into the return order list.
* If the parcel to be returned is not an existing order in the list, you can create a new return order by typing `return` `tid/TRANSACTION_ID` `n/CUSTOMER_NAME` `a/ADDRESS` `p/PHONE NUMBER` `rts/RETURN_DATE_&_TIME` `w/WAREHOUSE_LOCATION` `[c/COMMENTS_BY_CUSTOMER]` `[type/TYPE_OF_ITEM]` of the parcel. This will create a new return order and add it into the return order list.

==== Format
* `return` `tid/TRANSACTION_ID` `n/CUSTOMER_NAME` `a/ADDRESS` `p/PHONE NUMBER` `rts/RETURN_DATE_&_TIME` `w/WAREHOUSE_LOCATION` `[c/COMMENTS_BY_CUSTOMER]` `[type/TYPE_OF_ITEM]`
* `return` `tid/TRANSACTION_ID`


[TIP]
====
* List of order attribute prefixes can be found <<command_prefix, here>>.
====

==== Examples
* `return` `tid/ac17s2a` `n/Bobby Tan` `a/123 Delta Road #03-333, Singapore 123456` `p/91230456` `e/bobby@example.com`
`rts/12-12-2020 1300` `w/Jurong Warehouse` `c/NIL` `type/glass` +
Creates and adds an order with `TRANSACTION_ID` 'ac17s2a' as a return order into the list of return orders.
* `return` `tid/ac17s2a` +
Converts the order with `TRANSACTION_ID` 'ac17s2a' into a return order and adds it into the list of returns.
* `return` `tid/b1230512` `n/Aaron Teo` `a/256 Alpha Road #03-222, Singapore 123567` `p/91230456` `e/aaron@example.com` `rts/12-12-2020 1400` `w/Jurong Warehouse` `c/Leave it at the lobby` `type/metal` +
Creates and adds an order with `TRANSACTION ID` 'b1230512' as a return order into the list of return orders.


[[search]]
=== Locating orders by order fields: `search`

==== Description

* You can search all orders that contain a given keyword.
* By default, `search` finds all parcels (orders and return orders) that contain the given keyword(s) in any of it's field.
* Specific search can be performed by tagging keywords that you want to search for with the corresponding <<command_prefix,`ORDER_ATTRIBUTE_PREFIX`>>.
* You can also specify which type of parcel you want to specifically search for by providing a <<command_flags, flag>>.

==== Format
* `search` `<<command_flags, [FLAG]>>` `KEYWORD` `[MORE_KEYWORDS]...` OR
* `search` `<<command_flags, [FLAG]>>` `<<command_prefix, ORDER_ATTRIBUTE_PREFIX>>/KEYWORD` `[MORE_KEYWORDS]...` `[<<command_prefix, ORDER_ATTRIBUTE_PREFIX>>/KEYWORD MORE_KEYWORDS]...`

****
* The search is case insensitive. e.g `hans` will match `Hans`
* The sequence of the keywords does not matter. e.g. `Hans Bo` will match `Bo Hans`
* Only full words will be matched e.g. `Han` will not match `Hans`
* Orders matching at least one keyword will be returned (i.e. `OR` search). e.g. `Hans Bo` will return `Hans Gruber`, `Bo Yang`
****

==== Examples
* `search` `-r` `Jeremy Loh` +
Return return order(s) containing keyword of `jeremy`, `Jeremy Loh` or `loh` or any of the above as long as it appears in any of the orders field.
* `search` `-o` `tid/asj2od3943` +
Return order(s) with transaction ID of `asj2od3943`
* `search` `-r` `p/92039999` +
Return return order(s) with phone number of `92039999`
* `search` `-o` `p/92039999` `tid/asj2od3943` `n/jeremy` +
Return order(s) with either phone number of `92039999` or transaction ID of `asj2od3943` or name of `jeremy` or any of the above combinations.


=== Saving the data
==== Description
* Data is saved in the hard disk automatically after any command that changes data that is present.
* There is no need to save manually.

=== Export order list `[coming in v2.0]`
_{explain how the user can export their order list as csv file to pass the orders to their colleagues}_

=== Reminder `[coming in v2.0]`
_{explain how the user can set reminder specifically for orders that are rescheduled or urgent orders}_

=== Rescheduling orders `[coming in v2.0]`
_{explain how the user can reschedule their orders when customers notify them that they are unavailable for receiving orders}_

=== Keeping track of work schedule `[coming in v2.0]`
_{explain how the user can keep track of their work schedule}_

=== Statistics for completed orders `[coming in v2.0]`
_{explain how the user can view statistics such as on-time rates (difference between actual and expected
delivery), number of deliveries completed in a day}_

== FAQ
*Q*: How do I transfer my data to another Computer? +
*A*: Install the app in the other computer and overwrite the empty data file it creates with the file that contains the data of your previous Address Book folder.


== Command Summary

* <<insert, *Insert*>> : `insert` `tid/TRANSACTION_ID` `n/CUSTOMER_NAME` `a/ADDRESS` `p/PHONE_NUMBER` `e/EMAIL` `dts/DELIVERY_DATE_&_TIME` `w/WAREHOUSE_LOCATION` `cod/CASH_ON_DELIVERY` `[c/COMMENTS_BY_CUSTOMER]` `[type/TYPE_OF_ITEM]` +
e.g. `insert` `tid/0123456789` `n/Eng Xuan En` `a/Tampines St 84 Blk 877 S520877 #01-123` `p/87654321` `e/xuanen@example.com` `dts/2020-02-20 1300` `w/Yishun industry` `cod/$4.50` `c/please knock the door three times :D` `type/heavy`
* <<clear, *Clear*>> : `clear` `[FLAG]` +
e.g. `clear` `-f`
* <<delete, *Delete*>> : `delete` `FLAG` `INDEX` +
e.g. `delete` `-o` `2`
* <<delivered, *Delivered*>> : `delivered` `FLAG` `INDEX` +
e.g. `delivered` `-r` `2`
<<edit, *Edit*>> : `edit` `FLAG` `INDEX` `ORDER_ATTRIBUTE_PREFIX/VALUE` +
e.g. `edit` `-r` `2` `n/Xuan En`
* <<exit, *Exit*>> : `exit`
<<search, *Search*>> : `search` `<<command_flags, [FLAG]>>` `<<command_prefix, ORDER_ATTRIBUTE_PREFIX>>/KEYWORD` `[MORE_KEYWORDS]...` `[<<command_prefix, ORDER_ATTRIBUTE_PREFIX>>/KEYWORD MORE_KEYWORDS]...`  +
 e.g. `search` `-r` `tid/ac1e345x7s`
* <<help, *Help*>> : `help`
* <<show, *Show*>> : `show`
* <<import, *Import*>> : `import` `FILE_NAME` +
e.g. `import` `orders.csv`
* <<list, *List*>> : `list` `[DONE_STATUS]` +
e.g. `list` `done`
* <<return, *Return*>> : `return` `tid/TRANSACTION_ID` `n/CUSTOMER_NAME` `a/ADDRESS` `p/PHONE_NUMBER` `e/EMAIL` `rts/RETURN_DATE_&_TIME` `w/WAREHOUSE_LOCATION` `c/COMMENTS_BY_CUSTOMER` `type/TYPE_OF_ITEM` +
e.g. `return` `tid/ac17s2a` `n/BOBBY TAN` `a/123 Delta Road #03-333, Singapore 123456` `p/91230456` `rts/12-12-2020 1301` `w/Jurong Warehouse` `c/NIL` `type/glass`
* <<return, *Return*>> : `return` `tid/TRANSACTION_ID` +
e.g. `return` `tid/ac17s2a`
* <<nearby, *Nearby*>> : `nearby` `[FLAG]` `POSTAL_SECTOR` or `nearby` `[FLAG]` `AREA` +
e.g. `nearby` `-o` `14` +
e.g. `nearby` `-r` `north` +
e.g. `nearby` `east`

== Appendix A: Glossary

[[command_prefix]]
.Command Prefix
|===
|Prefix |Meaning |Used in the following Command(s)

|ot/
|Order Type
|<<import, Import>>

|tid/
|Transaction ID
|<<edit, Edit>>, <<insert, Insert>>, <<return, Return>>, <<search, Search>>, <<import, Import>>

|n/
|Customer Name
|<<edit, Edit>>, <<insert, Insert>>, <<return, Return>>, <<search, Search>>, <<import, Import>>

|a/
|Address
|<<edit, Edit>>, <<insert, Insert>>, <<return, Return>>, <<search, Search>>, <<import, Import>>

|p/
|Phone Number
|<<edit, Edit>>, <<insert, Insert>>, <<return, Return>>, <<search, Search>>, <<import, Import>>

|e/
|Email
|<<insert, Insert>>, <<edit, Edit>>, <<return, Return>>, <<search, Search>>, <<import, Import>>

|dts/
|Delivery Date And Time
|<<edit, Edit>>, <<insert, Insert>>, <<return, Return>>, <<search, Search>>, <<import, Import>>

|rts/
|Return Date and Time
|<<return, Return>>, <<search, Search>>, <<import, Import>>

|w/
|Warehouse Location
|<<edit, Edit>>, <<insert, Insert>>, <<return, Return>>, <<search, Search>>, <<import, Import>>

|cod/
|Cash On Delivery
|<<edit, Edit>>, <<insert, Insert>>, <<search, Search>>, <<import, Import>>

|c/
|Comments by Customer
|<<edit, Edit>>, <<insert, Insert>>, <<return, Return>>, <<search, Search>>, <<import, Import>>

|type/
|Type of Item
|<<edit, Edit>>, <<insert, Insert>>, <<return, Return>>, <<search, Search>>, <<import, Import>>
|===

[[command_flags]]
.Possible Command Flags
|===
|Flag |Meaning |Used in the following Command(s)

|-f
|Force clear, no user confirmation will be requested
|<<clear, Clear>>

|-o
|Order flag, Operation on order list
|<<clear, Clear>>, <<nearby, Nearby>>, <<delivered, Delivered>>, <<search, Search>>, <<edit, Edit>>

|-r
|Return Order flag, Operation on return order list
|<<clear, Clear>>, <<nearby, Nearby>>, <<delivered, Delivered>>, <<search, Search>>, <<edit, Edit>>
|===

[[area_table]]
=== Area Information of Singapore

<<nearby, Click here>> to navigate back to the Nearby Command!

.Central
|===
|District |Areas |Location

|1 |Marina Area
a|
* Boat Quay
* Chinatown
* Havelock Road
* Marina Square
* Raffles Place
* Suntec City

|2 |CBD
a|
* Anson Road
* Chinatown
* Neil Road
* Raffles Place
* Shenton Way
* Tanjong Pagar

|3 |Central South
a|
* Alexandra Road
* Tiong Bahru
* Queenstown

|4 |Keppel
a|
* Keppel
* Mount Faber
* Sentosa
* Telok Blangah

|5 |South West
a|
* Buona Vista
* Dover
* Pasir Panjang
* West Coast

|6 |City Hall
a|
* City Hall
* High Street
* North Bridge Road

|7 |Beach Road
a|
* Beach Road
* Bencoolen Road
* Bugis
* Rochor

|8 |Little India
a|
* Little India
* Farrer Park
* Serangoon Road

|9 |Orchard
a|
* Cairnhill
* Killiney
* Leonie Hill
* Orchard
* Oxley

|10 |Tanglin
a|
* Balmoral
* Bukit Timah
* Grange Road
* Holland
* Orchard Boulevard
* River Valley
* Tanglin Road

|11 |Newton
a|
* Chancery
* Bukit Timah
* Dunearn Road
* Newton

|12 |Toa Payoh
a|
* Balestier
* Moulmein
* Novena
* Toa Payoh

|13 |Central East
a|
* Potong Pasir
* Macpherson

|14 |Eunos
a|
* Eunos
* Geylang
* Kembangan
* Paya Lebar

|15 |East Coast
a|
* Katong
* Marine Parade
* Siglap
* Tanjong Rhu

|21 |Central West
a|
* Clementi
* Upper Bukit Timah
* Hume Avenue
|===

.East +
|===
|District |Areas |Location

|16 |Upper East Coast
a|
* Bayshore
* Bedok
* Chai Chee

|17 |Far East
a|
* Changi
* Loyang
* Pasir Ris

|18 |Tampines
a|
* Pasir Ris
* Simei
* Tampines
|===

.North East
|===
|District |Areas |Location

|19 |North East
a|
* Hougang
* Punggol
* Sengkang

|20 |Ang Mo Kio
a|
* Ang Mo Kio
* Bishan
* Braddell Road
* Thomson

|28 |North East
a|
* Seletar
* Yio Chu Kang
|===

.West
|===
|District |Areas |Location

|22 |Far West
a|
* Boon Lay
* Jurong
* Tuas

|23 |North West
a|
* Bukit Batok
* Choa Chu Kang
* Hillview Avenue
* Upper Bukit Timah

|24 |Far North West
a|
* Kranji
* Lim Chu Kang
* Sungei Gedong
* Tengah
|===

.North
|===
|District |Areas |Location

|25 |Far North
a|
* Admiralty
* Woodlands

|26 |North
a|
* Tagore
* Yio Chu Kang

|27 |Far North
a|
* Admiralty
* Sembawang
* Yishun
|===

