= CodeCampX - User Guide
:site-section: UserGuide
:toc:
:toc-title:
:toc-placement: preamble
:sectnums:
:imagesDir: images
:stylesDir: stylesheets
:xrefstyle: full
:experimental:
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
endif::[]
:repoURL: https://github.com/se-edu/addressbook-level3

By: `Team SE-EDU`      Since: `Jun 2016`      Licence: `MIT`

== Introduction

Code Camp X (CCX) is for those who *prefer to use a desktop app to manage the administrative tasks of running a coding camp*.
More importantly, CCX is *optimized for those who prefer to work with a Command Line Interface* (CLI) while still having the benefits of a Graphical User Interface (GUI).
If you can type fast, CCX can allow you to manage your camp's administrative tasks faster than traditional GUI apps.
Interested? Jump to the <<Quick Start>> to get started. Enjoy!

. Define a very specific _target user profile_.

Coding bootcamp
(Reasonable to assume that officers are educated enough to prefer typing)

. Define a clear _value proposition_ that matches the target user profile i.e., what problem does the product solve? How does it make the the user's life easier?
* *[Staff Management]* Helps the owner to schedule teachers
* *[Student Management]* Helps the owner to keep track of students progress
* *[Finances Management]* Helps the owner to track finances (profits and expenses)
* *[Courses Management]* Schedule courses

Hierarchy: Owner -> Admin Staff-> Teachers -> Students -> Progress +
Each owner has a few teachers, each admin staff takes care of a few teachers, each teachers has a few students, each students has a progress

. Optimize the product to the chosen target users i.e., add features that are especially/only applicable for target users (to make the app especially attractive to them).
Sheng Xue: I will try to organise in terms of when the feature should be done. I.e For each of the 4 functions, those on top should be done early, and those on the bottom will be done later. +
*[Staff Management]* +
*[Must-have] [Week 7]* +
As an owner, I want to be able to add and delete teachers, so I can hire and fire teachers.

*[Must-have] [Week 7]* +
As a user, I want to be able to promote or fire my teachers in the system.

*[Must-have] [Week 8]* +
As a user, I want to be able to edit the details of the teachers such as their incomes, so that their incomes will be automatically deducted from the finances of the tuition centre (STAFF>FINANCE)

*[Must-have] [Week 9]* +
As a user, I can specify the availability of the teachers, so that I can easily assign available teachers to teach specific courses. (STAFF -> COURSES)

*[Must-have] [Week 10]* +
As a user, I can specify the skill levels and the courses that the teachers can teach.

=== Adding a homework: `add homework`

Adds a homework to the list of homework +
Format: `add homework n/NAME d/DEADLINE`


* `add n/Function Programming Assignment d/2020-01-30`

=== Listing all homework : `list homework`

Shows a list of all homework. +
Format: `list homework`

=== Listing all homework for a course: `list homework`

Shows a list of all homework assigned to a course. +
Format: `list homework c/courseID`

Examples:

* `list homework c/001'

=== Editing a homework : `edit homework`

Edits an existing person in the address book. +
Format: `edit homework HOMEWORKID [n/NAME] [d/DEADLINE]`

****
* Edits the homework with the specified `HOMEWORKID'. The homeworkID *must exists* in the list of homework.
* At least one of the optional fields must be provided.
* Existing values will be updated to the input values.
****

* `edit 001 n/Machine Learning Assignment e/2020-02-30` +
Edits the name and deadline of the homework with ID of 001 to be `Machine Learning Assignment` and `2020-02-30` respectively.

=== Locating homework by KEYWORD/ID/DEADLINE: `find homework`

Finds homework with the any of the given keywords/ID/deadline +
Format: `find homework [k/KEYWORDS] [id/HOMEWORKID] [d/DEADLINE]

****
* The search is case insensitive. e.g `hans` will match `Hans`
* Only the name is searched.
* Only full words will be matched e.g. `Han` will not match `Hans`
* Only 1 of the parameters can be present
* HOMEWORKID must be valid.
* DEADLINE must be properly formatted
****
-update
* `find k/Machine` +
Returns any homework with `Machine` in its name such as - `Machine Learning Assignment`, `Reinforcement Learning Assignment`
* `find d/2020-01-30` +
Returns any homework with a deadline of `2020-01-30`