= FitBiz - User Guide
:site-section: UserGuide
:toc:
:toc-title:
:toc-placement: preamble
:sectnums:
:imagesDir: images
:stylesDir: stylesheets
:xrefstyle: full
:experimental:
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
endif::[]
:repoURL: https://github.com/AY1920S2-CS2103T-F11-2/main

By: `CS2103T-F11-2` Since: `Feb 2020` Licence: `MIT`

== Overview

=== About FitBiz

FitBiz is a business management tool tailor made for fitness coaches to manage their clients. From managing your client's profile to planning your schedules, FitBiz will surely ease the pain and monotony of managing a small to medium client portfolio.

This program is primarily a desktop application and optimised for those who prefer to work with a Command Line Interface (CLI). If you can type fast, and have clients to train and manage, FitBiz is definitely for you!

=== About this User Guide

This User Guide explains how to use the FitBiz CLI, as well as provides an understanding of the features and commands and some common use cases.

In this guide, we cover:

* Syntax of the commands available in FitBiz
* Common use cases for each command

=== Miscellaneous Features

As this is primarily a CLI based application, some features are included to make the user experience better. The following features are provided to simplify the use of FitBiz:

* Command History: similar to most modern CLIs, users can press the kbd:[Up] and kbd:[Down] arrow key to cycle through their previously entered commands. This history is persisted in the storage, allowing users to quickly reference what they have entered in a previous usage of this app.
* Command Auto Completion: again, similar to most modern CLIs, users can press the kbd:[Tab] key to auto complete the commands that they have partially typed. If the partially typed letters begin a string that uniquely identifies a command, the complete command name appears. Otherwise, a list of all commands similar to the ambiguous letters will appear.

== Quick Start

. Ensure you have Java 11 or above installed in your Computer
. Download the latest `FitBiz.jar` link:{repoURL}/releases[here]
. Copy the file to the folder you want to use as the home folder for your Fitness Manager
. Double-click the file to start the app. The GUI should appear in a few seconds
. Type the command in the command box and press kbd:[Enter] to execute it. e.g. typing `help` and pressing kbd:[Enter] will open the help window.
. Some example commands you can try:
* `list-c` : lists all clients
* `add-c n/John Doe g/Male p/98765432 e/johnd@example.com a/John street, block 123, #01-01 b/24-12-1997 h/170 cw/70 tw/75`
: adds a client named John Doe to FitBiz
* `exit` : exits the app
. Refer to <<Commands>> below for details of each command

== Commands

This section introduces the syntax and the usages of the commands available in FitBiz. In explaining the syntax, we will adhere to the following format:

* Words in `UPPER_SNAKE_CASE` are the parameters to be supplied by the user
** e.g. in `add-c n/NAME`, `NAME` is a parameter which can be used as `add-c n/John Doe`
* Items in square brackets are optional
** e.g. `n/NAME [t/TAG]` can be used as `n/John Doe t/friend` or as `n/John Doe`
* Items with `…` after them can be used multiple times including zero times
** e.g. `[t/TAG]…` can be used as (i.e. 0 times), `t/friend`, `t/friend t/family` etc.
* Parameters can be in any order
** e.g. if the command specifies `n/NAME p/PHONE_NUMBER`, `p/PHONE_NUMBER n/NAME` is also acceptable

=== View help: `help`

Opens a window with the link to the User Guide. `Currently in v1.3`
Lists all available commands and a short description of what they do. Specify the command for more detailed explanation. `Coming in v1.4`

Format: `help [c/COMMAND]`

Examples:

* `help`
** Lists all commands
* `help add-c`
** Shows a detailed explanation of the `add-c` command

=== List all clients: `list-c`

Shows all clients currently entered in this program.

* Note that this is the default view when you first launch FitBiz

Format: `list-c`

=== Find clients by name: `find-c` --- Yong Jie
`find-c` allows you to find clients with the names that are specified in your input. You might have many clients and finding a particular client by scrolling through the entire list might be troublesome and difficult. `find-c` is the command for you.

==== Parameters
This section acts as a summary of the important things to note when using `find-c` including their parameters.

Format: `find-c NAME`

[options='header']
[cols="15%,85%"]
|====================
| Parameters | Important points to note
| NAME |
* Substitute `NAME` with keywords you want to search with +

* You can use multiple keywords for `NAME`. +
e.g. You can enter `find-c bryan low`.

* The `NAME` keywords are case insensitive. +
e.g. Typing `find-c hans` will show clients even with the name `Hans`. +
For a better understanding, you can refer to the example section .

* The keywords used for `NAME` have to match at least one word in the name of the clients. +
e.g. Typing `find-c Bry` will not show clients with the name `Bryan`. +
For a detailed explanation, you can refer to the commons errors / problems section.

* Clients matching at least one `NAME` keyword will be returned and does not require all the words in their name to match. +
e.g. Typing `find-c Hans Bo` will show clients `Hans Gruber` and `Bo Yang` and not necessarily just client `Hans Bo`. +
For a detailed explanation, you can refer to the commons errors / problems section.
|====================

==== Example
Let's say that you want to find a client named "Bryan Low" in client list. You can simply use the `find-c` command as shown.

1.Type `find-c bryan` into the command box, and press `Enter` to execute it.

/photo

2.The result box will display the message of the number of clients listed. In this case, there are 2 clients with "bryan" in their name.

/photo

3.You can now see the clients with "bryan" in their names. As you can see, the name you use to search does not need to be case-senstive.

/photo

==== Common errors / problems
You might face some errors or difficulties when you `find-c`. In this section, you will be able to understand these errors and resolve them. You will also get a better understanding of the reply from the result box when using `find-c`.

===== Using incomplete names
You might wonder why `find-c` do not show the clients even though the client is in clearly in your client list. It might be possible that you have entered an incomplete name and does not match any word in the name of that client. The example below might help you understand better.

Example:
You want to find the client named "Bryan" in client list. Below shows that "Bryan" indeed exists in the client list.

/photo

Type `find-c bry" into the command box, and press `Enter` to execute it.

/photo

You will obtain "no clients listed!".

/photo

This is because the name that you have entered is incomplete and does not match any word in the name of any of the clients. To correct this, you have to enter `find-c bryan`.

/photo

===== Using multiple keywords for `NAME`

You might wonder why the application shows more clients than you intended. It might be possible that you have misunderstood how the `NAME` parameter gets the client you are finding. The application will show clients as long as one of the words of the client match a keyword you use for name. The example below might help you understand better.

Example:
You want to find the client named "Bryan Low" in client list.

Type `find-c bryan low` in to the command box, and press `Enter` to execute it.

/photo

You will obtain clients which have `bryan` in their name or `low` in the name. In the case below, there are 3 clients. `Bryan Low`, `Bryan Tan` and `Alice Low`.

/photo

You can try to enter keywords for `NAME` that are more specific to the client you are looking for. This will help to keep your search more scoped.

=== Add a new client profile: `add-c`

Initialises and adds a new client profile.

Format: `add-c n/NAME p/PHONE_NUMBER e/EMAIL a/ADDRESS [g/GENDER] [h/HEIGHT] [cw/CURRENT_WEIGHT] [tw/TARGET_WEIGHT] [r/REMARK] [s/SPORT]… [t/TAG]…`

* `n/NAME` is case insensitive. e.g `hans` will match `Hans`
* The order of words will matter. e.g `Hans Ong` will not match `Ong Hans`
* Only exact match will be shown. e.g. `Hans` will not match `Hans Ong`
* A client can have any number of tags (including 0)

Examples:

* `add-c n/Ming Liang p/98765432 e/johnd@example.com a/John street, block 123, #01-01`
** Adds a new client: Ming Liang with the above information
* `add-c n/Low Tah Kiow, John t/powerlifter e/betsycrowe@example.com a/some street p/1234567 t/strongman`
** Adds a new client: Low Tah Kiow, John with the above information

=== Edit a client’s profile: `edit-c`

Edits the client’s cliental details by specifying the attribute and the new value.

Format: `edit-c INDEX [n/NAME] [p/PHONE] [e/EMAIL] [a/ADDRESS] [g/GENDER] [h/HEIGHT] [cw/CURRENT_WEIGHT] [tw/TARGET_WEIGHT] [r/REMARK] [s/SPORT]… [t/TAG]...`

* `INDEX` refers to the index number shown in the displayed client list
* `INDEX` must be a positive integer (ie. 1, 2, 3, ...)
* At least one of the optional fields must be provided
* When editing tags, the existing tags of the client will be removed i.e adding of tags is not cumulative
* You can remove all the client’s tags by typing `t/` without specifying any tags after it

Examples:

* `edit-c 1 n/Ming Liang a/60 a/male`
** Edits the name of the 1st client to Ming Liang, age to 60, and gender to male.

=== Delete a client: `delete-c`

Deletes the client at the specified index from the program.

Format: `delete-c INDEX`

* `INDEX` refers to the index number shown in the displayed client list
* `INDEX` must be a positive integer (ie. 1, 2, 3, ...)

Examples:

* `delete-c 4`
** Deletes the 4th client from the program

=== View a client profile: `view-c`

Shows all available information of the client at the specified index. This also displays all the exercises recorded for the client as well as their personal bests for said exercises.

Format: `view-c INDEX`

* `INDEX` refers to the index number shown in the displayed client list
* `INDEX` must be a positive integer (ie. 1, 2, 3, ...)

Examples:

* `view-c 3`
** Shows all information about the 3rd client
* `view-c 45`
** Shows all information about the 45th client

=== Add a client's exercise: `add-e`  --- YongJie
`add-e` allows you to record an exercise done by the client that you are currently viewing. You will be able to see the exercises recorded and their information in a table.

==== Parameters
This section acts as a summary of the important things to note when using `add-e` including their parameters. The square bracket shows that it is optional and your command will still execute even if you do not enter them.

Format: `add-e n/EXERCISE_NAME d/DATE [ew/EXERCISE_WEIGHT] [reps/REPS] [sets/SETS]`

[options='header']
[cols="15%,85%"]
|====================
| Parameters | Important points to note
| n/NAME |
* Substitute `NAME` with the name of the exercise. +

* `n/NAME` is compulsory and you have to specify it. +

* `n/NAME` is case sensitive. +
e.g. An exercise named `pushup` will be considered to have a different name as an exercise named `Pushup`.

| d/DATE |
* Substitute `DATE` with the date of the exercise. +

* `d/DATE` is compulsory and you have to specify it. +

* `DATE` must be of the form `DD-MM-YYYY` (ie. 02-07-2020 for 2nd July 2020)

| [reps/REPS] |
* Substitute `REPS` with the reps of the exercise. +

* `reps/REPS` is optional..

* Range for `REPS` is 1-9999. +

| [sets/SETS] |
* Substitute `SETS` with the sets of the exercise. +

* `sets/SETS` is optional.

* Range for `SETS` is 1-9999. +

| [ew/WEIGHT] |
* Substitute `Weight` with the weight of the exercise. +

* `ew/WEIGHT` is optional.

* Range for `WEIGHT` is 1-9999. +
|====================

==== Example
Let's say that you want to add an exercise with the following details: +
Name: Bench Press +
Date: 12-02-2020 +
Reps: 4 +
Weight: 100 +
Sets: 4 +
You can use the `add-e` command to add the exercise as shown.

1.View the client that you want to add the exercise to. For information on how to view the client, you can refer to the section `...:view-c`. For this example, we will add the exercise to the first client in the list, `Alex Yeoh`. After you entered `view-c 1`, you will see `Alex Yeoh` detailed information and a table of his recorded exercises.

/photo

2.Now enter the information of the exercise, matching each detail of the exercise to the parameter. In this case, you will have to type `add-e n/Bench press d/12-02-2020 reps/4 ew/100 sets/4` into the command box. To recap,

[width="50%"]
|============
The name of the exercise after `n/` +
The date of the exercise after `d/` +
The reps of the exercise after `reps/` +
The weight of the exercise after `ew/` +
The sets of the exercise after `sets/` +
|============

Press enter to execute it.

/photo

3.After it has been successfully entered, the result box will display the recorded exercise.

/photo

4.You will also be able to see the recorded exercise in the table.

/photo

==== Common errors / problems
You might face some errors or difficulties when you `add-e`. In this section, you will be able to understand these errors and resolve them.

===== Duplicate exercises
You might wonder where the application shows you a duplicate exercise error when the details of the exercises you entered are different. It is likely that only the sets differ between the two exercises. The example below might help you understand better.

You might have the following exercise in your table.

/photo

If you were to enter `....` into the command box, the only information that is different is the number of sets. The result box will show that you have a duplicate exercise.

/photo type

/photo error

To solve this, we suggest incrementing the sets of existing exercise by using the `edit-e` command. This will help to keep your exercises consolidated and the table compact. For information on using `edit-e`, you may want to refer to the next section `Edit a client's exercise: edit-e`.

=== Edit a client's exercise: `edit-e` --- YongJie
`edits-e` allows edit an existing exercise done by the client that you are currently viewing. You will be able to see the updated exercise in the client's exercise table.

==== Parameters
This section acts as a summary of the important things to note when using `edit-e` including their parameters. The square bracket shows that it is optional and your command will still execute even if you do not enter them. However, at least one of them have to be specified.

Format: `edit-e INDEX [n/EXERCISE_NAME] [d/DATE] [ew/EXERCISE_WEIGHT] [reps/REPS] [sets/SETS]`

[options='header']
[cols="15%,85%"]
|====================
| Parameters | Important points to note
| INDEX |
* Substitute `INDEX` with the index of the exercise shown on the table. +

* `INDEX` is compulsory and you have to specify it. +

| n/NAME |
* Substitute `NAME` with the name of the exercise. +

* `n/NAME` is optional. +

* `n/NAME` is case sensitive. +
e.g. An exercise named `pushup` will be considered to have a different name as an exercise named `Pushup`.

| d/DATE |
* Substitute `DATE` with the date of the exercise. +

* `d/DATE` is optional. +

* `DATE` must be of the form `DD-MM-YYYY` (ie. 02-07-2020 for 2nd July 2020)

| [reps/REPS] |
* Substitute `REPS` with the reps of the exercise. +

* `reps/REPS` is optional.

* Range for `REPS` is 1-9999. +

| [sets/SETS] |
* Substitute `SETS` with the sets of the exercise. +

* `sets/SETS` is optional.

* Range for `SETS` is 1-9999. +

| [ew/WEIGHT] |
* Substitute `Weight` with the weight of the exercise. +

* `ew/WEIGHT` is optional.

* Range for `WEIGHT` is 1-9999. +
|====================
==== Example

==== Common errors / problems

=== Delete a client's exercise: `delete-e`

Deletes an existing exercise at the specified index from the exercise list of the client currently being viewed.

Format: `delete-e INDEX`

* `delete-e` can only be used when a client is in view (ie. `view-c` is called first)
* `INDEX` refers to the index number shown in the displayed exercise list of the client currently being viewed
* `INDEX` must be a positive integer (ie. 1, 2, 3, ...)

Examples:

* `view-c 1`
+
`delete-e 4`
+
** Deletes the 4th exercise from the exercise list of the 1st client

=== Schedule trainings for a client: `schedule`

Assigns weekly schedule timings to a client. The schedule will be displayed on the right panel of FitBiz, with the timings as well as the client's name. This command can assign multiple schedules to a client at once, by adding more arguments following the command.

Format: `schedule INDEX day/DAY st/STARTTIME et/ENDTIME`

* `INDEX` refers to the index number shown on the displayed client list
* `INDEX` must be a positive integer(ie. 1, 2, 3, ...)
* `INDEX` must be for an existing client index number
* `DAY` must be any one of the following values:
** MON
** TUE
** WED
** THU
** FRI
** SAT
** SUN
* `DAY` is not case-sensitive

Examples:

* `schedule 1 day/mon st/1100 et/1200`
** Adds to the 1st client a schedule for training from 11:00am to 12:00pm on Monday

=== Export as CSV: `export` [Coming in v1.4]

Exports a client’s training record to a CSV file.

Format: `export INDEX`

* `INDEX` refers to the index number shown in the displayed client list
* `INDEX` must be a positive integer (ie. 1, 2, 3, ...)

Example:

* `export 6`
** Exports training records of the 6th client

=== Filter clients based on attribute: `filter-c` [Coming in v1.4]

Filters the client list by the specified keyword(s) that matches the name or any attributes the client has.

Format: `filter-c KEYWORD [MORE_KEYWORDS]`

* The search is case insensitive. e.g `push ups` will match `Push Ups`
* The order of the keywords does not matter (e.g. `Push Pull` will match `Pull Push`)
* Only full words will be matched e.g. `Push` will not match `Push Pull`
* Clients matching at least one keyword will be returned (i.e. `OR` search). e.g. `Hans Bo` will return `Hans Gruber, Bo Yang`

Examples:

* `filter-c Johnny`
** Returns a client list of `Johnny Tim` and `johnny`

=== Display visualisations of training progress: `graph` [Coming in v1.4]

Shows visualisations of a client’s exercise progress.

Format: `graph e/EXERCISE_NAME [s/START] [e/END]`

* Generates a graphical representation of the client’s progress
* If `START` or `END` is not specified, it will default to the current month
* Date format of `[s/START]`, `[e/END]` is `DD-MM-YYYY`
* This command can only be used while viewing a client (ie. right after `view-c` is used)

Examples:

* `graph e/Push Ups`
** Shows a graph of Ming Liang’s Push Ups progress over the current month

=== View schedule for the day/week: `view-s` [Coming in v2.0]

Shows the schedule for today or the time specified.

Format: `view-s TYPE`

* `TYPE` must be either `today`, `week` or `month`

Examples:

* `view schedule today`
** Shows the schedule for today
* `view schedule week`
** Shows the schedule of the current week

== FAQ

*Q*: How do I transfer my data to another Computer? +
*A*: Install the app in the other computer and overwrite the empty data file it creates with the file that contains the data of your previous FitBiz folder.

== Command Summary

=== General Commands

[width="100%",cols="20%,<30%",options="header",]
|=======================================================================
|Command | Summary
|`export INDEX`| Exports client's training record to a CSV file.
|`help`| Shows all available commands and their description.
|`view-s TYPE`| Shows schedule for today or time specified.
|=======================================================================

=== Client Commands

[width="100%",cols="20%,<30%",options="header",]
|=======================================================================
|Command | Summary
|`add-c n/NAME p/PHONE_NUMBER e/EMAIL [t/TAG]…`| Adds a new client into FitBiz.
|`delete-c INDEX`| Deletes a client and its associated exercises.
|`edit-c INDEX [n/NAME] [p/PHONE] [e/EMAIL] [t/TAG]…​`| Edits an existing client.
|`filter-c KEYWORD [MORE_KEYWORDS]`| Filters a client based on specified keywords.
|`list-c`| Shows the list of clients in FitBiz.
|`view-c INDEX`| Shows detailed information of a client.
|`schedule INDEX [day/DAY] [st/STARTTIME] [et/ENDTIME]`| Assigns a schedule to a client.
|=======================================================================

=== Exercise Commands

[width="100%",cols="20%,<30%",options="header",]
|=======================================================================
|Command | Summary
|`add-e n/EXERCISE_NAME d/DATE ew/WEIGHT reps/REPS sets/SETS`| Adds a new exercise to a client.
|`delete-e INDEX`| Deletes an exercise in the exercise list of the client.
|`graph e/Push Ups`| Shows a graph of the exercise progress done by a client.
|=======================================================================
