= CodeCampX - User Guide
:site-section: UserGuide
:toc:
:toc-title:
:toc-placement: preamble
:sectnums:
:imagesDir: images
:stylesDir: stylesheets
:xrefstyle: full
:experimental:
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
endif::[]
:repoURL: https://github.com/se-edu/addressbook-level3

By: `Team SE-EDU`      Since: `Jun 2016`      Licence: `MIT`

== Introduction

AddressBook Level 3 (AB3) is for those who *prefer to use a desktop app for managing contacts*. More importantly, AB3 is *optimized for those who prefer to work with a Command Line Interface* (CLI) while still having the benefits of a Graphical User Interface (GUI). If you can type fast, AB3 can get your contact management tasks done faster than traditional GUI apps. Interested? Jump to the <<Quick Start>> to get started. Enjoy!

. Define a very specific _target user profile_.

Coding bootcamp
(Reasonable to assume that officers are educated enough to prefer typing)

. Define a clear _value proposition_ that matches the target user profile i.e., what problem does the product solve? How does it make the the user's life easier?
* *[Staff Management]* Helps the owner to schedule teachers
* *[Student Management]* Helps the owner to keep track of students progress
* *[Finances Management]* Helps the owner to track finances (profits and expenses)
* *[Courses Management]* Schedule courses

Hierarchy: Owner -> Admin Staff-> Teachers -> Students -> Progress +
Each owner has a few teachers, each admin staff takes care of a few teachers, each teachers has a few students, each students has a progress

. Optimize the product to the chosen target users i.e., add features that are especially/only applicable for target users (to make the app especially attractive to them).
Sheng Xue: I will try to organise in terms of when the feature should be done. I.e For each of the 4 functions, those on top should be done early, and those on the bottom will be done later. +
*[Staff Management]* +
*[Must-have] [Week 7]* +
As an owner, I want to be able to add and delete teachers, so I can hire and fire teachers.

*[Must-have] [Week 7]* +
As a user, I want to be able to promote or fire my teachers in the system.

*[Must-have] [Week 8]* +
As a user, I want to be able to edit the details of the teachers such as their incomes, so that their incomes will be automatically deducted from the finances of the tuition centre (STAFF>FINANCE)

*[Must-have] [Week 9]* +
As a user, I can specify the availability of the teachers, so that I can easily assign available teachers to teach specific courses. (STAFF -> COURSES)

*[Must-have] [Week 10]* +
As a user, I can specify the skill levels and the courses that the teachers can teach.

*[Nice-To-Have] [Week 11]* +
As a user, I want to mark the attendance of my teachers, so that I can track their number of work hours

*[Nice-To-Have] [Week 12]* +
As a user, I want to be able to give bonuses or raises based on the teachers’ performance so as to encourage better performance by the teacher.

*[Nice-To-Have] [Week 13]* +
As a user, I want to know who are the backup teachers in case the one on duty is not available (sick or leave) so that we can ensure that all classes can be taught




*[Student Management]* +
*[Must-have] [Week 7]* +
As an owner, I want to add or drop students based on the sign ups and quitting of the students.

*[Must-have] [Week 7]* +
As a user, I want to edit the student’s details such as the courses that they are taking and their parent’s contact, so that I can contact them whenever necessary.

*[Must-have] [Week 8]* +
As a user, I want to be able to track the amount of homework done so as to ensure that the students are kept up to speed with the learning material

*[Must-have] [Week 8]* +
As a user, I want to know be able to key in the test scores of the students over the period of the course, so that I can understand the effectiveness of the materials taught.

*[Must-have] [Week 9]* +
As a user, I want to know how many students I have during each month, so that I can track if sign-up rates have been reached.

*[Nice-To-Have] [Week 10]* +
As a user, I want to be able to key in the feedback of each student at the end of each week, so that I can better understand what kind of improvements I should make.

*[Nice-To-Have] [Week 11]* +
As a user, I want to mark the attendance of my students for each class, so that I can track the attendance of each class and students.

*[Nice-To-Have] [Week 12]* +
As a user, I want to compare students’ performance in a class, so that I can have an overall view of the class performance.

*[Nice-To-Have] [Week 12]* +
As a user, I want to make analysis based on student sign-up/ drop out rate, so that I can know the current running business makes money

*[Nice-To-Have] [Week 13]* +
As a user, I want to save student’s birthday, so that I can have a “surprise birthday party” for students


*[Finances Management]* +
*[Must-have] [Week 7]* +
As a user, I want to be able to automate the spendings of the tuition centre due to the salary of the staff, so that I do not need to manually deduct the savings from the salary at the end of the month.

*[Must-have] [Week 7]* +
As a user, I want to be able to automate the income generated by each of the students according to the course fees payable by the students, so that I do not need to manually add the income generated at the end of the month.

*[Must-have] [Week 8]* +
As a user, I want to be able to know how much we are spending by adding the name and price of the items or services bought.

*[Must-have] [Week 9]* +
As a user, I want to tag each of the spendings of the tuition centre with the priority levels, such as “must-have”, “nice-to-have”, or “not-needed”, so that I can evaluate the spendings of the tuition centre.

*[Must-have] [Week 10]* +
As a user, I want to be able to know how much we are earning by adding the various sources of income such as through students course fees, or miscellaneous sources like textbook sales.

*[Must-have] [Week 11]* +
As a user, I want to be able to tag each of the spendings with the department that they are from, so that I can better understand which department is spending on what types of goods and services.




*[Nice-To-Have] [Week 12]* +
As a user, I can view the statistics of the finances at periods such as day, week of month, so that I can better plan ahead.

*[Nice-To-Have] [Week 13]* +
As a user, I want to be able to track the payment status of each customer so that we can ensure that all customers have paid on time.

*[Courses Management]*

*[Must-have] [Week 7]* +
As a user, I can add or remove courses from the system.

*[Must-have] [Week 7]* +
As a user, I should be able to edit the course details, especially the costs of the courses, so that I can automate the income generated from these courses.

*[Must-have] [Week 8]* +
As a user, there can be multiple ongoing sessions of each course in a period of time, and I can assign students and teachers to these course sessions.

*[Must-have] [Week 8]* +
As a user, I can assign the classrooms for each course session, so that I can better plan out the location requirements.

*[Must-have] [Week 9]* +
As a user, I can add logistics requirements of the courses such as scissors, electronic equipment, so that I can better plan out my logistics.

*[Must-have] [Week 9]* +
As a user, I can add the course’s curriculum and homework requirements to the students when they are added, so that I can keep track of the student’s progress.

*[Must-have] [Week 10]* +
As a user, I can add the feedback and review ratings of the courses, so that I can keep track of the course’s satisfaction ratings.

*[Nice-To-Have] [Week 10]* +
As a user, I can clone a current copy of the course session, so that I do not need to start from scratch every time I am adding a new course session.

*[Nice-To-Have] [Week 11]* +
As a user, I can look at the overview of the courses to see which courses are the most popular or sustainable, so that I can better plan out potential future courses or make changes to existing ones.

*[Nice-To-Have] [Week 12* +
As a user, I am able to add a list of teachers who are experienced with each of the courses, so that I can prioritise those teachers when I am assigning teachers for a course.

*[Nice-To-Have] [Week 13]* +
As a user, I am assign the teachers to each course based on their own preferences.
































Group: AY1920S2-CS2103-W14-1 +
+++<u>+++User Guide for +++</u>++++++<u>+++*Code Camp X*+++</u>++++++<u>+++:+++</u>+++

. Overview of Code Camp X
. Features
.. Student Population Management
.. Teachers and Staff Management
.. Course and Curriculum Management
.. Finance and Payment Tracking
... Track total revenue and expenses
... Track student’s payment and whether it’s on time
... Track payroll
... Track profitability by course
. Commands
.. +++<u>+++*General*+++</u>+++ Commands
_See the specific feature sections for possible parameters_

... +++<u>+++_add_+++</u>+++ command
Command: ‘add <object> <parameters>’ +
Description: This will add a respective object into the
corresponding list.

... +++<u>+++_delete_+++</u>+++ command
Command: ‘add <object> <objectIndex>’ +
Description: This will delete a specified object from the corresponding list

... +++<u>+++_edit_+++</u>+++ command
Command: ‘add <object> <objectIndex> <parameters>’ +
Description: This will edit parameters of the specified object

... +++<u>+++_find _+++</u>+++command
Command: ‘find <object> <parameters>’ +
Description: This will search the corresponding lists for all object names which matches the objectDescription.

... +++<u>+++_help_+++</u>+++ command
Command: ‘help’ +
Description: This will bring up all possible commands for you to know what commands and parameters to use.


.. +++<u>+++*Student Management*+++</u>+++ Commands
... Adding a student
Command: 	‘add-student<parameters>’ +
Parameters:

. ‘n/ <new student’s name>’
. co/ <new course name>’

... Deleting a student
Command: 	‘delete-student studentIndex’

... Editing a student details
Command: 	‘edit-student studentIndex <parameters>’ +
Parameters:

. ‘n/ <new student name>’
. ‘co/ <new course name>’
. ‘cu/ <new curriculum assignment>’
. ‘pp/ <new payment plan>’

... Finding for a student entry by specified parameters
Command: 	‘find-student <parameters>’ +
Parameters:

. ‘sn/ <studentName>’ - find by student name
. ‘co/ <courseName>’ - find students taking similar courses

... Assigning a student for a course
Command: 	‘assign student studentID courseID’ +
Note: A Course Fee will be assigned to the student when he/she is assigned to a course

.. +++<u>+++*Teachers and Staff*+++</u>+++ Management Commands
... Adding a teacher
Command: 	‘add-teacher <parameters>’ +
Parameters:

. ‘n/ <new teacher’s name>’
. ‘s/ <new teacher’s salary>’

... Deleting a teacher
Command: 	‘delete-teacher studentIndex’

... Editing a teacher details
Command: 	‘edit-teacher teacherIndex <parameters>’ +
Parameters:

. ‘n/ <new teacher name>’
. ‘co/ <new course name taught>’
. ‘s/ <new teacher’s salary>’

... Finding for teachers entry by specified parameters
Command: 	‘find-student <parameters>’ +
Parameters:

. ‘n/ <teacher’s name>’ - find by teacher’s name
. ‘co/ <course taught>’ - find teachers by similar courses taught
. ‘s/ <value>’ - find teachers who earn within the specified values

... Assigning a teacher to a course
Command: 	‘assign teacher teacherID courseID’

.. +++<u>+++*Course and Curriculum*+++</u>+++ Management Commands
... Adding a course
Command: ‘add-course <parameters>’ +
Parameters:

. ‘n/ <course name>’
. ‘cid/ <course id>’

... Adding a curriculum
Description: Curriculum is a list of tasks and its respective deadlines to be done by +
Command: ‘add-curriculum <parameters>’ +
Parameters:

. ‘currID/ <curriculum id>’
. ‘currDesc/ <varargs of task names>’
. ‘taskDL/ <varargs of deadlines>’
Note: the number of currDesc and taskDL must match, else error will be thrown.

... Assigning objects to a course
Description: Each course must have a curriculum to be taught, an accompanying teacher, and students to be taught +
Command: ‘assign course <parameters>’ +
Parameters:

. ‘currID/ <curriculum id>’
. ‘sID/ <studentID>’
. ‘tID/ <teacherID>’

... Editing a course
Command: ‘edit-course <parameters>’ +
Parameters:

. ‘cn/ <course name>’
. ‘currID/ <curriculumID>’


.. +++<u>+++*Finance and Payment*+++</u>+++ Tracking Commands
... Adding a FinanceInfo
Command: ‘add-finance <parameters>’ +
Parameters:

. ‘n/ <finance name>’
. a/ amount

... Editing a FinanceInfo
Command: ‘add-finance<parameters>’ +
Parameters:

. ‘n/ <finance name>’
. a/ amount










Student:  +
Name ‘n/ <new student’s name>’  +
AssignedCourse co/ <new course name>’

Teacher +
Name n/ <new teacher’s name>’ +
Salary ‘s/ <new teacher’s salary>’

Course ‘n/ <course name>’ +
Name ‘n/ <course name>’ +
ID ‘cid/ <course id>’


Finance +
‘Name n/ <finance name>’ +
a/ amount








