= CodeCampX - User Guide
:site-section: UserGuide
:toc:
:toc-title:
:toc-placement: preamble
:sectnums:
:imagesDir: images
:stylesDir: stylesheets
:xrefstyle: full
:experimental:
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
endif::[]
:repoURL: https://github.com/se-edu/addressbook-level3

By: `Team SE-EDU`      Since: `Jun 2016`      Licence: `MIT`

== Introduction

Code Camp X (CCX) is for those who *prefer to use a desktop app to manage the administrative tasks of running a coding camp*.
More importantly, CCX is *optimized for those who prefer to work with a Command Line Interface* (CLI) while still having the benefits of a Graphical User Interface (GUI).
If you can type fast, CCX can allow you to manage your camp's administrative tasks faster than traditional GUI apps.
Interested? Jump to the <<Quick Start>> to get started. Enjoy!

=== Adding a homework: `add homework`

Adds a homework to the list of homework +
Format: `add homework n/NAME d/DEADLINE`

* `add n/Function Programming Assignment d/2020-01-30`

=== Listing all homework : `list homework`

Shows a list of all homework. +
Format: `list homework`

=== Listing all homework for a course: `list homework`

Shows a list of all homework assigned to a course. +
Format: `list homework c/courseID`

Examples:

* `list homework c/001'

=== Editing a homework : `edit homework`

Edits an existing person in the address book. +
Format: `edit homework HOMEWORKID [n/NAME] [d/DEADLINE]`

****
* Edits the homework with the specified `HOMEWORKID'. The homeworkID *must exists* in the list of homework.
* At least one of the optional fields must be provided.
* Existing values will be updated to the input values.
****

* `edit 001 n/Machine Learning Assignment e/2020-02-30` +
Edits the name and deadline of the homework with ID of 001 to be `Machine Learning Assignment` and `2020-02-30` respectively.

=== Locating homework by KEYWORD/ID/DEADLINE: `find homework`

Finds homework with the any of the given keywords/ID/deadline +
Format: `find homework [k/KEYWORDS] [id/HOMEWORKID] [d/DEADLINE]

****
* The search is case insensitive. e.g `hans` will match `Hans`
* Only the name is searched.
* Only full words will be matched e.g. `Han` will not match `Hans`
* Only 1 of the parameters can be present
* HOMEWORKID must be valid.
* DEADLINE must be properly formatted
****
-update
* `find k/Machine` +
Returns any homework with `Machine` in its name such as - `Machine Learning Assignment`, `Reinforcement Learning Assignment`
* `find d/2020-01-30` +
Returns any homework with a deadline of `2020-01-30`