= CodeCampX - User Guide
:site-section: UserGuide
:toc:
:toc-title:
:toc-placement: preamble
:sectnums:
:imagesDir: images
:stylesDir: stylesheets
:xrefstyle: full
:experimental:
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
endif::[]
:repoURL: https://github.com/se-edu/addressbook-level3

By: `Team SE-EDU`      Since: `Jun 2016`      Licence: `MIT`

== Introduction

Code Camp X (CCX) is for those who *prefer to use a desktop app to manage the administrative tasks of running a coding camp*.
More importantly, CCX is *optimized for those who prefer to work with a Command Line Interface* (CLI) while still having the benefits of a Graphical User Interface (GUI).
If you can type fast, CCX can allow you to manage your camp's administrative tasks faster than traditional GUI apps.
Interested? Jump to the <<Quick Start>> to get started. Enjoy!

=== Assignment
==== Adding a Assignment: `add Assignment`

Adds a Assignment to the list of Assignment +
Format: `add Assignment n/NAME d/DEADLINE`

* `add n/Function Programming Assignment d/2020-01-30`

==== Listing all Assignment : `list Assignment`

Shows a list of all Assignment. +
Format: `list Assignment`

==== Listing all Assignment for a course: `list Assignment`

Shows a list of all Assignment assigned to a course. +
Format: `list Assignment c/courseID`

Examples:

* `list Assignment c/001'

==== Editing a Assignment : `edit Assignment`

Edits an existing person in the address book. +
Format: `edit Assignment AssignmentID [n/NAME] [d/DEADLINE]`

****
* Edits the Assignment with the specified `AssignmentID'. The AssignmentID *must exists* in the list of Assignment.
* At least one of the optional fields must be provided.
* Existing values will be updated to the input values.
****

* `edit Assignment 001 n/Machine Learning Assignment e/2020-02-30` +
Edits the name and deadline of the Assignment with ID of 001 to be `Machine Learning Assignment` and `2020-02-30` respectively.

==== Locating Assignment by KEYWORD/ID/DEADLINE: `find Assignment`

Finds Assignment with the any of the given keywords/ID/deadline +
Format: `find Assignment [k/KEYWORDS] [id/AssignmentID] [d/DEADLINE]

****
* The search is case insensitive. e.g `hans` will match `Hans`
* Only the name is searched.
* Only full words will be matched e.g. `Han` will not match `Hans`
* Only 1 of the parameters can be present
* AssignmentID must be valid.
* DEADLINE must be properly formatted
****

Examples:

* `find Assignment k/Learning` +
Returns any Assignment with `Learning` in its name such as - `Machine Learning Assignment`, `Reinforcement Learning Assignment`
* `find Assignment d/2020-01-30` +
Returns any Assignment with a deadline of `2020-01-30`

=== Finance
==== Adding a finance: `add finance`

Adds a finance to the list of finance +
Format: `add finance n/NAME a/AMOUNT`

* `add n/Paid NUS for textbooks a/2000`

==== Listing all finance : `list finance`

Shows a list of all finance. +
Format: `list finance`

==== Editing a finance : `edit finance`

Edits an existing finance in the address book. +
Format: `edit finance FINANCEID [n/NAME] [a/AMOUNT]`

****
* Edits the finance with the specified `FINANCEID'. The financeID *must exists* in the list of finances.
* At least one of the optional fields must be provided.
* Existing values will be updated to the input values.
****

* `edit finance 001 n/Purchased Crayons a/20` +
Edits the name and amount of the finance with ID of 001 to be `Purchased Crayons` and `20` respectively.

==== Locating finance by KEYWORD/ID/DEADLINE: `find finance`

Finds finance with the any of the given keywords/ID/amount +
Format: `find finance [k/KEYWORDS] [id/FINANCEID] [a/AMOUNT]

****
* The search is case insensitive. e.g `nus` will match `NUS`
* Only the name is searched.
* Only full words will be matched e.g. `NUS` will not match `NUSSU`
* Only 1 of the parameters can be present
* AssignmentID must be valid.
* AMOUNT must be properly formatted
****

Examples:

* `find finance k/NUS` +
Returns any finance with `NUS` in its name such as - `Bought textbooks from NUS`, `NUS bonding day`
* `find finance a/200` +
Returns any finance with an amount of `200`

=== Course
==== Add a course: `add course`

Add a new course to the list of course +
Format: `add course n/NAME`
Example:

* `add course n/Programming Methodology`

==== List all courses: `list course`
Shows a list of all courses
Format: `list course`

==== List all students in a course: `list course student`
Shows a list of all students in a course +
Format: `list c/courseID --students`

=== Student
==== Add a student: `add student`

Add a new student to the list of student +
Format: `add student n/NAME` +
Example:

* `add student n/Jon Snow`

==== Remove a student: `remove student`
Remove a student from the list of students +
Format: `remove student studentID`

==== List all students: `list student`
Shows a list of all students
Format: `list course`

==== Edit information about a student: `edit student`
Edits an existing student in the student list
Format: `edit student s/studentID [n/NAME] [d/DESCRIPTION]` +
Example:

* `edit A0131120E n/Aegon Targaryen d/Son of Lyanna Stark and Rhaegar Targaryen`

==== Assign a student to a course: `assign student to course`
Assign an existing student in the student list to a course in the course list
Format: `assign student s/studentID course c/courseID`

=== Teacher
==== Add a teacher: `add teacher`

Add a new teacher to the list of teachers +
Format: `add teacher n/NAME` +
Example:

* `add teacher n/Ned Stark`

==== Remove a teacher: `remove staff`
Remove a teacher from the list of teachers +
Format: `remove teacher teacherID`

==== Edit information about a teacher: `edit teacher`
Edit an existing teacher in the teachers list
Format: `edit teacher s/teacherID [n/NAME] [d/DESCRIPTION]` +
Example:

* `edit A0131120E n/Ned Stark d/Lord of Winterfell`

==== Assign a teacher to a course: `assign teacher to course`
Assign an existing teacher in the teacher list to a course in the course list
Format: `assign teacher s/teacherID course c/courseID`

=== Staff

==== Add a staff: `add staff`
Add a new staff to the list of staffs +
Format: `add staff n/NAME`

==== Remove a staff: `add staff`
Remove a new staff to the list of staffs +
Format: `remove staff staffID`

==== Edit information about a staff: `edit staff`
Edit an existing teacher in the staff list +
Format: `edit staff s/teacherID [n/NAME] [d/DESCRIPTION]`