# **CookBuddy Recipe Manager**
:site-section: UserGuide
:toc:
:toc-title:
:toc-placement: preamble
:sectnums:
:imagesDir: images
:stylesDir: stylesheets
:xrefstyle: full
:experimental:
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
endif::[]
:repoURL: https://github.com/AY1920S2-CS2103T-W12-4/main/

By: `AY1920S2-CS2103T-W12-4`      Since: `Feb 2020`      Licence: `MIT`

== Introduction

This user guide provides documentation on CookBuddy such as a quick start guide and an overview of its features.

*CookBuddy* is for users who prefer a desktop application for managing recipes.
More importantly, *CookBuddy* is optimized for those who prefer to work with a Command Line Interface (CLI) while still having the benefits of a Graphical User Interface (GUI).

If you are a fast typist, *CookBuddy* can manage your recipes faster than applications that use a GUI.
Interested?
Proceed to <<Quick Start>> to get started!

=== How to navigate this User Guide

Throughout this guide, you may come across a few symbols.
They are used to draw your attention to important or note-worthy information.

Here are the symbols this User Guide uses:

[NOTE]
This block displays additional *notes* that contains extra information that you should take note of.

[TIP]
This block displays *tips* that you may find useful.

== Quick Start
1. Ensure you have Java 11 or later installed on your machine.
    - If not, download and install the latest Java Runtime Environment from https://www.java.com/en/download/[here].

2. Download the latest CookBuddy.jar from https://github.com/AY1920S2-CS2103T-W12-4/main/releases[here].

3. Copy the file to the folder you want to use as the home folder for *CookBuddy*.

4. Double-click the executable to start the app. CookBuddy's GUI should appear in a few seconds.

5. Type your command in the command box and press Enter to execute it.
   e.g. typing `help` and pressing Enter will open the help window.

6. Some example commands you can try:

   * `list` : lists all recipes in the recipe book

   * `new recipe n/Ham Sandwich ing/bread, 2 slices; ham, 1 slice ins/put ham between bread; serve on plate`:
    adds a recipe named "Ham Sandwich" to *CookBuddy*.

   * `delete 3` : deletes the 3rd recipe shown in the current list

   * `exit` : exits *CookBuddy*

7. Refer to <<Features>> for details of each command.

==  Features
COMMAND FORMAT:

* Words in `UPPER_CASE` are the values of the parameters to be supplied by the user.
    ** In `find n/RECIPE_NAME`, `RECIPE_NAME` is the value of the `n/` parameter supplied to the `find` command.

* Words in square brackets indicate that they are optional. `[t/TAG]` means the `t` parameter (tag) is optional.

===  Help — `help (V1.4)`
Lists out all the commands accepted by *CookBuddy*.
If a command name is specified, it will specify how to use that command.

=== Create a Recipe — `new`
Adds a new recipe to *CookBuddy*.

Format: `new n/NAME ing/INGREDIENT, QUANTITY [; ...] ins/INSTRUCTION [; ...] [cal/CALORIES] [s/SERVING_SIZE]
[r/RATING] [t/TAG [, ...]]`

Example: `new n/Fried Rice ing/White rice, 1 cup; salt, 1 gram ins/Fry the rice; add salt`

[NOTE]
Parameters in *bold* indicate they are mandatory.

*CookBuddy* accepts the following parameters:

    * `n/` - *name*
    * `ing/` - *ingredients*
    * `ins/` - *instructions*
    * `cal/` - calories (in kcal)
    * `s/` - serving size (any number greater than 0)
    * `r/` - rating (scale of 0 to 5)
    * `d/` - difficulty (scale of 0 to 5)
    * `t/` - tags (seperated by commas)

=== Delete a Recipe — `delete`
Deletes a recipe from *CookBuddy*.

Format: `delete INDEX`

=== Modify a Recipe — `modify`
Modifies attributes of a recipe.

Format: `modify INDEX [ing/INGREDIENT, QUANTITY [; ...]] [ins/INSTRUCTION [; ...]] [cal/CALORIES] [s/SERVING_SIZE]
[r/RATING] [t/TAG [, ...]]`

Example 1: `modify 1 ing/ham, 2 slices`

Modifies the ingredients of the 1st recipe in the list to contain only 2 slices
of ham.

Example 2: `modify 2 ins/boil eggs; slice apples`

Modifies the instructions in the 2nd recipe to contain two instructions:

    * boil eggs
    * slice apples

=== List Recipes — `list`
Lists out all the recipes managed by *CookBuddy*.

=== Find Recipes — `find`
Find recipes with a particular parameter.

[NOTE]
*CookBuddy* can find recipes from one parameter at a time.

==== Find by name - `find [n/NAME [...]]`
Example: `find n/sandwich`
Finds recipes that contain the word `sandwich` in their name.

==== Find by ingredient - `find [ing/INGREDIENT [...]]`
Example: `find ing/bread`
Finds recipes that contain the word `bread` in their ingredients.

=== Count Recipes — `count`
Displays the total number of recipes stored in *CookBuddy*.

//=== View a Recipe — `view RECIPE_INDEX (V1.3)`
//Opens the recipe at `RECIPE_INDEX` to view.
//
//=== Tag a Recipe — `tag <index> <tag_type> <tag> (V1.3)`
//Tags a recipe at the specified index with the tag of tag_type.
//
//Example: `tag 1 cuisine french` would assign the tag `cuisine: french` to the recipe at index 1.

// ==== Tag recipes as containing allergens — `tag allergen <index> [ingredient] <allergen>`
// Tags a recipe (and the ingredient, if specified) as containing `allergen`.

// ==== Tag the meal type of a recipe — `tag meal <index> <meal type>`
// Tag the recipe as `meal type` such as breakfast/lunch/dinner

// === Duplicate Recipe — `dup <index>`
// Duplicates the recipe found at the specified index, and places the new recipe at `index + 1`
// Useful for users who wish to experiment with recipes while keeping a copy of the original.

=== Deleting all recipes - `reset`
Removes all recipes from *CookBuddy*.

=== Exiting the program - `exit`
Exits *CookBuddy*.
